### ISSUE TITLE
Text decode get an incorrect value, when input is special encode.

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#1017]
I try to use a special encode(Buffer.from('2453545782b92053d401', 'hex')) as a parameter of the Text. Then, I have no way to restore the input parameter, because the input parameter lost some information in the conversion to a string with utf-8. I guess because “0x82” is a special code in utf-8.

In fact, this problem cause me to get an incorrect tx hash. Is there a way to solve it？

```javascript
Buffer.from(
  new Text(Buffer.from('2453545782b92053d401', 'hex')).toU8a()
).toString('hex') 
=== '3c535457efbfbdefbfbd2053efbfbd01'  // it should be 2453545782b92053d401
```

**Comment by jacogr** [comment]
`toU8a()` will always encode it with SCALE. This means that it has extra length encoding added. If you want the raw bytes (not for transfer to/from node), you can pass the `isBare` flag, i.e. `new Text(...).toU8a(true)`, which will not include the prefix.

In the above example, you certainly don't want the length encoding added.

**Comment by aniiantt** [comment]
> `toU8a()` will always encode it with SCALE. This means that it has extra length encoding added. If you want the raw bytes (not for transfer to/from node), you can pass the `isBare` flag, i.e. `new Text(...).toU8a(true)`, which will not include the prefix.
> 
> In the above example, you certainly don't want the length encoding added.
> 
> Additionally, when you are passing in raw Uint8Array values (Buffer extends Uint8Array), it always wants to length prefix added. So there is an additional problem there.
> 
> Either -
> 
> * pass just the string
> * pass it directly as hex, i.e. `new Text('0x2453545782b92053d401')` (without the conversion to buffer)
> 
> EDIT: The second option doesn't work, for some reason the Text does not allow hex inputs as it should. That should be adjusted to cater for it.

I'm sorry, maybe I can't express myself very well. But I don't mean compact prefix and hex. I mean the loss of information during the utf-8 conversion in some cases. 

For example: 
![image](https://user-images.githubusercontent.com/7029338/59551068-862dc380-8fa6-11e9-89da-0497a955efb7.png)

In this case,  after converting to a string, the buffer cannot be converted to the original buffer. 

Similarly, 
https://github.com/polkadot-js/api/blob/9be7880938e47c7dbd3d271a49a917b10ac2658b/packages/types/src/primitive/Text.ts#L43

So in some cases, when an u8a is constructed as the parameter of Text，it is converted a string. If I want to get the original u8a, it is impossible because bad encoding conversion. It's not about Compact prefix.

**Comment by jacogr** [comment]
For "bad string inputs", not sure we want to do anything - `Text` is meant to be a representation of string values only. If you want to use random bytes, I would suggest `U8a`, `Bytes` (which adds a prefix).

**Comment by jacogr** [comment]
So going back to the original, Text didn't allow hex inputs, so this -

`new Text(Buffer.from('2453545782b92053d401', 'hex'))`

Would have encoded each byte - i.e. instead of the first byte being `24` you ended up with 2 bytes, the first `2` the second `4`. (That is addressed in the linked PR)

Additionally, the toHex/toU8a added the length. So you ended up with -

- an output twice as long
- and additional hex prefix

(This addesses both - https://github.com/polkadot-js/api/pull/1018 - i.e. https://github.com/polkadot-js/api/pull/1018/files#diff-5c5fb0a3fb824184977c4ae1afd825cbR21)

Just a small note - when you pass hex values to any types in polkadot/api, always add the `0x` prefix, otherwise it would treat it as string. (So even with the "can parse hex" PR above in, yours would have still decoded it as non-hex since it lacked a prefix.)
