### ISSUE TITLE
Api derive types should be correct

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1101]
E.g. here: https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/contracts/fees.ts#L47

It should not be BN, but the actual Codec type. derive is one of the rare places where we have typings, so let's make them correct.

tests should also be updated (e.g expect.any(BN) -> expect.any(BalanceOf))

**Comment by jacogr** [comment]
Don't quite agree on the tests, since that means we will have to circle back again after everything is reflected. so for the tests, `BN`

**Comment by amaurymartiny** [comment]
Why so? I suppose we'll be using `ClassOf` everywhere once we have reflected, so `ClassOf(...)` in api-derive, and `expect.any(ClassOf('...'))` in tests

**Comment by jacogr** [comment]
Yes, that works, just not 100% how the instanceof check works, since technically each time is a new class. 

(I just don't want to swap to eg. `BalanceOf` since that is certainly one that needs to be swapped to interface-only ASAP. Stuff like `BlockNumber` or `Balance` will probably hang about slightly longer, but will go away as well - primitives are safe.)

**Comment by jacogr** [comment]
Done.
