### ISSUE TITLE
API gets incorrect genesis configuration when instancing

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#1285]
The Substrate node has two instances of the collective module, Council and TechnicalCommittee. They are both given the same genesis configuration (no members). But one can easily specify different configurations as I've done in the [joshy-council-config branch](https://github.com/paritytech/substrate/tree/joshy-instance-config). That branch also contains a test showing that the initial storage is populated as expected in the substrate runtime (Thanks mostly to @thiolliere).

However, starting `substrate --dev` node and querying it with this script, shows that the technical committee is still empty.
```js
const { ApiPromise } = require('@polkadot/api');

async function main() {
  const api = await ApiPromise.create();

  let techMembers = await api.query.technicalCommittee.members();
  let councilMembers = await api.query.council.members();
  console.log(JSON.stringify(councilMembers));
  console.log(JSON.stringify(techMembers));
}

main().catch(console.error).finally(() => process.exit());
```

Apps gives even a different answer, showing that both committees were initialized with Alice as the sole member.
![image](https://user-images.githubusercontent.com/2915325/62808838-44f9f180-bac7-11e9-91a2-5f034d465caf.png)

**Comment by jacogr** [comment]
I really cannot comment on specific branches, too many variables involved. 

All I can suggest is that make sure you have a node and template that supports metadata v7, before that the queries did not work at all.

**Comment by jacogr** [comment]
Update to the above - all the API . does is make a query using the prefix and storage method as defined, i.e. https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata/v7/latest.substrate.v7.json#L2495

Nothing is inferred, the data is exactly as the node specified them. (As indicated, in v6 this was wrong, in v7 this was split - if there are more issues, it almost certainly does not quite sit on the API side since it only acts on what it receives)

**Comment by JoshOrndorff** [comment]
I've written more thorough tests, and it appears @jacogr is correct. This is indeed a substrate issue. I've opened https://github.com/paritytech/substrate/issues/3373 accordingly.
