### ISSUE TITLE
Shared/wrong value from 2 independent subscriptions

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#1310]
When a Substrate runtime has multiple instances of the same module, the Chain State UI incorrectly reports the storage state. When querying either instance, the UI reports the state of whichever instance was modified more recently.

Using the default Substrate node, you can reproduce this using the Council and TechnicalCommittee, because both are instances of the Collective module.
1. Launch a clean `--dev` chain
2. Use sudo to add Alice to the Council
3. Observe that both collectives report Alice as the sole Council member (on chain state tab).
4. Use sudo to add Bob to the Tech Committee
5. Observe that both collectives report Bob as the sole tech committee member (on chain state tab).
![image](https://user-images.githubusercontent.com/2915325/63032382-b4832e80-be83-11e9-8653-d164d99542d6.png)

The underlying API produces the correct results.
![image](https://user-images.githubusercontent.com/2915325/63032267-7ab22800-be83-11e9-9bf9-a872e28b28b8.png)

Note: I originally discovered this when exploring genesis configurations for instanced modules, abut the problem is broader than genesis configurations as described above.

**Comment by jacogr** [comment]
Follow-up - it is in the memozize -

![image](https://user-images.githubusercontent.com/1424473/63046784-70b81580-bed3-11e9-943a-a3e72be57578.png)

Basically it uses `toJSON`, but that only takes the params into account, not the actual function (for storage) as well. Which, well, creates a bit of an issue. So effectively it tries to memozie on this -

`state_subscribeStorage [[[{"name":"Events","modifier":"Default","type":{"PlainType":"Vec<EventRecord>"},"fallback":"0x00","documentation":[" Events deposited for the current block."]}]]]`

For all instances this is the same. (And actually is quite horrible since if the stuff above matches 100%, it could get even worse)
