### ISSUE TITLE
Nit: make `subscribeFinalizedHeads` and `subscribeNewHead` consistant

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#1322]
Please close if this is not an issue, but it seems weird that we have inconsistent plurality with `subscribeFinalizedHeads` and `subscribeNewHead`.

Seems like both should either be plural or singular `Head`.

**Comment by jacogr** [comment]
The RPCs map directly to substrate - 

https://github.com/paritytech/substrate/blob/master/core/rpc/src/chain/mod.rs#L70
https://github.com/paritytech/substrate/blob/master/core/rpc/src/chain/mod.rs#L88

So weird, yes, but not going to change in in the API without an underlying change.

**Comment by shawntabrizi** [comment]
Ill open an issue there, thanks

**Comment by jacogr** [comment]
Sadly it is one of those funny ones - as soon as exposed, it will actually make the API worse, since we support anything from 1.x onwards. So, basically it will probably end up with something really bad on the interface side (doubling-up, etc), so you cannot detect the exposed endpoints without a call.

So "fixing", creates a huge mess, although we have aliasses on the node RPC side, so the endpoint call may be renamed, but the API will always continue to point to the deprecated alias from that point onwards.
