### ISSUE TITLE
SignerPayload and ExtrinsicPayloadValue not support customized extrinsic

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#1355]
Usually customization of extrinsic adds extra fields, like the one we do on our chain adds two extra fields. These extra fields usually need to be passed to signer as part of ExtrinsicPayload.

Currently ExtrinsicPayloadValue and SignerPayload are quite specific to the default impl, because it uses method not extrinsic. Things were different at v0.81.x, which is the version we are upgrading our lib from.

**Comment by jacogr** [comment]
So looking at SignerPayload, the definition is as follow -

```js
Struct.with({
  address: 'Address',
  blockHash: 'Hash',
  blockNumber: 'BlockNumber',
  era: 'ExtrinsicEra',
  genesisHash: 'Hash',
  method: 'Call',
  nonce: 'Compact<Index>',
  runtimeVersion: 'RuntimeVersion',
  tip: 'Compact<Balance>',
  version: u8
})
```

So everything there is retrieved from the registry. It is however not in the registry itself, since there is no way atm to inject custom methods like `toPayload`. We can certainly make sure . it gets (as-is) into the registry and be pulled from there.

So I'm not sure what is suggested here?

**Comment by ianhe8x** [comment]
The keys of SignerPayload are fixed, I have no way to add more. (I want to add doughnut and feeExchange so the signer can recover the extrinsic from payload)

**Comment by jacogr** [comment]
Covered in #1357 & #1360
