### ISSUE TITLE
Support recursive datatypes

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#1394]
As explained in https://github.com/polkadot-js/apps/blob/master/packages/app-settings/src/md/basics.md types are registered in the order they are supplied. This prevents using some interesting data types such as the familiar [cons list](https://en.wikipedia.org/wiki/Cons).

It would be helpful to support such recursive data-types. As an example and test case, consider this rust code and the corresponding non-working type declaration.

```rust
#[derive(PartialEq, Eq, Clone, Encode, Decode, Debug)]
pub enum ConsList {
    End,
    Cons {
        head: u64,
        tail: Box<ConsList>,
    }
}
```

```json
{
    "Cons": {
        "head": "u64",
        "tail": "ConsList"
    },
    "ConsList": {
        "_enum": {
            "End": null,
            "Cons": "Cons"
        }
    }
}
```

**Comment by jacogr** [comment]
Just a comment - the “order of n which they are supplied” is actually not applicable anymore. Since we moved all the internal types to definitions as well - it is a bit tough (and unmaintainable over 100+ types - well, it is certainly much more than that)

So it has grown up a bit - which also helps. I know the apps docs are still outdated, however have not gotten around to that.
