### ISSUE TITLE
Decode custom struct Vec<u8> issue.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/api#1404]
How to use polkadot-js to decode custom struct (These's Vec<u8> type field in it)

Example:
struct defination in runtime:

```
#[derive(Encode, Decode, Default, Clone, PartialEq)]
#[cfg_attr(feature = "std", derive(Debug))]
pub struct Project {
   name: Vec<u8>,
   voted_members: u64,
   accumulative_weight: u64, 
}
```

register custom type in polkadot-js:
```
"Project": {
   "name": "Vec<u8>",
   "voted_members": "u64",
   "accumulative_weight": "u64"
  }
```

But the display output is wrong, all the bytes are decoded to field `name`

![3181568773705_ pic](https://user-images.githubusercontent.com/34789555/65110826-4266b200-da0c-11e9-9f62-14a54a470fd2.jpg)

![屏幕快照 2019-09-18 下午12 04 18](https://user-images.githubusercontent.com/34789555/65110892-7fcb3f80-da0c-11e9-868c-e7dd37565d55.png)

Note: if put name in the last will ok, but sometime have more than two Vec<u8>.  

```
#[derive(Encode, Decode, Default, Clone, PartialEq)]
#[cfg_attr(feature = "std", derive(Debug))]
pub struct Project { 
   voted_members: u64,
   accumulative_weight: u64, 
   name: Vec<u8>,
}
```

**Comment by jacogr** [comment]
Ok, so the length 29 shows the issue here. Any `Vec`, including `Vec<u8>` is encoded as `<length> + <bytes>`. So assuming an array of `[1, 2, 3, 4]`, the encoded value would be 5 in length, containing the following - `[4 << 2, 1, 2, 3, 4]`

The data your are feeding it does not have the length prefix, so the codec cannot know how many bytes to decode. In this case it uses the first byte (since that where the length should be) and uses that to correctly interpret the length. However the data passed is wrong - it doesn't have the length identifier.

**Comment by jiangfuyao** [comment]
Get the perfect answer
