### ISSUE TITLE
subscribeNewHeads hangs if called when node is syncing

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/api#1631]
If you connect API to a node that wasn't synced yet fully, subscribe gives you only one block and then hangs and does nothing, even if it's synced later. This behavior was the same on 1.x and continues to Kusama CC3 and latest API versions.

What is expected behavior?

- I suggest not returning anything until it's up-to date and then start sending blocks as normal. 
- Throw error, stating the node is still syncing. 
- Last resort would be to pipe synced blocks to subscription, but I can see potential performance issues with this. 

```javascript
await api.rpc.chain.subscribeNewHeads((header) => {
  console.log('new block', header.number.toNumber())
}
```

**Comment by jacogr** [comment]
This is expected behavior.

The node does the following -

- upon making a subscription, it sends the last known value
- when syncing, it does not send head updates (it could be 100's per second)

**Comment by jak-pan** [comment]
Is there a way to know that the node is fully synced? If yes, we can start listening after it's synced. If not, at the very least, node should start sending blocks after it syncs and probably shouldn't send last known value, otherwise it's leading to unexpected behavior.

**Comment by jacogr** [comment]
Changing the subscriptions to not send last-known, it even more problematic, it is done by design in Substrate, not by accident. 

For instance, if you subscribe to a balance and it only sends when changed (not initially), you will never get a value back until a transfer is received. And again, doing this would actually fit certain applications better than what the node currently does, and for others, create issues.

`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_health", "params":[]}' http://localhost:9933` -> `{"jsonrpc":"2.0","result":{"isSyncing":false,"peers":0,"shouldHavePeers":false},"id":1}`

So use `api.rpc.system.health` to get system info

**Comment by jak-pan** [comment]
> So use `api.rpc.system.health` to get system info

this is what I needed, thank you!
