### ISSUE TITLE
api.query.system.blockHash(blockNumber) always returns 0x0000000000000000000000000000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by DanielMagro97** [polkadot-js/api#1638]
When executing api.query.system.blockHash(blockNumber) in Javascript, using v0.98.1, passing any block number always returns 0x0000000000000000000000000000000000000000000000000000000000000000

**Comment by jacogr** [comment]
Run with `NODE_ENV=test <command>` or inspect the network in the UI you are using - what . does the node return?

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/70161582-93f21500-16bc-11ea-861a-422c7223cdfb.png)

The AP is correct is returning the default value.

**Comment by jacogr** [comment]
As per the code, it is correct -

- it gets populated on init, https://github.com/paritytech/substrate/blob/fc6914cdb8c322cea8a4591bbf9566dd23bfd143/frame/system/src/lib.rs#L630
- and removed on finalize, https://github.com/paritytech/substrate/blob/fc6914cdb8c322cea8a4591bbf9566dd23bfd143/frame/system/src/lib.rs#L650

If this worked on CC2 (and not on CC3), it is due to a trie-bug that neccesitated the upgrade to CC3, the trie was not correctly clearing map storage entries.,
