### ISSUE TITLE
`Option<()>` returns `isNone` true when `Some(())`

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#1724]
I have a simple storage map from `T::AccountId => Option<()>` acting like a boolean.

I set the storage of user to `()` indicating that boolean (`isSome`) should be true.

The Polkadot JS API seems to return `value.isSome === false`.

**Comment by jacogr** [comment]
Probably not going to fix this unless this pops up in the actual Substrate core, and even then it may have some reach and be quite tricky RPC-wise - the `()` acts like `Null` to the JS API since it is, well, nothing and empty encoded.

If you want a boolean, I would suggest using a boolean.

**Comment by shawntabrizi** [comment]
Ah, well it is in the new `Society` module, which is how I ran into this.

I could update the module so that we don't use `Option<()>` if this is an anti-pattern. The thought to use `Option<()>` was simply to reduce one bit of storage per user, but probably not worth it if this causes you problems.

**Comment by jacogr** [comment]
There def. is an issue, but it (may) be a tough one. Will dig and see, maybe I get lucky. 

Especially worried about subscriptions on these types of things (there are so loopholes, especially with multi subs, since the value for "not there" and "not changed" are the same on the RPC level)

**Comment by jacogr** [comment]
Ok, so looked at it somewhat and the issue is actually now what I expected, but rather in the Option type itself. So it actually indicates (internally) a None with a Null value and a Some with a non-Null. However, since the input is an empty tuple, it is equivalent to Null.

So there is an issue, probably need a re-look at the empty tuple stuff and the decoding thereof.

**Comment by shawntabrizi** [comment]
Thanks @jacogr !
