### ISSUE TITLE
`api.derive.accounts.idToIndex` returns `undefined`

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#1793]
I may be using this API completely wrong, so sorry ahead of time.

I am trying to add a feature to my front-end so that user accounts are shown using their index rather than their full address. To do this, I keep track of all the users in my front end, and then make a single query through the derive api to get their index and store it in a lookup object. The react hook looks like:

```js
  useEffect(() => {
    const unsubscribeAll = null;
    for (const user of users) {
      if (!(user in indices)) {
        api.derive.accounts.idToIndex(user, index => {
            setIndices({ ...indices, [user]: index });
        });
      }
    }
    return () => unsubscribeAll && unsubscribeAll();
  }, [api.derive.accounts, indices, setIndices, users]);
```

This was working fine at first with the two users in my system. However, when a third user was added, I noticed that their index was not appearing. By debugging, I found that the result of `api.derive.accounts.idToIndex` was `undefined`, and I had stored that null value into my lookup object so we didnt look it up again.

So I added a simple check to make sure that we only store real values into the lookup table:

```js
        api.derive.accounts.idToIndex(user, index => {
          if (index) { // Added this simple check
            setIndices({ ...indices, [user]: index });
          }
```

And now everything works. In the background, my front-end is now making multiple queries to `idToIndex`, only at some point which returns a real result.

So my conclusion is that this API is "lagging" where at some point it does not have the index I am trying to look up, and another point it does.

Just wanted to know if this is expected behavior.

**Comment by jacogr** [comment]
Yes, the signature is `(accountId: AccountId | string): Observable<AccountIndex | undefined>`, so it actually will result while it tries to build up the full list of indexes in the background.

It certainly can be `undefined` when there is no index. The lagging is due to the fact that it still needs to build up the list of all the indexes, so the early ones will return quicker than the later ones.

The multiple calls are actually fine, everything is caches so when you are doing `call(1)` somewhere and `call(1)` somewhere else, both on the RPC layer (assuming a call is active) and on the derive layer memomization is used.
