### ISSUE TITLE
api.query.system.account fn doesn't exist

### ISSUE THREAD

**Issue by qalqi** [polkadot-js/api#1853]
In https://polkadot.js.org/api/examples/promise/03_listen_to_balance_change/

its mentioned as   `let [previousNonce, { free: previousFree }] = await api.query.system.account(Alice);`
for previos free balance.

But that api.query.system.account fn doesn't seem to exist at api `1.2.0-beta.12`

Instead it should be
`let { free: previousFree } = await api.query.balances.account(Alice);`

**Comment by jacogr** [comment]
Ok, so there is no "doesn't not exist on the API" state as mentioned - the API purely decorates based on what the metadata provides. So if the chain you connect to does not have that functionality (e.g. in the case of Kusama, this will be the case, it is outdated as to current), it will not be available.

The documentation always tracks the latest Substrate master, you can see the functionality here - https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L299

This change is slightly more than 24 hours old on Substrate, so will take time to filter down to all networks. 

On old, non-current networks, the `system.accountNonce` functionality allows for this, as well as `balances.freeBalance` & `balances.reservedBalance` which is now not on latest anymore and combined in this query

**Comment by jacogr** [comment]
Additionally, the `balances.account` is actually not populated on chains where `system.account` is available - more that 1 day old versions of Substrate do indeed populate balances.account. (Which ia also different from the much older chains, where freeBalance is still used) 

However, if you run this against a current Substrate, you will see that the balances.account values stay at 0 at those locations, only system.account is used.

The derives actually cater for -

- old networks
- slightly newer networks
- current networks

by detecting what is on-chain - https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/balances/account.ts#L84

My suggestion would be to update your Substrate to latest - only the system.balances is used since the composite account merge went in.
