### ISSUE TITLE
Library compatibility with Secure EcmaScript

### ISSUE THREAD

**Issue by mpetrunic** [polkadot-js/api#2062]
Secure EcmaScript proposal: https://github.com/tc39/proposal-ses

### Steps to reproduce:
Only way we know how  to reproduce is to run build on:
https://github.com/NodeFactoryIo/metamask-snap-polkadot/tree/feature/connect-to-node

### Error:
```
Build success: 'build/index.js' bundled as 'dist/bundle.js'!
Snap evaluation error: possible import expression rejected around line 8527
```

Code:
![image](https://user-images.githubusercontent.com/8836210/76956534-83387880-6914-11ea-9f72-fb356d8d61c8.png)
Which makes no sense as that line contains comment so it might be due to snap evaluation code.

**Comment by mpetrunic** [comment]
Opened issues on ses-shim repo in case it's bug there:
https://github.com/Agoric/SES-shim/issues/234

**Comment by jacogr** [comment]
Thanks an absolute million for logging this - this is a good starting point to see what can be done. No promises, would need to dig.

**Comment by jacogr** [comment]
So comparing your repo against the metamask base - swap to their build process, non-snap.

**Comment by mpetrunic** [comment]
So snap build is using [snaps-cli](https://github.com/MetaMask/snaps-cli) which contains build step which rewrites some code to be compatible with ses. We are looking into doing some preprocessing where we remove comments from code as it appears that ses evaluation fails on some import statements in comments (actual code uses requires). Hopefully someone from agoric will respond and give better insight into this.

**Comment by mpetrunic** [comment]
@jacogr It seems like initial errors were because SES evaluates comments as well. I've opened up
PR on cli tool for building snaps which strip comments: https://github.com/MetaMask/snaps-cli/pull/50

Unfortunately, currently you cannot run wasm code inside ses. Is it possible to use this library without wasm initialization?

**Comment by jacogr** [comment]
I commented in substrate-technical -

It depends. So the wasm-crypto is basically a couple of things - faster versions of things like hashing and sr25519. For things like blake2, the slghtly-slower JS version will be used as a fallback when the wasm version is not avalable. sr25519 does not have any fallback, it is only wasm. (I'm using the term "wasm" here loosely, i.e. on platforms such as RN is uses asm.js instead of wasm, which is not available)

It always tries to instantiate the wasm portion, although it would be an easy addition to control that "auto-init-wasm" via a creation flag, aka don't use it, only use JS fallbacks. (Or even force to asm.js)

Specifically, we could control this via flag - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L220 which would allow all operations, except for anything with sr25519

**Comment by jacogr** [comment]
`1.8.0-beta.10` allows the `initWasm: false` flag which would skip init on the API level itself. Please give it a try as see if it gets down the road somewhat.

The util-crypto will still try imports from wasm-crypto in the utils to determine which path to take,  i.e. if wasm is available it will use that, otherwise fallback. If this creates an issue, there would need to be some magic in the util-crypto done.

**Comment by mpetrunic** [comment]
Yeah we are using `ed25519` to avoid that. Tnx a lot for this. 
Will keep logging here if we encounter any more issues but it seems will manage to make it work :slightly_smiling_face:

**Comment by jacogr** [comment]
Please do add here, happy to see how we can get it pointing in the right direction.

**Comment by mpetrunic** [comment]
@jacogr We noticed that everytime we create and commentApiPromise, it makes a bunch of calls to fetch metadata. We can only store json serializable data in plugin state(we cannot really persist some global variable), so we ended up initializing ApiPromise on every snap invocation. 

Question is, is it possible to extract metadata that can be serialized as json which we can pass somewhere when initializing api to avoid all those metadata calls and possibly make everything a bit faster?

**Comment by jacogr** [comment]
https://github.com/polkadot-js/api/blob/master/packages/api/src/types/index.ts#L40-L44

**Comment by mpetrunic** [comment]
We saw that, but from code it seems it would still fetch bunch of stuff like:
- https://github.com/polkadot-js/api/blob/5c7f9f1c8a4f1128dd188c64c22c5b958ab7c031/packages/api/src/base/Init.ts#L152
- rpc methods

Second question do we pass `ApiPromise.runtimeMetadata.toJSON()` there?

**Comment by jacogr** [comment]
You don't pass the `toJSON` - you need the raw hex.

And it still needs to fetch the additional stuff, otherwise it has no guarantees that it is working with the correct metadata. (And with wrong metadata the API is completely stuck stuck _everything_ uses the metadata. So it will, even when passing, still need to do some things)

**Comment by mpetrunic** [comment]
How long do you keep metadata cached then?

We need to serialize metadata to json to store it in plugin state(so we can reuse it on subsequent calls), if we need to pass Metadata object how do we restore Metadata from json so it's raw hex?

**Comment by jacogr** [comment]
Any Codec object has a `.toHex()` on it - https://polkadot.js.org/api/start/types.basics.html#everything-is-a-type

You can use it until the chain is upgraded and the specVersion has changed.

**Comment by MakMuftic** [comment]
@jacogr hi :wave: , we encountered another problem because of Secure EcmaScript doesn't allow `setInterval` function. After initializing API it disconnects after a few seconds (I suppose setInterval is used to keep the connection alive ?).
For now, we are manually reconnecting using `await provider.connect();` but definitely would like to do this more elegantly if possible. Do you think there is another way of solving this problem?

**Comment by jacogr** [comment]
Does it allow setTimeout?

I'll explain where this comes from - the actual connection does close without a health check when the subscriptions does not return any results in 30s. So the interval there is something that sends a `system_health` to keep the connection active.

So it depends on failure mode -

- if `setInterval` is undefined, we really should be checking before using
- Possibly use `setTimeout` (slightly more messy, but only a line or two)
- If no other option, skip completely (which is horrible, it will drop continuously in certain cases)

Either way, need some detection for these, or at worse a `noKeepalive` flag?

So I guess the question is which options is availble here, and is it undefined or just throws on explicit use?

**Comment by jacogr** [comment]
Closing. Feel free to re-open if there are more.
