### ISSUE TITLE
api.derive.accounts.indexes() returns empty object {}

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#2066]
Hi!

`api.derive.accounts.indexes()` is returning an empty object {}, tested in https://polkadot.js.org/apps/#/js / api v1.8.0-beta.1.

I was using this query to get all the active accounts in the system. Is this currently the best way to do that?

**Comment by jacogr** [comment]
It will only retrieve the accounts with active accountIndexes.

These were NOT migrated with the storage changes. 

So only accounts who physically called register (which nobody knows about), will appear in there.

**Comment by mariopino** [comment]
Thanks @jacogr,  I see, so it's possible to get current active accounts from the API somehow?

**Comment by jacogr** [comment]
You can query all (depending on chain/version) `api.query.system.account.keys()` and then retrieving the key metadata via the key `.args` (In the CHANGELOGs

I would really suggest keeping the general no-issue queries to other channels. Just since these are not issues, but rather very chain-specific.
