### ISSUE TITLE
How to detect why a transaction is failed to send?

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2088]
I think all I am getting from `.send` is an `Error`, containing a message like `submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (16100000000030000 vs 16100000000030000): The transaction has too low prior`

or `submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Stale`

So I can only use string matching to found out why it failed.

**Comment by jacogr** [comment]
In [JS Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) the info in a `message` property. There is no metadata. So the format will always be converted into what the env. supports.

(We did have `ExtError` in much earlier versions that extended Error and provided a code. However it was a complete hack with workarounds stacked since the Error object is actually not meant to be extended)
