### ISSUE TITLE
Retrieve list of all bonded and not bonded validators

### ISSUE THREAD

**Issue by asmodat** [polkadot-js/api#2170]
https://github.com/polkadot-js/api/blob/5acce98346adb419559d223f776210ac4bdf8bea/packages/api-derive/src/staking/validators.ts#L32

I am trying to understand how is the list of validators retrieved in the polkadot js **waiting** tab here -> https://polkadot.js.org/apps/#/staking/waiting. More precisely what RPC call is made to retrieve it.

This code is too abstracted for me to clearly see what is going on and I can't replicate the behavior that polkadot js is presenting with any of the storage commands as per their documentation here: https://polkadot.js.org/api/substrate/storage.html#erasstakers-eraindex-accountid-exposure

Could someone help me with understanding how to get list of all validators, not just those bonded (Session.Validators)?

**Comment by jacogr** [comment]
Via `api.query.staking.erasStakers.keys(currentEra)` as per the linked code - it retrieves all the keys (not doing the the full entries here, since we only want the list of AccountIds) for the DoubleMap by the era (using currentEra to get the next elected, not activeEra which is the current set)

For DoubleMap entries this cookbook entry is similar (following on from the maps retrieval section linked in the getting started) -

https://polkadot.js.org/api/cookbook/storage.html#how-do-i-use-entries-keys-on-double-maps

It shows how to get the list for the full storage map vs. a slice (based on the first DoubleMap key provided).

**Comment by asmodat** [comment]
Could you please help me understand how is the TCP request built?

I tried: 
```
POST(RPC_URL,
method: "state_getStorage",
params: XXHash.Hash128s("Staking").Combine(XXHash.Hash128s("ErasStakers")).Combine(XXHash.Hash64(ERA_HEX)).Combine(ERA_HEX)
```

But it does not work for me, ErasStakers only works for me if I supply EraIndex and AccountId at the same time

**Comment by jacogr** [comment]
1. You really don't want to hard-coding those keys and the hashers as above. You need to retrieve it via metadata and then based on what is set in the metadata for the hashers and prefixes, use that. These can change based on chain. (There are vastly different live implementations of these, as specified above you will have breakages if you don't create it based on what the metadata supplies)

2. There is no single answer for "what is the RPC" - it is all based on what the chain supports (there are currently 3 different combinations that may be valid, depending on the chain, the RPC node and at which update point they are). RPC availability is provided, like metadata, via the rpc_methods call and the API decorates based on these.

For both these issues you don't need to take care of anything manually, the API will retrieve the metadata when it connects, decorate the entries based on the specified hashers and abstract away the underlying calls on these, based on actual RPC-node & chain support.

**Comment by asmodat** [comment]
I already did all this abstraction myself, I only show the pseudocode to understand what kind of request that is. I based all on this tutorial: https://www.shawntabrizi.com/substrate/transparent-keys-in-substrate/ but I still do not understand how to make a call to state_getStorage to retrieve back that info about all validators that are both bonded and not bonded. 

From your response, I understand that I need to somehow call the state_getStorage with the method Staking.ErasStakers and supply as parameter only currentEra. But that does not work for me

**Comment by jacogr** [comment]
So, the above tutorial assumes that the metadata doesn't change - it does. Take it with a grain of salt for something that is applicable "today, at exactly this timestamp, for ceratn areas". The only way to get this information (and there are no short-term shortcuts that won't burn you in a month or two) is to -

- retrieve the on-chain metadata
- get the hashers and prefixes from there
- construct the keys based on that

Anything else that is not just an educational outing is bound to fail.

I am re-iterating that there is no single RPC for these, it depends on what the node supports. You can only get that information via rpc_methods. Once again, if you don't follow this approach by querying this endpoint to determine support, you are bound to have breakages due to deprecation.

For instance, currently on Kusama depending on which RPC node the API connects to (Parity of W3F), it does different things based on the actual node version. Connecting to Edgeware (live, relatively current) does different things altogether for these, including the hashers. You may have getKeys available but that is deprecated and replaced with getPagedKeys (which is not available everywhere as of yet), you may need to retrieve entries via subscriptions or use queryStorage for a range as a non-subscription or use the (very new) queryStorageAt (which itself will be deprecated and replaced with a paged version).

For all these, 

- always check your specific node
- read the actual Rust documentation to see what each endpoint in state_* does

Most importantly, always query the node for metadata and rpc_methods. The support, hashers, prefixes can and will change, the recent changes were <1 month ago on everything map-related. (It is specifically designed so things can change, since the node provides all the relevant info on support. these are flexible and transparent via metadata)

I am closing this issue now since this is way off topic for anything JS API related., and will just cause greater confusion on areas that API users just don't need to care about and really shouldn't (unless they want to footgun themselves, although al least the base as-per-metadata decorated key support is there).
