### ISSUE TITLE
invalid transaction

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#2197]
I have 0.018888888889 KSM and send 0.008888888889 KSM from [CgdyrkRxyHMPcfQTWYP4fYxUXNcJzebW2bue4perF8E6E48](https://polkascan.io/pre/kusama/account/CgdyrkRxyHMPcfQTWYP4fYxUXNcJzebW2bue4perF8E6E48) to [Dz1PvaydyqZqkPWQG3MKKdB6qME33eWkKoRXGGwJHZxnpdD](https://polkascan.io/pre/kusama/account/Dz1PvaydyqZqkPWQG3MKKdB6qME33eWkKoRXGGwJHZxnpdD) which is active, but get an `invalid transaction` error.

How to found out why it failed.

**Comment by jacogr** [comment]
That is from the transaction pool, i.e. Substrate related. There is no other info that the tx pool provides on those.

**Comment by xwartz** [comment]
very strange, this error occurs when transferring normal amount in some cases.

**Comment by jacogr** [comment]
In know the guys on the txpool are aware of a case where you do get the status, but the transaction still gets included. (It means it is invalid on the RPC node, which returns the status but then included elsewhere)

So here specifically, nothing that can be done - the API can only report the exact statusses are received from the pool. (Invalid does mean the transaction is dropped from the pool since it cannot be processed on that node anymore)

**Comment by jacogr** [comment]
The Invalid/included was fixed in the Substrate txpool as per Kusama/Polkadot 0.8.8
