### ISSUE TITLE
api.derive.staking.stakerRewardsMulti costs too much

### ISSUE THREAD

**Issue by AkakaKong** [polkadot-js/api#2218]
Sometimes it costs 120 seconds for the first time stash id query. It requires optimized.  However, it is fast for the second time using the same stash id query.

**Comment by jacogr** [comment]
It needs to -

- query all the validator exposures for the last 84 eras
- query all the validator preferences for the last 84 eras
- get all the rewards (no multiple, only 84 eras)
- check against the claimedEras arrays for validators to filter
- match all supplied stashes to validators/nominators

The reason why it is faster the second time around is because of memomization.

So yes, this is 100% expected - getting 225 keys for a single era and repeating over all of them is expensive.

**Comment by AkakaKong** [comment]
Is it possible to separate the reward API into two parts? one is eras points and rewards and so on, the one is filtering the stash id rewards, so that we can cache the former one data by era?

**Comment by jacogr** [comment]
The derives are already split into parts that are used. 

As it stands however hooking further splits into the calculation (which is not exported) will yield an approach that would need to be completely reworked again when Substrate 2 is out. The issue atm is that the networks has to support both old and new payout approaches in the calculations. 

Until the migrationEra has no effect of migrated networks, it means a significant effort to further complicate before it can be done cleanly. So it is innefective effort that would need to be replaced completely. 

So the short version of this is that there is already code for calculation splits which allows for injection of data (and has been tested as such), however this will not go in in the short term until only staker payouts are the norm.
