### ISSUE TITLE
Events decoding returns wrong result at block 2064961

### ISSUE THREAD

**Issue by nobrick** [polkadot-js/api#2251]
When decoding events at block [2064961](https://polkascan.io/pre/kusama/block/2064961),

```js
await api.query.system.events.at("0x4b8928d922b8940fe2f8a80d3491ab5992dd610d498dafe28445fa1ba7405f5b")
```

returns

```json
[
  {
    "phase": { "Initialization": null },
    "event": {
      "index": "0x080c",
      "data": [
        "0xd39a9ab3692021ef9859a35b49467685334e5ea98ecdc35e1c4b5497bd7675b4",
        "D3dswrhhow77nssxXgxGxYDNso2aVZ44GnHudWpQWCBx5j8",
        168576300000000
      ]
    },
    "topics": []
  },
  {
    "phase": { "Initialization": null },
    "event": { "index": "0x0002", "data": [] },
    "topics": []
  },
  {
    "phase": { "Initialization": null },
    "event": { "index": "0x0807", "data": [48, true] },
    "topics": []
  },
  {
    "phase": { "ApplyExtrinsic": 0 },
    "event": {
      "index": "0x0000",
      "data": [
        { "weight": 1103806605072, "class": "Operational", "paysFee": false }
      ]
    },
    "topics": []
  },
  {
    "phase": { "ApplyExtrinsic": 655360000 }, // outbound extrinsic index
    "event": {
      "index": "0x0000",
      "data": [{ "weight": 8589934848, "class": "Normal", "paysFee": false }]
    },
    "topics": [
      "0x420f000001000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000",
      "0x0000000000000000000000000000000000000000000000000000000000000000"
    ]
  },
  {
    "phase": { "ApplyExtrinsic": 0 },
    "event": { "index": "0x0000", "data": null },
    "topics": []
  }
]
```

The result seems wrong: an outbound extrinsic index exists. Any ideas?

**Comment by jacogr** [comment]
Really cannot comment on older blocks without knowing the types that should be used there. It could be due to any of the types used. There is some type mismatch, so the decoding goes wrong and by the time it gets the the problematic one, it starts from the wrong byte offsets.

**Comment by nobrick** [comment]
Thank you @jacogr. But I don't quite understand why it is an *older* block. It is a block with the latest runtime version 1058 on Kusama, so could we decode it according to `types-known/src/spec/kusama.ts`? Or is there anything I can do to parse the block?

**Comment by jacogr** [comment]
Ahh, didn't see it is a current block :) For current, will take a look. There was an issue with the types for `CompactAssignment`, this one is caused by exactly the same issue as the previous one you reported - 

https://github.com/polkadot-js/api/issues/2241

For that block it is fixed, but here it would seem like we _still_ have an issue. Will need to pull the data and see. Can confirm it is problematic on this one as well.

**Comment by jacogr** [comment]
Scratch the above.It is more tricky, way more tricky. So that block is the actual runtime upgrade block.So it is the last block before the upgrade was applied. The code gets applied there and then is used in any following blocks.

![image](https://user-images.githubusercontent.com/1424473/81264366-8c56e380-9041-11ea-8212-537a25f0c566.png)

So for any blocks after that one, the Weight type if `u64`, for that block and the blocks before that, the Weight type is `u32`. So trying to decode that block with the current types fails. So it reads an extra 4 bytes from the Weight and then the entry after that fails.

**Comment by nobrick** [comment]
Yes, It is tricky. I think I'll just skip this block for now :) Thanks.

**Comment by jacogr** [comment]
Just added this entry to the FAQ, https://polkadot.js.org/api/start/FAQ.html#when-querying-older-blocks-events-it-fails-on-parsing

T:;DR don't have a automagic solution for non-current-metadata stats and blocks as of yet. (Know exactly what _should_ be done, but have had a gap to properly implement it as of yet. It won't be added to `.at`, but would rather be `.historic` since it has a lot of overhead before even attempting to read the data)
