### ISSUE TITLE
Storage Function uses 'any' type

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#246]
* Storage Function here uses any type `storageFn = (arg?: any)`. Reference: https://github.com/polkadot-js/api/blob/master/packages/type-storage/src/utils/createFunction.ts#L48

* It was discussed that the "arg is determined based on the type of the storage function, which is determined by the metadata queries from the runtime.".  It could even be "something extending Base" or "something that could be fed to a Base type to create a Base instance".

It could be either `Base<any> | any | undefined`, where `any` is all of these.

If we establish that it's ok to just use the `any` time here, then propose to remove the comment `// TODO Find better type than any` at https://github.com/polkadot-js/api/blob/master/packages/type-storage/src/utils/createFunction.ts#L48

**Comment by jacogr** [comment]
Closing, this is the one area (well, along with the other creates), where `any` is actually the truth :) Weird, but yes, the value can be anything since it is either a primitive, or a `Base` or classes such as BN. In this case if it cannot convert a runtime error will be raised - there really is no way with the dynamic nature to be exact here.
