### ISSUE TITLE
[question] How to register transfer Types

### ISSUE THREAD

**Issue by noahsalvadordenjo** [polkadot-js/api#2470]
Dear github,

I'm sorry but i do not find a way to register the correct types for a basic transfer
i have to register the ```Vec<EventRecord>``` type because of the following error
```
Unable to decode storage system.events: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 192, in Normal, Operational, Mandatory
```
I create my api like so 
```
const api = await ApiPromise.create({ provider: provider, types: {
                Address: 'AccountId',
                Balance: 'u64',
                BlockHash: 'Hash',
                data: 'Vec<EventRecord>'
            }, signer: {} });
```
I gues data needs to change but with what should i replace it?

**Comment by jacogr** [comment]
`Vec<EventRecord>` does exist. The above error shows up since the internal types for the event being emitted is wrong. Is can be -

- `Weight` which is `u63` vs the normal `u64`
- The DispatchError type (lots of changes between Substrate versions)

So depends what version you are running and which version of Substrate that targets. (API always tracks Substrate master)

**Comment by noahsalvadordenjo** [comment]
Thanks but i still have the same error
```
"@polkadot/api": "^1.27.1"
```
substrate version
```
2.0.0-rc4
```

**Comment by jacogr** [comment]
Closing, assuming resolved.
