### ISSUE TITLE
Fail to decode types with ApiPromise that exists across a runtime upgrade

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#2613]
## High level overview:

Instances of Sidecar alive while polkadot went from v18 -> v23 could not decode blocks after the runtime upgrade that had `RewardDestination` enum in them. I recreated this issue by simulating a runtime upgrade from v22 -> v23 in a local test-net. Further, I saw similar phenomena in the apps UI where the submit extrinsic for setPaye did not update with the new `RewardDestination`

Sidecar version:  commit [57324a632b94d770d2f8ca5e7100e47d4ea11281](https://github.com/paritytech/substrate-api-sidecar/commit/57324a632b94d770d2f8ca5e7100e47d4ea11281) (branch `zeke-log-2` which is the current open logging PR and has the current polkadot-js beta installed)

## How I re-created the error:
- got a docker compose up and running of a 2 validator, 3 node local test net. all nodes running polkadot v22, but modified to have the sudo pallet.
- connected sidecar to the Annie validator node
- submitted a setPayee transaction for Bob and checked that correctly it changed in the `accounts/{accountId}/staking-info` route
- intermittently checked the `/runtime/spec` route to ensure spec version was changing as expected 
- made a call to set code with the polkadot wasm file from the [v0.8.23 release](https://github.com/paritytech/polkadot/releases/tag/v0.8.23)
- then I tried to setPayee for Bob but saw the options did not update (no `Account(accountId)`). So I refreshed the apps page and then saw the `Account(accountId)`  show up. I then was able to successfully submit the transaction. I think this is important because it re-established the WS connection and everything corrected - which is the same behavior Sidecar always exhibits with these types of errors.
- I checked the block using Sidecar ( see `/blocks/98` in logs, I call it twice and then call `blocks/97`, which works) and it failed to decode the `RewardDestination` enum.

I am attaching logs from Sidecar. The logs include http request/response summaries, stack dumps, and RPC logging from polkadot-js/api using `NODE_ENV=test`.

Logs:
[set-code-sas.log](https://github.com/polkadot-js/api/files/5228878/set-code-sas.log)

My .env file for Sidecar:
```
SAS_SUBSTRATE_WS_URL=ws://127.0.0.1:9946

SAS_LOG_FILE_USE=true
SAS_LOG_CONSOLE_LEVEL=debug
SAS_LOG_FILE_PATH=./logs/set-code-sas.log
SAS_LOG_FILE_STRIP_ANSI=true
SAS_LOG_FILE_LEVEL=debug
SAS_LOG_FILE_COUNT=100

**Comment by emostov** [comment]
cc @dvdplm, @joepetrowski

**Comment by jacogr** [comment]
Don't confuse the apps behaviour - it does not deal with runtime upgrades in any kind of transparent fashion, it always requires a manual refresh. (Just because of the way the registry is setup there as a global, externally from the actual API usage - at some point will get there to doing it properly)

**Comment by dvdplm** [comment]
> it does not deal with runtime upgrades in any kind of transparent fashion

@jacogr is there a ticket open we can watch?

**Comment by jacogr** [comment]
The apps UI has no ticket like that - it is part of my ongoing long-term registry overhaul there which I clean up bit by bit, component by component. 

The issue is that initially all apps types were global. Then we introduced the registry concept to make it self contained. So with that scenario the apps UI took the same approach with a global registry to "get it to work without rewriting the whole app".

So it really does not handle upgrades. It is better now that it doesn't crash anymore (so the "refresh this now" popup is not there and even allows you now to send "the same txs without new types".)
