### ISSUE TITLE
Inconsistent response from query.system.account after RefCount change

### ISSUE THREAD

**Issue by bariscicek** [polkadot-js/api#2722]
After RefCount change from u8 to u32 I get inconsistent response on calls to query.system.account to local node at version 0.8.25. 

When first connection to wss call returns expected value, but after 1-2mins returns bad value which looks like decoded with u8. 

That happens for both Polkadot and Kusama networks and happens all the time. After restarting the node app, on fresh start expected balance is returns. Polkadot-js version is 2.2.1.

**Comment by jacogr** [comment]
Simple await or subscription? (asking because they do use different paths).

**Comment by bariscicek** [comment]
Subscription, starting api with ApiPromise({ provider }), nothing else.

**Comment by bariscicek** [comment]
Something I realized that when I get bad value, BN bytes are shifted 3 bytes.
ie. "0x00000000000000000015958323d2da94" => "0x00000000000015958323d2da94000000"

**Comment by jacogr** [comment]
Since you are running a local node, can you add the `--execution wasm` flag to the binary and see if the issue persists? (There should be no difference in how the node serves RPC requests on wasm via native execution, i.e. it should always return the raw trie data, but since you mentioned "bytes shifted" just wanted to rule out that possibility)

**Comment by bariscicek** [comment]
I just realized that another proc is actually registering type, and that is happening after setting metadata.
`api.registry.register(getSpecTypes(api.registry, chain, version.specName, blockSpecVersion))`

Not sure why it is breaking, since version of @polkadot/types is 2.2.1 as well.

**Comment by jacogr** [comment]
Ok, the own-registration should be removed. Since before 2.0 the API has transparent support for historic queries. So in the case of `.at` queries it actually manages a separate registry for old types. (So it will transparently manage a registry per version). so effectively that registration clobbers the registry that is meant for the 25 runtime.

**Comment by bariscicek** [comment]
But would removing this registry make historic queries broken?

**Comment by jacogr** [comment]
No. There is transparent support built-into the API.

**Comment by bariscicek** [comment]
Thanks for explanation.
