### ISSUE TITLE
popping out "Cannot construct unknown type" when use "at" operator to retrieve the state at a specific block.

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#2770]
When I query current state by using the form of "api.query.<module>.<function>", it works perfectly fine.
![A93AEC14-5922-4FA8-BABF-8B20C44E0E4E](https://user-images.githubusercontent.com/45537372/96973740-e6ddf080-154a-11eb-9ad2-56d2c0e3175f.png)

But when I use the "at" operator to retrieve the state at a specific block, it pops out  "Cannot construct unknown type" error. I am pretty sure it worked weeks ago. 
![7D1325D2-034E-4BB2-9DCA-6190367291C3](https://user-images.githubusercontent.com/45537372/96974076-4c31e180-154b-11eb-973f-7eaa4e179403.png)

Could you please have a look at what's wrong with it?

**Comment by jacogr** [comment]
I'm assuming you are injecting types via `types` on the API as opposed to the new (history-aware) `typesBundle`? There is an issue with the former at this point, a fix should make it in today (it is currently being tested).

**Comment by herryho** [comment]
Yes! I'm so happy to hear the good news! The problem have been torturing me for days. 😄 Thanks~

**Comment by jacogr** [comment]
The types will be deprecated (alongside a v3 of the API), specifically because of issue like this because it is just not descriptive enough and especially only older blocks the types may have changed. So with the `typesBundle` it allows you to cater for multiple chains and on each of those actually multiple versions with distinct types.

So an example will be -

```js
const api = await ApiPromise.create({
  typesBundle: {
    // listing based on the spec name
    spec: {
      // example for node-template, could be edgeware, polkadot, kusama or whatever the chain
      // specName is set to
      'node-template': {
        types: [
          {
            // the min and max specVersion to apply this to - to apply to all can just make
            // max undefined, so it always applies
            minmax: [0, 40],
            types: { SomeType: 'u32' }
          },
          {
            minmax: [41, undefined],
            types: { someType: 'u64' }
          }
        ]
      }
    }
  }
});
```

It is slightly more noisy, but especially when using historic queries where the types will morph over time, it allows you to cater for previous versions and the correct types based on the version at that point is applied.

**Comment by herryho** [comment]
Ok, I'll have a try. Thanks!
