### ISSUE TITLE
Type definition for tuple struct in custom RPC query

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/api#2835]
Hi, I have following scenario:
Custom RPC query with parameter type defined as `pub struct Wrapper(pub [u8; 32])`. For typegen json it is defined (same as regular structs) as `Wrapper: {param_1: '[u8; 32]'}`.

There are two problems with this: 1) By default in custom rpc's tuple struct is serialized as array, 2) [u8; 32] is serialized as array
In polkadot.js those types are deserialized normally, but serialization doesn't fit expected interface - rpc expects the type to be in array form, but from polkadot.js it's sent as map with hex string `{param_1: "0x0...0"}`.
In this particular case I have workaround - not to use tuple structs and have custom serde overrides for Wrapper to serialize/deserialize inner type as hex string.

The questions are: Is it possible to define tuple struct in json for typegen? How can I add custom serialization/toHuman/etc overrides on client side?

**Comment by jacogr** [comment]
Why are you using `Wrapper: {param_1: '[u8; 32]'}` as opposed to a simple `[u8; 32]`? Since it has no extra information from the struct, the extra "Wrapper" is not needed. that may solve the issue since H256-like should be supported.

The typegen is limited, i.e. it only caters for what is known instead of trying to do anything - there are a large number of corner cases which it doesn't even attempt since it is not used in the Substrate base. So the best approach is to extend typegen, PRs welcome.

**Comment by modbrin** [comment]
@jacogr Thanks for suggestions.

Leaving out wrapping on client is one option, it suits this example, initially the problem arised because there were already some tuple structs with more member types and I found it harder to fix on client side because couldn't override it in typegen without intervening core library.

As I see it currently - a part of bigger question - performing custom queries via custom rpc's which is a low-level approach and uses serde-json directly rather than encoding types through scale codec as in extrinsics/state-queries. This makes custom queries separated, problems such as differing serialization occur and runtime upgrade doesn't support update of custom rpc's. Therefore I believe an extension of overall custom queries mechanism of substrate api is an area of contribution, which I probably will experiment with eventually.
