### ISSUE TITLE
Support single signatures

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#2844]
Currently, polkadotjs only supports having multisignature (sr25519, ed25519, ecdsa). The limitation comes from the codec which prefixes the signature with the enum number.

This forces moonbeam to use a multisignature protocol too faking the 2 first implementations.

@jacogr do you think we can change the sdk to support a single ecdsa signature extrinsic? Also checking that this isn't already implemented or if it's impossible for some reason.

Thanks in advance

**Comment by jacogr** [comment]
Support for Extrinsic v3 was dropped completely. The upgrade from v3 -> v4 was done because of the move from AnySignature to MultiSignature, i.e. MultiSignature was the reason for the change. So actually doing anything but MultiSignature is wrong from a historic perspective.

However, there is an issue logged to break that protocol already, in the cases where chain want to override the Signature type, see https://github.com/polkadot-js/api/issues/2536 (aka this is a duplicate)

**Comment by joelamouche** [comment]
thank you for your answer. Let me get back to you
