### ISSUE TITLE
how to decode result from state_getStorage

### ISSUE THREAD

**Issue by heipacker** [polkadot-js/api#2886]
const result1 = await provider.send('state_getStorage', [storageKey.toHex()])
        console.log(util.hexToBn(result1, {isLe: true}).toString());
        console.log('rpc state_getStorage', result1)

response

rpc state_getStorage 0x0c00000003000000de4121e21d000000000000000000000000000000000000000000000000000000aff18b48170000000000000000000000aff18b48170000000000000000000000

how can i decode the result from rpc request, is there some examples?

**Comment by jacogr** [comment]
You decode it via the types as provided by the metadata, i.e. the types for the specific module and the specific call (primitive, option, maps, etc.). The API does it for you when calling `api.query.<module>.<method>`.

There are no examples in the API for those (only the code in `packages/rpc-core` in the API repo itself) since the decorated interfaces already handles the decoding transparently.

**Comment by heipacker** [comment]
Because I use the official example to have all kinds of strange problems. In addition, the performance that I can handle with this RPC method will be higher, because our application scenario needs high concurrency

**Comment by jacogr** [comment]
`registry.createType(<ouput type>, <data>)` would decode. (Where the type is as defined in the metadata)

**Comment by jacogr** [comment]
Closing, answered.
