### ISSUE TITLE
How to check if registry has metadata set?

### ISSUE THREAD

**Issue by ii-ii-ii** [polkadot-js/api#2896]
https://github.com/polkadot-js/api/blob/master/packages/types/src/create/registry.ts#L351 

`this.#metadataCalls`, `this.#metadataErrors`, `this.#metadataEvents` are private variables. There is no way to access them.

So how do I know if registry has injected metadata?

**Comment by jacogr** [comment]
It doesn't have a `hasMetadata` getter.  

The reason for this is that the API ensures the registry is decorated upon connect. (And for historic queries would inject older metadata as required). So it generally is not something that needs to be managed externally, like the API swaps registries as applicable (for older state), it takes care of the management of the current metadata, also on upgrades.

**Comment by ii-ii-ii** [comment]
But there's nothing wrong with adding it, right? Some people, like me, use wsprovider + registry + metadata to implement the required functionality. Because I think api is too heavy and has a lot of things I don't need. At this point it would be nice if I could access the metadata through registry.

**Comment by jacogr** [comment]
Sure, you can use components in what fashion you believe makes sense. (It is not something actively supported, i.e. while generally the "normal" API interfaces are really managed with a don't-break-userspace mentality, Metadata and registry itself is still undergoing some major upheavals, so YYMV)

As for the specific item, remember that everything added becomes in need of support, so really need to understand the "why and how" here, since it is not needed anywhere else. So while the registry itself will probably never have a `registry.metadata`, it _may_ make sense to have some easy-to-calculate state exposed if these is a solid usecase. (Just bear in mind what I mentioned above, the registry <-> metadata is not 100% clean atm, so it will probably change)

**Comment by jacogr** [comment]
BTW, it is also important from an API perspective to understand "what is not needed" and "heavy", since it does drive improvements. So feedback is always welcome to improve.
