### ISSUE TITLE
Events support in @polkadot/typegen

### ISSUE THREAD

**Issue by tomusdrw** [polkadot-js/api#2965]
AFAICT there is no support for events typing generation in `@polkadot/typegen`:
https://polkadot.js.org/docs/api/examples/promise/typegen/
while it seems quite useful.

**Comment by jacogr** [comment]
Overall there is no generation for events at all - the Event type is only a generic codec, so even for Polkadot/Kusama any use of the events is to cast them. (It only gets generated from metadata)

**Comment by jacogr** [comment]
So, how would you expect this to work? Interested since this has been in the back of my mind for some time. So basically, code-wise,

```js
// returns Vec<EventRecord>
const records = await api.query.system.events();

// here Even is a generic Event, data is a Tuple - types can only be applies when the
// compiler actually knows exactly what is in the storage (unlike tx/rpc/storage where
// we know up-front based on the actual call made)
records.forEach(({ phase, event: { data } }) => {
 ...
});
```

So TS just cannot apply typing since it just doesn't know what is inside the `Vec<EventRecord>`. This is horrible, since for instance in balance,transfer you would need to manually recast `data` to `ITuple<[AccountId, Balance]>` when using. So the generation help that coupld be applied would be something like -

```js
// generated based on metadata
type EventDataBalancesTransfer = ITuple<[AccountId, Balance]>;

// use still needs to cast, but at least there is an alias...
const [accountId, balance] = event.data as EventDataBalancesTransfer;

// where this is what is done currently
const [accountId, balance] = event.data as  ITuple<[AccountId, Balance]>;
```

**Comment by savudani8** [comment]
I was able to generate event types for the parachain metadata using the code in PR https://github.com/polkadot-js/api/pull/2981.

I didn't need to specify custom event types, as they were already part of the `EventMetadataV12` property of the Metadata https://github.com/polkadot-js/api/blob/333313fd6abf2820f00a555b46edb108e63a3848/packages/types/src/interfaces/metadata/types.ts#L233

The result can be observed here:
![Screenshot from 2020-12-23 16-02-11](https://user-images.githubusercontent.com/23065004/103015417-4e5af100-4538-11eb-9f64-8fa8318eee5c.png)

**Comment by jacogr** [comment]
Yes, the generation is not the issue, that is really straight forward. 

My questions are around the use. Since it is not able to be auto-applied, so it is still being casted. I am guessing that applying and casting as „generated“ removes some errors, eg. When the Tuple changes for 3 to 2.

**Comment by savudani8** [comment]
So what you're saying is that even with auto-generated types, the events from a tx subscription need to be manually cast to a type that is known beforehand?

**Comment by jacogr** [comment]
Indeed.

From `system.events` we get a `Vec<EventRecord>` back, until it is decoded (which happens in the runtime), you cannot know the types for it. So it can never be done statically.

**Comment by savudani8** [comment]
Such a feature would still add value in my opinion. To check if a transaction is successful, at the moment I'm comparing strings, which is not ideal. (For instance `if (event.section == "issue" && event.method == "RequestIssue")`) 

The build of the PR I opened failed because I made my changes on top of v2.8.1 and then I rebased, but it would be great to merge this in January

**Comment by jacogr** [comment]
You will get away from doing that method/section string compare. Only after that you can cast. 

Just trigger the PR again
