### ISSUE TITLE
author_removeExtrinsic wrong key name

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#3023]
When using the author_removeExtrinsic in the UI:
```
{"id":18,"jsonrpc":"2.0","method":"author_removeExtrinsic","params":[[{"Hash":"0x0000000000000000000000000000000000000000000000000000000000000000"}]]}
```
it returns:
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: unknown variant `Hash`, expected `hash` or `extrinsic`."},"id":18}
```

Same happens with `Extrinsic` vs `extrinsic`

**Comment by jacogr** [comment]
It is actually correct for the enum. However there used to be discrepancies on the serialization layer that had a mix of `PascalCase` and `camelCase`, either/or in different cases. 

That has been adjusted on the Substrate side but never made it through to the API. Decoding-wise the API handles any version, but encoding-wise seems the adjustment was not made, as needed. (Never an issue since i only affects RPCs and enums are few and far in-between)
