### ISSUE TITLE
Issues with data retrieval results on new asset pallet in substrate master

### ISSUE THREAD

**Issue by JesseAbram** [polkadot-js/api#3031]
I am having issues with data retrieval on the latest substrate master asset panel. All transactions go through fine and the logic is consistent with what it should be but retrieving and displaying data gives weird results. 

Context: 
- Interacting with assets panel on latest substrate [master](https://github.com/paritytech/substrate/tree/master/frame/assets)
- Using both the polkadot.js frontend and a cli [tool](https://github.com/JesseAbram/asset_cli_tool)
- Tested with multiple versions of polkadot.js including the 3.3.0-0

Steps to reproduce 
 - create asset with any value of min balance and max zombies then query asset info, they are set to 0 and supply is not 0 (internal logic reflects what is expected)
 - transfer funds to a zombied account (an account without and native token balance), query, the number seems like an overflow but the logic behaves as if it was 100 (fixes itself after depositing native token then making any transfer action)
 - Freeze boolean on account always remains false even when internal logic is true

Extra info 
- I am sharing the types I am using, I believe them to be correct but would not be shocked if I did something wrong [here](https://github.com/JesseAbram/asset_cli_tool/blob/master/blockchainServices/setup.js#L7), in fact due to the nature of the issue it is where I am spending my most time looking

**Comment by jacogr** [comment]
The API already provides types for asset - since it is a known substrate module. You do however need to define the `TAssetBalance` type if it doesn't map to a balance, i.e. https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/assets/definitions.ts#L29 (Actually looking at that i generally maps to the substrate default, which is u64, so the API is not right there - will update it alongside the PR for missing that that will go up soon)

That may not have a result at all, but at least it aligns actual use.

**Comment by jacogr** [comment]
Ok, so went through your steps on the apps UI (no types added, just the defaults after adjusting the `u64` in the API - which has been bumped). Cannot see what you see.

- supply is correct, 0 -> updates after minted
- balance on recipient (no native) is correct
- can freeze/thaw and the state updates

Looking at your types, you have an issue with the deposit balance type, it is BalanceOf, not asset balance.

**Comment by JesseAbram** [comment]
My Hero! Thank you so much! It all is working now!
