### ISSUE TITLE
Include metadataConsts in the return of api.getBlockRegistry()

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#3080]
It is useful in our case, but currently is set to null.

**Comment by jacogr** [comment]
Your linked workaround for now is the “recommended” since the API decorates itself. It actually was added originally (but not implemented) for the consts.at(hash) usecase. However it may be dropped when it gets there so rather not rely on it as of yet. 

Will get some clarity once we get to the at constants - it is weird if that one is there are decorated and the others are not. So it almost needs to be an all or nothing - or at least requires some thinking.

**Comment by jacogr** [comment]
I think what you are missing I think his case is an exposed API point to re-decorate - probably with flags. We can certainly hoist the decoration and expose it as a function to make that happen. (It is there, needs to be public and flagged)

**Comment by ianhe8x** [comment]
`consts` are not a problem now (or rather not the only problem), since I found I also need errors and events to be swapped.

**Comment by jacogr** [comment]
Yes, that is why I referred to the "all-or-nothing" above. the `metadataConsts` seemed like a good idea at the time as a "placheolder" so I don't lose track of where. However as evident don't believe it has legs even if filled.
