### ISSUE TITLE
about ExtrinsicFailed or ExtrinsicSuccess

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#3081]
When I send the extrinsic to the network, I can know whether the extrinsic is successful or not with the send callback function. However, if we want to read the extrinsic already contained in the block, we cannot know whether the extrinsic is successful. Is there any way to know whether the extrinsic is successful or not reading the extrinsic already in the block?

**Comment by jacogr** [comment]
Events are not in the blocks, there are in the state. So you need to map. See https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by puffanddmx** [comment]
When the contract is initiated, the address of the contract appears. If we use the method you said above link, can you get the contract address if we do block read? -> if so , how can we get it ?

**Comment by jacogr** [comment]
Phase - the apply is the index of the extrinsic in the block

Events - the index is the scale-encoded (as per the metadata) event, module and then event. You can use `api.events.<module>.<event>.is(event)` to check for the type. (Or event.section` and `event.method` for the name - you should never match on index directly, since it does change between upgrades)

Max weight - depends on chain, either `api.consts.system.blockWeights` (chains up to date with Substrate master) or `api.consts.system. maximumBlockWeight` (2.0 chains)

**Comment by puffanddmx** [comment]
when i mint erc721, i got this error.
how can i get the block limits for using api call to set up the proper gas_limit ?

1 . gas_limit: 2000000000000n  : got this error
submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction would exhaust the block limits

**Comment by jacogr** [comment]
`api.consts.system.blockWeights` - as per my comment above.

**Comment by jacogr** [comment]
Closing. Original questions answered.
