### ISSUE TITLE
`Capabilities detected` Warning

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3105]
When running the monnbeam tests with the latest version of the api I get this log:
`2021-01-25 11:31:42        API/INIT: Capabilities detected: {"AccountInfo":"AccountInfoWithRefCount"}`

What are capabilities and what does this message mean?

Thanks in advance

**Comment by jacogr** [comment]
It is a log and will probably be removed in a next version, but since it is new it is value to have as a tool at the start. 

Basically for those the API actually detects which version is on the chain for certain types. So instance recently the `AccountInfo` structure has actually changed in Substrate, the above allows the API to detect which version is actually available without having it specified. (The same check also applies for `ValidatorPreferences` - there will be more added).

It does not remove the need for definitions, especially looking at historic info the AI never looks back, rather it is only a "at-this-point-in-time" check. Done on initial connection and on upgrades.

**Comment by joelamouche** [comment]
So does it mean I should add `{"AccountInfo":"AccountInfoWithRefCount"}` to the moonbeam types?

**Comment by jacogr** [comment]
You could for safety. It is the current API default (`AccountInfoWithProviders` being the new one), but as mentioned in the previous week's API release notes, it may change in the medium term as it rolls out. (There pressure is not there anymore to change the default since we do now detect it for latest, but at least for historic versions in the bundle it would be prudent)
