### ISSUE TITLE
FATAL: Unable to initialize the API: createType(StorageKey):: Bytes length 328100489 exceeds 10485760

### ISSUE THREAD

**Issue by xhuanlee** [polkadot-js/api#3118]
"@polkadot/api": "^3.6.4"

**my code:**
```
const provider = new WsProvider('ws://192.168.0.25:9944');
const api = await ApiPromise.create({ provider });
```

**error messages:**
```
2021-01-28 17:16:46        REGISTRY: Error: Bytes length 328100489 exceeds 10485760
2021-01-28 17:16:46        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageKey):: Bytes length 328100489 exceeds 10485760
2021-01-28 17:16:46        API/INIT: Error: createType(StorageKey):: Bytes length 328100489 exceeds 10485760
Uncaught (in promise) Error: FATAL: Unable to initialize the API: createType(StorageKey):: Bytes length 328100489 exceeds 10485760
```

**Comment by jacogr** [comment]
Which network are you running locally? It seems like a mismatch in types - the API tries to decode via something that doesn’t match what is actually on the node.

**Comment by xhuanlee** [comment]
> 
> 
> Which network are you running locally? It seems like a mismatch in types - the API tries to decode via something that doesn’t match what is actually on the node.  
I'm running `substrate-node-template@2.0.1`, is there anyway to fix it ?

**Comment by jacogr** [comment]
Sorry, only seeing this now. The node-template 2.0.1 I believe is using `MultiAddress`, the API has it as a default type since the 3.7.1 release. (Before that it was on the previous default for Substrate)

See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures for the types of addresses available.
