### ISSUE TITLE
Subscription multi

### ISSUE THREAD

**Issue by shangpit** [polkadot-js/api#3136]
```js
const unsub = await api.queryMulti([
  queryChainState1
  queryChainState2
], callback);
```
Is there a option to setup only trigger callback when both query1 and query2 has some change in chain state?

**Comment by jacogr** [comment]
No. Underlying all it does it to subscribe to multiple keys via the subscription RPCs. The node returns a result when any on of the the keys has a value change at the end of a block. Any additional filtering is to be done in your own code.

**Comment by shangpit** [comment]
Thanks very much 👍

**Comment by shangpit** [comment]
But is there a way to filtering which key has value change?

**Comment by shangpit** [comment]
Example: Subscribe the value change of an address, which block number that has change...

**Comment by jacogr** [comment]
The actually blockHash where it is retrieved is not passed through. It is an extension to the subscription interface that is a actually WIP atm. 

Not 100% sure if it will end up as an additional API interface or if it can cleanly extend the current. The latter is fist-prize, but slightly tricky consistently without creating breakages. So the delay is really not in the functionality part but rather keeping it non-breaking

**Comment by shangpit** [comment]
Can we discussion about performance of subscibe? Is there any problem when we subscribe 10,000 keys?

**Comment by jacogr** [comment]
The API does chunk it into smaller parts for >384 and the re-combine the responses it when using `queryMulti`. Very large numbers do have an impact on the node side since it checks each key at the end of each block. So the slightly smaller batches do allow it to move through a single subscription faster and appear more responsive. (JS has the obvious issue that it is single-threaded, so slightly smaller chunks allows it t do processing in-between results instead of seemingly "getting stuck".)

For subscribe, not sure if there is a hard limit if the API didn't chunk like it does above - there was one introduced in substrate for the `entries` (where it uses queryStorageAt, these iterate the trie, which is really expensive).

**Comment by shangpit** [comment]
```js
const unsubscribe = await api.rpc.chain.subscribeNewHeads(async (newHead) => {
      const { hash, number } = newHead;
      console.log(`Block number ${number.toNumber()}`);
      const [allEvent, signedBlock, timestamp] = await Promise.all([
        api.query.system.events.at(hash),
        api.rpc.chain.getBlock(hash),
        api.query.timestamp.now.at(hash),
      ]);
      const allEventFilterd = allEvent
        .filter(({ event }) => api.events.balances.Transfer.is(event))
        .filter(({ event: { data: [_, to, __] } }) => {
          const check = addresses.includes(to.toString());
          return check !== undefined;
        })
        .map((event) => {
          const extrinsic = signedBlock.block.extrinsics.find((_, index) => event.phase.isApplyExtrinsic && event.phase.asApplyExtrinsic.eq(index));
          return {
            ...event,
            extrinsicHash: extrinsic.hash,
          };
        });
      allEventFilterd.forEach(async ({ extrinsicHash, event: { data: [from, to, amount] } }) => saveToDatabase)
```
When i implement subscibe Transfer event i got three records in database, may be there is three phases of events with same transfer???
![image](https://user-images.githubusercontent.com/49492179/106865025-306ad980-66fd-11eb-95fd-72a3f0bf8104.png)

**Comment by jacogr** [comment]
There are forks on the network, around 1 in every 4 blocks on Babe. This means it can be included in a block (which new heads will report), then retracted as the block gets forked off (a secondary slot, which may actually have multiples as well), then included in an another block as a primary. So they can and will appear multiple times.

When you listen to finalized heads, there are no forks since it is the blocks as included.

**Comment by shangpit** [comment]
```js
api.rpc.chain.subscribeFInalizeHeads(async (newHead) => {
```
you mean that?
