### ISSUE TITLE
Chain-specific SignedExtension guide

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/api#3221]
I've been trying to find out how to pass additional data for custom SignedExtension. Basically I'm trying to make version of ChargeTransactionPayment that will accept tip and extra info, e.g. AssetId for fee.

There was a guide for `ExtrinsicV3` which states the need to redefine `Extrinsic` and `ExtrinsicPayload` types. Looking at `ExtrinsicV4` however it does seem that custom SignedExtension could be injected otherwise. Only info that is parsed from metadata is SignedExtension Ids, so actual definitions need to be present on client.

Questions are - how to define/inject custom SignedExtension format and how to pass those values when signing a transaction? E.g. `tip` is passed via `SignerOptions`, do I need redefine it as well to pass actual values when doing `.signAndSend()`?

**Comment by jacogr** [comment]
Have no guide. However, the extensions can now be injected as part of the API options. So without a guide, going to link you to the source. Here is an example of defining an extension  https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/signedExtensions/substrate.ts#L18-L23

So basically in the API you would do -

```js
const api = await ApiPromise.create({
  signedExtensions: {
    ChargeTransactionPayment: {
      extrinsic: {
        tip: 'Compact<Balance>'
      },
      payload: {}
    }
  }
});
```

The `extrinsic` part is the info that goes into the extrinsic, the `payload` the info that gos into the payload itself.

I'm not sure anybody uses these as of yet (although I have had queries), so there may be gaps. However anything defined here would be applied if it appears in the metadata (in the order defined there).

**Comment by modbrin** [comment]
Great, after updating deps to latest I can see this option. However how to pass the value? I tried `.signAndSend(account, { charge_fee_info })` which succeeds, but value is not received in substrate. Injected extension does not appear in `SignerOptions`. Is there another approach to do this?

**Comment by jacogr** [comment]
The issue is that the payload only adds the fields to the payload it knows about. Effectively it would lose any extra stuff in the serialization here - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/SignerPayload.ts#L54

So it can be adjusted -

1. The payload base needs to take the types into account, so instead of https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/SignerPayload.ts#L31-L43 it needs to follow the same approach as done in the Extrinsic where the fields are actually generated on the fly

2. The serialization above needs to (in some way) be able to add the additional fields - so guessing it is once again checking for fields it doesn't have and then apply toHex on it

**Comment by modbrin** [comment]
I have reviewed changes but still have question on how to pass actual values during transaction submission. How do I construct and submit the transaction with extended payload?

**Comment by jacogr** [comment]
Extra information should be passed through from the actual `signAsync` or `signAndSend` - https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L186
