### ISSUE TITLE
Some packages should be devDependencies

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#323]
https://github.com/polkadot-js/api/blob/0ee712531364ff4f0c3a94aaa581acfa926888d2/package.json#L29-L35

**Comment by jacogr** [comment]
cc @ltfschoen

**Comment by ltfschoen** [comment]
@amaurymartiny The following is my understanding of how those dependencies are used:
* babel-plugin-module-resolver - used to transpile TS to JS when we run `yarn run build`.  Since we're not storing any JS files on Github we're also using the CI to build for production with this script, which also runs `yarn run build` https://github.com/polkadot-js/dev/blob/master/packages/dev/scripts/polkadot-dev-build-travis.sh#L79. So I think it needs to remain in "dependencies"

* gitbook-plugin-include-codeblock - used to include the TS/JS code snippets. I think same situation as above, but part of building the Gitbook https://github.com/polkadot-js/dev/blob/master/packages/dev/scripts/polkadot-dev-build-travis.sh#L202

*  gitbook-plugin-insert-logo-link - **Yes, I think this could be a "devDependency"**

* gitbook-plugin-mermaid-gb3 - I think same situation as gitbook-plugin-include-codeblock (it generates various diagrams)

* gitbook-plugin-sunlight-highlighter - I think same situation as gitbook-plugin-include-codeblock, it just colours the code or background in the code snippets

**Comment by jacogr** [comment]
- `babel-plugin-module-resolver` used by build only, so it is a dev dep.
- `gitbook-plugin-include-codeblock` - dev dep
- ...

When cloning the repo and running `yarn` to install the dev deps are installed. So with all those as dev deps, it works locally and on CI. Deps are only used by things that are needed when using the npm packges as a dep in other projects.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/333
