### ISSUE TITLE
`abi.project.source.hash` is wrong

### ISSUE THREAD

**Issue by ii-ii-ii** [polkadot-js/api#3247]
`inkAbi.project.source.hash.toString()` is getting the wrong code hash. It should actually equal `inkAbi.json.source.hash`.

Add code to the test case(https://github.com/polkadot-js/api/blob/master/packages/api-contract/src/Abi.spec.ts#L21),  Can be tested and verified.

```
console.log(
          inkAbi.project.contract.name.toString(),
          inkAbi.project.source.hash.toString(),
          (inkAbi.json as any).source.hash
);
```

**Comment by jacogr** [comment]
The issue is that the `hash` is a reserved word for the Codec since it is exposed on each type - so it doesn't contain the hash field in the structure, but rather the hash of the structure. (It is the hash for the complete structure). So basically to extract that one, there needs to be an alias added where it extracts to a different field.

(If you do need the hash of the wasm, you can get it via `source.wasm.hash.toHex()`)
