### ISSUE TITLE
Can I use this JS to operate "Parachain Slots Auction"?

### ISSUE THREAD

**Issue by Yangxin-GG** [polkadot-js/api#3249]
Hi，It is said that KSM's Parachain Slots Auction is about to start. Can I use this js to pledge the account balance for auction?
If so, what should I do? Is there a document for reference?

**Comment by jacogr** [comment]
Yes, the API will decorate all the methods and queries as available on the chain. So once the chain has the module available, the metadata provides the information and the API decorates with that information.

For the specific methods that i available on that module, it is best to refer to the actual source-of-truth, the Rust module for auctions.

**Comment by Yangxin-GG** [comment]
Okay, how should I use this JS to pledge assets for auction? Is there a corresponding API?

**Comment by jacogr** [comment]
The APIs matches 1-to-1 what is in the Rust code. See https://polkadot.js.org/docs/api/start/basics

- chain has the module
- JS API requests metadata from the chain containing all interfaces
- JS API decorates all the methods as exposed

None of this is hard-coded, rather it is all decorated by the chain itself. So for instance, if the slots API is included in any chain, this function allowing you to bid will be made available - https://github.com/paritytech/polkadot/blob/master/runtime/common/src/slots.rs#L409

**Comment by Yangxin-GG** [comment]
Thank you！

**Comment by Yangxin-GG** [comment]
OK, I found it, there is a "society" module in tx of JS that can perform Slots Auction operations
However, my JS level is very poor and I don’t know how to use it. Can you write the tutorial in the docs?

**Comment by jacogr** [comment]
The society is completely different. The society is active on chains such as Kusama for the human-blockchain project. (And other chains as well, each with specific rules)

There are no chains that expose parachain auctions or crowdloans yet, these modules are still in change mode and have not been finalized. To use it you would need to 

- checkout the polkadot master branch
- include the relevant modules into a dev nodeconfig
- build it.

Once done, when you connect the API to that node, the modules would be available.

As for specific tutorials, this is sadly out of the scope here - the issue is that the Rust code is always the source of truth and each update changes interfaces in some modules. So keeping that relevant and up to date is an impossible task.

If you want to learn how to use the API, do follow the getting started guides - https://polkadot.js.org/docs/api

**Comment by Yangxin-GG** [comment]
Okay, thank you for your answer
