### ISSUE TITLE
feature/request: publish bundles

### ISSUE THREAD

**Issue by thelostone-mc** [polkadot-js/api#3255]
#### Description 

Would be neat if polkadot would also **publish bundles along with the npm module!**
The reason for this ask if there are projects like Gitcoin which aren't built using node -> this limits the ability to build dapp using polkadot

Right now , to make this integration possible, I'm maintaining a bundle https://github.com/thelostone-mc/polkadot-bundle
which is generated using browserify (details can be found on the repo)

That bundle I generated does end up with warning like multiple instances of the required package.
And I'm assuming that that's cause the polkadot packages use diff version of the same node modules

![photo_2021-02-04_14-36-05](https://user-images.githubusercontent.com/5358146/109650401-2d8bc900-7b83-11eb-999e-8b82015bc9c3.jpg)

I'm not clear on what the right versions would be -> but my hunch is the dev team would probably know the right versions to use to generate the bundle.

I ask this cause I've seen other chains like harmony / binance do this
Even if they don't publish the bundle , it's been baked into their build pipeline so anyone who wants to use it , just pulls in a repo , runs the build command -> copies over and uses the generated bundle

Here is an example:
https://github.com/harmony-one/sdk#bundle
sdk is a node module but to get the bundle , i would just pull that repo and run a command to generate it

**Comment by jacogr** [comment]
The above issue is actually due to a very ineffective bundling operation - it must be massive since it seems that each entry duplicates the same imports, hence what you are seeing on-screen.

Can look at esm full-bundle modules, but umd probably on't be on the cards (have actually been playing with that on-and-off with rollup), but no guarantees as "to when". (Will be in the API v4+ & util v6+ cycle which starts next week) Not sure if that is a requirement, but prefer to move forward since browsers now all support it, instead of doubling-up.

Overall the indv. libs would need to go in and export as indv. globals.

**Comment by ilionic** [comment]
I am echoing the request since it would allow to use polkadotjs api in secure context, ie vm2 or deno for certain js/ts server side use case. On the related note would be nice to make polkadotjs module available here https://deno.land/x

**Comment by jacogr** [comment]
Bundle usage examples -

- Util https://github.com/polkadot-js/common/blob/master/test-bundle.html
- API https://github.com/polkadot-js/api/blob/master/test-bundle.html
