### ISSUE TITLE
Any plans on improving type checking?

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#3322]
We're having some internal debates about whether it's worth having consumers of our PolkaBTC-JS lib (which extends `polkadot-js/api`) use Substrate types or just strings. For instance, the `H256` type does not seem to add any safety checks (compile-time nor runtime). Rather than have consumers do `api.createType("H256", "id_string_example")`, they could just pass the string `"id_string_example"` to PolkaBTC-JS, which would make the conversion on their behalf. 

It seems to me like the only scenario where it would make sense to expose substrate types to PolkaBTC-JS consumers is if `polkadot-js/api` plans on adding more rigorous checks to these types. Is that something on your to-do list? Do you have any recommendations on this topic? 

Thanks

**Comment by jacogr** [comment]
Generally you really don't want to use `api.createType`. Pass the string, array, etc. in and let the API do it.

The `H256` which is `[u8; 32]` internally is interesting, the `[u8; x]` should really do runtime bitLength checks. (like for instance done in numbers or AccountId). 

It is generally a thankless job i.e. small coding to add checks, then updating tests as required - and there are some "interesting" aspects, for instance when decoding from a byte-stream it should only do the bound check on the bytes remaining (so input should be >= required), since there may be left after decoding. In the case of e.g. hex values, it should be exact.

If you do spot places where checks are needed (like `U8aFixed` mentioned above), it is actually good adding them and PRs would be welcomed.

**Comment by jacogr** [comment]
Even issues also appreciated, if not PRs. (As to specific Codec instances - they all need to, but some are more important than others...)
