### ISSUE TITLE
Is there any example code for crownload？

### ISSUE THREAD

**Issue by carrie143** [polkadot-js/api#3329]
I want to develop about dot Parachain slots auctions.I would like to implemente functions for users,like lock ksm/dot for parachain for bid and unlock ksm/dot from parachain？Is there anybody knows?

**Comment by jacogr** [comment]
You can run Polkadot master with the Westend-dev chain. It has the latest modules, although not audited and further changes are probably on the cards. The pallet code for this is well documented on the functionality.

**Comment by carrie143** [comment]
Thank you for your advice。I am from exchange so I need to develop crownload function for user;so I want to ask that is there any example code for crownload integration

**Comment by jacogr** [comment]
Nothing that I'm aware of. You could possibly look at the apps UI code for parachains, which does crowdloans for the current interface for testing purposes, however bear in mind that all of this is unaudited and bound to change from an chain interface perspective. (The current iteration of crowdloan is now a couple of days old)

https://github.com/polkadot-js/apps/tree/master/packages/page-parachains/src/Crowdloan

The best is always tracking the source of truth, which is the Rust code - just because of the un-audited concerns.

https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan.rs
