### ISSUE TITLE
Confirming `metadata` key returned from api.rpc.state.getMetadata()

### ISSUE THREAD

**Issue by jimmychu0807** [polkadot-js/api#3338]
The composed keys returned from `api.rpc.state.getMetadata()` are now `magicNumber` and `_metadata`, with an underscore prefixed to `metadata`. Is this intended?

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/916

**Comment by jacogr** [comment]
You never want to access the `_metadata` key, that is internal and intentional.

The structure is a handler for all versions of metadata with a consistent output, to retrieve the latest, you always was to use `asLatest` which will also apply the correct type aliasing that is needed.

Since it seems to be used/discovered, will move it to an explicit private `#` in the next version.

**Comment by jimmychu0807** [comment]
I see. Let's thank chrome dev tool autofilling for discovering unintend-to-expose object key 😄

**Comment by jacogr** [comment]
The issue is that by convention, anything `_*` should not be used and has historically been used (not only here, everywhere for private/protected members). 

However in the last 8 months the `#` operator got accepted that gives proper privates in JS. The API code does not use it everywhere - if it ain't broke, don't fix it. (protected interfaces are still `_` and will continue to be)
