### ISSUE TITLE
Creating Keyring demos

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3354]
Hey, @jacogr 
Can you please demonstrate how to create Keyring with:
1) Mnemonic phrase with derive path
2) Seed
3) Private key

**Comment by MrRakhim** [comment]
I saw in docs this one 
`const newDeri = keyring.addFromUri(`${PHRASE}//hard-derived/soft-derived`);`
but did not understand what does `//hard-derived/soft-derived` mean

**Comment by jacogr** [comment]
Exactly as above. The hard and soft paths are the Substrate derivation.

See https://wiki.polkadot.network/docs/en/learn-accounts

**Comment by MrRakhim** [comment]
okay, I could create an account by them)
How can I retrieve secret seed, while I've created an account by mnemonic?

**Comment by jacogr** [comment]
The keyring does not expose the private key. It only exposes methods on the pair that uses the key. 

If you wish to use a private key directly, you need to use the (used in the keyring, Not documented) lower level sr25519 or ed25519 functions in util-crypto. The keyring itself uses these, so that is the only real-world sample available.

**Comment by MrRakhim** [comment]
thanks, got it
