### ISSUE TITLE
API: Error [504] Gateway Time-out

### ISSUE THREAD

**Issue by Piratnewtime** [polkadot-js/api#3365]
I'm always banned if I try to use **more than one** connection to our **Polkadot** node.

When I use HTTP connection then I see errors "[504] Gateway Time-out" from every scripts which use the node.
When I use WS connection then "Error: disconnected from ws://...:9292: 1006:: Connection dropped by remote peer.".

I need to load all blocks from the node and for that I use only 3 methods:
1. `await api.isReadyOrError;` (when I'm blocked then in this step I can catch errors about failed queries of health, chain or something else)
2. `await api.rpc.chain.getBlockHash(number)` 
3. `(await api.rpc.chain.getBlock(hash)).block`

So, when I use only **one** connection it may work fine, but if I start **one more** script with connection to the node, then all connections are blocked and I have to wait some time when I can load blocks again.

We increased number of connections up to 100 and nothing was changed.

If I was blocked reloading scripts can't help me, but if the node was restarted, then I can connect and load new blocks without waiting end of ban.

![image](https://user-images.githubusercontent.com/10776668/113297802-22f05b00-930c-11eb-839b-63688f0d38ad.png)

Our node has enough resources and doesn't show any logs about my bans. But we didn't try to turn on debug logs because there were too many logs.

I have no ideas what we can configure to solve this problem.

**Comment by jacogr** [comment]
This is a node-side and/or deployment issue - the HTTP/WS client cannot connect with the node and the node drops the connection. Could very well be routing-related as well, however since it seems like IP addresses above, there should be nothing lookup-related (and either way that only happens once on connect at least in the case of WS)

I would suggest looking at the trace options on the node (they are very noisy) to see when the node closes the connection.

WS only maintains a single connection until dropped, HTTP obviously makes one per query.

**Comment by Piratnewtime** [comment]
I've made more tests and discovered that I can have more than one connection, but when I try to load **3899548** block all connections immediately stop and show me those errors in the same time for all connections from different servers. I checked that **port** and it's still **open**, but **API isn't responding**. Already 10 min past and still not working.

**Comment by Piratnewtime** [comment]
Also we don't know how to see **only** trace logs on the node, is there any way to see only traceroute logs from api?

**Comment by jacogr** [comment]
The -ltrace=... option in the node I believe. 

Couple of questions -

- I am assuming you are running the node in archive mode?
- Is the 10 mins over WS or HTTP? (WS has keep-Alice’s, HTTP not)
- What is the load on the RPC node during that time? (Some post upgrade will be really heavy since new metadata should be generated)
- Are toi seeing the Same when using one of the public nodes? (Which are WS only)

Will check that specific block myself when I am at a PC.

**Comment by Piratnewtime** [comment]
1) Yes, we run our node in archive mode.
2) As I see if I try to load block 3899548 through WS, then API on WS won't be working, but HTTP continue work... until I try to load that block through HTTP... then API on HTTP also won't be working.
3) We didn't see any resources problems and high load on that moment.
4) Yep, I've just tried WS with public node and one my connection continue working while another connection with a try of loading bad block was dropped.

`2021-04-02 14:12:33          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Connection dropped by remote peer.`
`2021-04-02 14:12:33        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from wss://rpc.polkadot.io: 1006:: Connection dropped by remote peer.`
`2021-04-02 14:12:34        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: disconnected from wss://rpc.polkadot.io: 1006:: Connection dropped by remote peer.`
`2021-04-02 14:12:34        RPC-CORE: health(): Health:: disconnected from wss://rpc.polkadot.io: 1006:: Connection dropped by remote peer.`
`2021-04-02 14:12:34        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://rpc.polkadot.io: 1006:: Connection dropped by remote peer.`

**Comment by Piratnewtime** [comment]
Okay, we see a log from that trace of RPC... It's really big log. I think it may be reason why API is blocking.
![image](https://user-images.githubusercontent.com/10776668/113426804-0aa03f00-93e5-11eb-8d9b-4f375e3a18ed.png)
