### ISSUE TITLE
u8a.subarray is not a function

### ISSUE THREAD

**Issue by ziwenxie** [polkadot-js/api#3414]
error info:

![image](https://user-images.githubusercontent.com/24546717/115366738-2767af80-a1f8-11eb-99b8-5f5ca62a6317.png)

![image](https://user-images.githubusercontent.com/24546717/115361205-ef11a280-a1f2-11eb-9ce6-be6e725d8da6.png)

substrate interface:
```rust
		pub fn swap_with_exact_supply(
			origin: OriginFor<T>,
			pairs: Vec<CurrencyId>,
			amount_1: u128,
			amount_2: u128,
			tmp_param: fixedu128,
```

javascript types.json definition:

```json
  "CurrencyId": {
    "_enum": {
      "Token": "Token"
    }
  },
  "Token": "u8",
  "CurrencyIds": {
    "_": "Vec<CurrencyId>"
  },
```

Any ideas on this?

**Comment by jacogr** [comment]
The interafce expects an input of `{ _: [{ Token: 1 }...] }` as you have defined CurrencyIds.

**Comment by jacogr** [comment]
If it is just because of SCALE codec on the Rust side that that `{ _: 'Vec<CurrencyId>' }` is defined that way, you can just flatten the definition to `Vec<CurrencyId>`. 

No field names are encoded in SCALE, so all these are equivalent encoding wise - 

`{ _: 'Vec<CurrencyId>' } === (Vec<CurrencyId>) === Vec<CurrencyId>`.

In this case don't believe the `{ _: ... }` would add much value from a readability perspective, at least now when being used.

**Comment by ziwenxie** [comment]
okay

**Comment by ziwenxie** [comment]
Hi @jacogr 

`"CurrencyIds": "Vec<CurrencyId>",` not working:

![image](https://user-images.githubusercontent.com/24546717/115856981-bcb8ad00-a45f-11eb-906e-ba3f0e8fbb7a.png)

`  "CurrencyIds": { "_": "Vec<CurrencyId>" },` is working:
![image](https://user-images.githubusercontent.com/24546717/115857180-f4bff000-a45f-11eb-972a-faffe4c5d94b.png)

**Comment by ziwenxie** [comment]
> The interface expects an input of `{ _: [{ Token: 1 }...] }` for the first param since that is how you have defined CurrencyIds.

Hi @jacogr 
`{ _: [{ Token: 1 }, {Token: 2}]},`  not working => error info `Cannot map Enum JSON, unable to find '_' in token`
