### ISSUE TITLE
query doublemap with the second key

### ISSUE THREAD

**Issue by amphineko** [polkadot-js/api#3499]
Take this as an example:

``` rust
	#[pallet::storage]
	#[pallet::getter(fn staked)]
	pub type Staked<T: Config> =
		StorageDoubleMap<_, Twox64Concat, T::AccountId, Twox64Concat, T::AccountId, BalanceOf<T>>;
```

How could I retrieve all `Staked` entries by the second map `AccountId` key?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/storage#how-do-i-use-entrieskeys-on-double-maps

**Comment by amphineko** [comment]
Thank you.

I think this article covers retrieving based on the first map key. 

Actually, I'm going to look up entries based on the second map key. (i.e any entries with a specific second map key, and the first map key is not concerned)

**Comment by jacogr** [comment]
That is not supported. Keys are constructed with `prefix ++ hash(key1) ++ hash(key2)` so lookups are possible on `prefix ++ hash(key1)`.

**Comment by amphineko** [comment]
Do you have any advice about, or solutions rather than, retrieving all the keys and iterating over them to filter by the second map key?

**Comment by jacogr** [comment]
So technically, it is very possible - it is just horribly ineffective. 

- query by the `prefix` only
- filter all keys (which will be the full map) for the interested entries

So that is why it is not supported on the JS side since it basically means retrieving the full map (which is not cheap) and then filtering. In the case of the first key being supplied, the `prefix + hasher1(key1)` is done on the node. So the irrelevant entries are not retrieved from the trie itself since the sub-part is matched.

**Comment by amphineko** [comment]
Thanks for your confirmation. :)
