### ISSUE TITLE
await api.derive.staking.waitingInfo returning zero for all exposure.others 

### ISSUE THREAD

**Issue by jhonalino** [polkadot-js/api#3574]
I'm trying to get the nominators for waiting validators. but everything is zero when I do 

`
    // get the chain information
    const waitingInfo = await api.derive.staking.waitingInfo({ withController: true, withPrefs: true });
    const waiters = waitingInfo.info.map(function (b) {
        return b.exposure.toJSON();
    });

    window.waiters = waiters;
    console.log(waiters);
`

I might just be missing something. but need help figuring out getting the waiting like the "targets" section in polkadot-js thank you !

**Comment by jacogr** [comment]
The exposure is only applied when the actual validator is active - so Exposure refers to the active stake.

To get the mapping of nominators -> validator, you need to retrieve all the nominations and map them to the validators. (This is a horribly expensive exercise... actually in the apps UI contemplating if it is worth it since it is well, "quite slow")

**Comment by jhonalino** [comment]
oh I see. I imagine this will get worse once we have 100k nominators. 
damn. 

for my purposes the only thing I can think of to scale this is cache the results server side and feed it to frontend in a paginated way for almost instant experience. but that comes at a cost of decentralization. I can't package it for ipfs anymore. 


is this the reality now of truly decentralized apps? cause querying a blockchain is slow. but it also means its the most accurate and truly decentralized. 


I guess this is an open ended question. but what do you recommend for apps that want to query and displays expensive calls like this but want both speed and decentralized web3 vision. or do I have to choose one over the other???? 

thank you and sorry for thr bother.

**Comment by jacogr** [comment]
Good question, don't have the answers - so I'm really into the "decentralize everything" camp, which is why stuff like the apps UI only uses on-chain data. However, well, atm the RPC nodes themselves are "centralized" although at least for some there are multiple options. (There is work ongoing to have light browser nodes running in an extension.... but we are not there yet...)

For better UX, having at least some things in a centralized DB gives a much better experience. I prefer however to keep things non-reliant-on-DB, but yes, a lot of things are much harder in that case. It is a trade-off and a call that every dev needs to make for themselves, their goals and their app. (in some cases I have played with caching some stuff in the browser, but that is also very limited, 5MB which doesn't really go far enough to make an impact)

The RPC layer only exposes the data on-chain and the data on-chain is there for current and future block processing - trie storage is not optimal, so the blockchain only keeps the state it really needs to process and nothing more, not the state that external people to the blockchain may want.

**Comment by jhonalino** [comment]
appreciate your response jaco! I kept pondering over this question and I'm glad to hear your thoughts on this. cleared up some indecisions on my mind
