### ISSUE TITLE
Subscription leak in react useEffect.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#3597]
Hi, having the following react code:

```
const useBlocksInfo = ({ isApiReady, api, chain }: Props) => {
  const isMounted = useIsMounted();
  const [bestBlock, setBestBlock] = useMountedState('');
  const [bestBlockFinalized, setBestBlockFinalized] = useMountedState('');

  useEffect(() => {
    let unsubscribeBestNumber: () => void;
    if (api && isApiReady && chain && isMounted()) {
      api.derive.chain
        .bestNumber((res) => {
          setBestBlock(res.toString());
        })
        .then((unsub) => {
          unsubscribeBestNumber = unsub;
        })
        .catch((e) => logger.error('error reading blocks', e));
    }
    return function cleanup() {
      unsubscribeBestNumber && unsubscribeBestNumber();
    };
  }, [api, isApiReady, chain, setBestBlock isMounted]);
```

I would like to know if there is any way to prevent the following scenario:

1) Component is mounted.
2) Promise start.
3) While the promise is running the component gets unmounted.
4) Subscription does not get terminated because the `unsubscribeBestNumber` is not set.

Is there any way we can prevent this scenario with the existing api code?

In case there is not, i found this js controller that can help to manipulate the connection: https://developer.mozilla.org/en-US/docs/Web/API/AbortController

i'm thinking that queries can accept kind of signal parameter so we can abort the connection in the clean up useEffect in case the unsubscription function is not assigned.

**Comment by jacogr** [comment]
Well aware of AbortController, it actually gets used quite a bit elsewhere, see https://github.com/polkadot-js/phishing/blob/master/packages/phishing/src/fetch.ts#L7-L30

In this case it is a catch-22, since you want something retuned to use and the functions are dual-use. Additionally, there is no `Abort` -

- underlying it doesn't use fetch
- it is actually rxjs observables (which does have abort functionality)

You can do it the following way.

```js
useEffect(() => {
  const unsubPromise = api.derive.chain.bestNumber((res) => {
    setBestBlock(res.toString());
  });
  
  return () => unsubPromise.then((u) => u());
});
```

So the promise always resolves before attempting it.
