### ISSUE TITLE
Allow Chaining `.entries()` and `.at()` Storage Query

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#3622]
A common query that user might want to make is to get all the balances or staking info for a specific past block.

To do this, they need to both query all items in a map with `.entries()`, but then also specify a specific block hash with `.at()`.

At the moment, it does not seem these two APIs can be chained together.

**Comment by jacogr** [comment]
.entriesAt and .keysAt do exist (not in the docs currently)

**Comment by shawntabrizi** [comment]
wonder for ergonomics if it could be manipulated into a `api.query.system.account.entries.at(hash)`, but nbd

**Comment by jacogr** [comment]
There is another for in the works (query and consts), that will look something like - 

api.queryAt(hash).somewhere.something.entries() 

it actually has the benefit of decorating old modules and their storage names at that point of the chain (atm you cannot really query keys that don’t exist anymore since they are. It decorated)
