### ISSUE TITLE
Decoded input doesn't match input | query.system.account | local node 

### ISSUE THREAD

**Issue by NickitaX** [polkadot-js/api#3641]
While connecting to a local substrate node to query account information:

```javascript
const wsProvider = new WsProvider('ws://127.0.0.1:9944');
const api = await ApiPromise.create({provider: wsProvider});
let { data: { free: previousFree }, nonce: previousNonce } = await api.query.system.account(context.address);
````

the following error is getting fired:

`RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (76 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)`

I believe it is tightly connected to [this issue related to validators](https://github.com/polkadot-js/api/issues/1160) which was resolved.

````json
"@polkadot/api": "^4.13.1"
````

**Comment by jacogr** [comment]
No. The issues are not related. 

I am assuming you are connecting to a Substrate 3 node, which by now has very outdated types. The AccountInfo structure has completely been changed in Substrate master (and deployed to networks following recent changes such as Kusama and Polkadot). 

You need to inject the (now outdated types), to your API instance, since the API will always track current types by default.

**Comment by NickitaX** [comment]
Indeed @jacogr I was using the Substrate 3 node which was coming from tutorials. Thanks, it did fix the problem. I will try to use the latest build to stay updated with current API 👍
