### ISSUE TITLE
Question: Getting section and method on multisig args

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3667]
I am trying to get section/method for each of multisig args and cannot find it anywhere.

For example if I iterate through batchAll args I can check if arg is system remark like so

```
call.section === "system" &&
  call.method === "remark" &&
```

But inside of multisig.asMulti I cannot find sectrion/method for each arg, only values

```
const extrinsics = signedBlock?.block?.extrinsics;
const extrinsic = extrinsics?.[0];
const isMultisig = extrinsic.method.section === "multisig" && extrinsic.method.method === "asMulti"; //true

const systemRemark = extrinsic.method?.args?.[3]; // this is just hex bytes of system.remark value
```

tried logging all the nearest props and cannot find it

Any help is greatly appreciated. Thanks

**Comment by jacogr** [comment]
It is an `OpaqueCall`, see https://polkadot.js.org/docs/substrate/extrinsics#asmultithreshold-u16-other_signatories-vecaccountid-maybe_timepoint-optiontimepoint-call-opaquecall-store_call-bool-max_weight-weight

Opaque since it is encoded as a `Vec<u8>`. 

If you want to extract the data, you can do `api.registry.createType('Call', opaqueCall.toU8a(true))` (The `true` here is important, since that strips the `Vec` length encoding)

**Comment by Yuripetusko** [comment]
Thanks very much, very helpful
