### ISSUE TITLE
Cannot read property 'rpc' of undefined

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3684]
Hi. I made a short code which get value of blockhash and get block by blockhash. But I occured the error `Cannot read property 'rpc' of undefined`. How do I solve the problem?

used API: @polkadot/api v4.15.1. 

Short Code:
```typescript
export default class PolkadotService extends BaseService {
    protected api: ApiPromise
    protected provider: WsProvider

    constructor(config: IApiConfig, logger: Logger) {
        super(config, logger);
        const provider = new WsProvider(`${config.hostUrl}${config.port ? `:${config.port}` : ''}`);
        ApiPromise.create({ provider }).then(a => (this.api = a))
    }

    private getBlockHash = async num => {
      const hash = !num ? await this.api.rpc.chain.getBlockHash() : await this.api.rpc.chain.getBlockHash(num)
      return hash.toString()
    }

    private getBlockByHash = async hash => await this.api.rpc.chain.getBlock(hash)

    protected async fetchAssetTransfers(blockNumber: number, retryLimit: number): Promise<IDeposit[]> {
        let transfers: IDeposit[] = [];
        let from = ''

        try {
          const blockHash = await this.getBlockHash(blockNumber)
          const { block } = await this.getBlockByHash(blockHash)
        } catch(e) {
        this.logger.warn(`Error while fetching transfers for block #${blockNumber}: `, e);
        }
    }
}
```

**Comment by boohyung** [comment]
The constructor was missed. Could you check the short code again?

**Comment by jacogr** [comment]
This is a promise -

`ApiPromise.create({ provider }).then(a => (this.api = a))`

It doesn't not resolve immediately. It depends on the event loop and in this case the API does connection and decoration as well. So you are using the `this.api` before it was initialized. Since it is not initalized, it is undefined.

**Comment by boohyung** [comment]
How do I initialize this.api and get resolve?

**Comment by jacogr** [comment]
Ok, this has really nothing to do with the API, this is just pure JS and working with promises. Promises are always async, see https://developers.google.com/web/fundamentals/primers/async-functions

I really don't have the bandwidth to teach JS and Promises here since this is purely a misunderstanding of sync vs async code and how Promises resolve in the event loop. The best I can suggest is to brush up on your knowledge of how Promises work, there are a bunch of tutorials, like the link I shared above available on the internet.

**Comment by boohyung** [comment]
Thanks @jacogr Let me check the doc.
