### ISSUE TITLE
unsubscribe is not work 

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#370]
For api-observable, I try  unsubscribe bestNumber, but it not send chain_unsubscribeNewHead request

**Comment by aniiantt** [comment]
may be we can use shareReplay instead ReplaySubject
![image](https://user-images.githubusercontent.com/7029338/47841631-3faf9e00-ddf5-11e8-829d-a6e5a2d15813.png)

**Comment by jacogr** [comment]
Yes, I'm suprised it doesn't work, but at the same time it has not seen unsubscribe testing in a very, very long while and a lot of changes has gone into it since it was known working. (There really should be tests around this, that is a failing here)

So the state of the RxJS versions -

1. We are generally trying to point people towards `api/rx`, hence the documentation all around that
2. api-observable is what the UI uses, but it still needs a bit of TLC to get it nicely aligned with where everything else is now, i.e. 
- it doesn't quite extend from `api/rx` like it should
- really should only have the functions which are not available in the base, i.e. things like combines (and bestNumber is actually a good example of useful things in there since it takes another sub and then pulls info from it)

With all the above background, the fix should indeed go into the `rpc-rx` package (as indicated above) - so it pulls into both the above mentioned uses.

**Comment by jacogr** [comment]
So reading through the linked issue, def. seems we introduced this very recently when swapping from `BehaviourSubject` to `ReplaySubject`. (Unless the former also has the issue). 

I've followed your suggested approach and it seems to do the trick with a test, i.e. unsub seems to be called in this case - https://github.com/polkadot-js/api/pull/373
