### ISSUE TITLE
New Type Require

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/api#3737]
The [BlockNumberFor](https://crates.parity.io/frame_system/pallet_prelude/type.BlockNumberFor.html) was become a part of substrate pre-define type.

**Comment by jacogr** [comment]
The actual API types doesn't actually have -

(a) everything that is in Rust
(b) everything that is in the Substrate traits

Rather they do get added based on what can be "seen" on substrate master and Polkadot master, i.e. stuff that gets used there in pallets. Even then tracking is quite difficult at this point before we get to having these exposed in the actual metadata.

However, when it is available, it should be added since it does make life easier for all.
