### ISSUE TITLE
Method instance args getter should return Array not a Struct so remove the FIXME 

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#374]
If we create a new instance of the `Method` class, it is understood based on discussion with @amaurymartiny that the current functionality of the `args` getter is ok, and the FIXME as shown [here](https://github.com/polkadot-js/api/blob/master/packages/types/src/Method.ts#L170) is no longer required.

For example, when you go to http://localhost:3000/#/extrinsics and click Submit Transaction, and you want to obtain the recipientId (dest) and amount (value) from the prop `this.props.value.extrinsic` that passed down to polkadot-js/apps/packages/ui-signer/src/Extrinsic.tsx, then 

```
const methodInstance = new Method(extrinsic, extrinsic.meta);

// WRONG - do not use `.raw`. 
// See https://github.com/polkadot-js/apps/pull/389#discussion_r230735365
// const recipientId = methodInstance.args[0].raw.toString();
// const amount = methodInstance.args[1].raw.toString();

// WRONG - suggested in the FIXME, but not preferred approach
// const recipientId = methodInstance.args.get('dest').toString();
// const amount = methodInstance.args.get('value').toString();

// RIGHT
const recipientId = methodInstance.get('args').get('dest').toString();
const amount = methodInstance.get('args').get('value').toString();  // or .toBn().toString()
```

Proposed action is to remove the following [FIXME](https://github.com/polkadot-js/api/blob/master/packages/types/src/Method.ts#L170)
```
get args (): Array<Base> {
    // FIXME This should return a Struct instead of an Array
    return [...(this.get('args') as Struct).values()];
  }
```

**Comment by jacogr** [comment]
I actually disrespectfully disagree and agree wit the FIXME :)

Since we expose (everywhere else), the Map values as getters, this should align. So there is need for the `args` array, however the `get args` should return the underlying actually value, i.e. it should be a Struct.

So suggesting would be for `get args` to return the Struct (as per FIXME) and something else to return the convience helper. Generally I have yet to use the `get('something')` in the UI, always could rely on the `get something` helpers. (Only in the case of generic stuff like Event is `get('something')` really needed)

**Comment by jacogr** [comment]
Closing, not planning on breaking the external interfaces for this.
