### ISSUE TITLE
RPC-CORE: health(): Health:: Network request failed

### ISSUE THREAD

**Issue by AlexBHarley** [polkadot-js/api#3856]
Our React Native application is receiving hundreds of `RPC-CORE: health(): Health:: Network request failed` logs while just sitting idol. They're in bunches of 7 every 10 seconds. Is there a way to disable the health check? Obviously internet connection has not been lost. 

We're connecting to `https://rpc.polkadot.io`.

**Comment by jacogr** [comment]
Withou the Health check, the WS Connection will drop every 60s.

**Comment by AlexBHarley** [comment]
@jacogr I'm connecting via `https`, not the `wss` endpoint so is the health check still necessary?

**Comment by jacogr** [comment]
There is no logic differences - so yes, in wss it is not strictly needed, but not going to have different logic paths.

**Comment by AlexBHarley** [comment]
Makes sense, can this issue then become a request to make that ten second health check configurable?

**Comment by jacogr** [comment]
So still not sure why this fails in your case. 

However having thought through it, it actually makes no sense at all to do the health check since it really is not applicable. It does not hurt, but at the same time it actually adds no value on non-WS endpoints and actually does add (albeit very small) some load to the endpoint nodes. So the reason it is there is non-sensical in this case.
