### ISSUE TITLE
Can we make second arg (ClassId) optional in uniques.account query

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3865]
I would like to query all assets by account, because I might not know all classIds where these assets are located

`const keys = await api.query.uniques.account.keys(accountId);`

But this throws an error that second argument is missing

The line in question for generated types where second argument is not Optional is here, but I am not sure how to make it optional as it's generated from onchain metadata
https://github.com/polkadot-js/api/blob/ba74ad0be9ea5b2640f3b2c0ba1b23c786bc190b/packages/api/src/augment/query.ts#L1347

**Comment by Yuripetusko** [comment]
And follow up question. If ClassId becomes optional, will returned double map contain classId. Because I don't see any other way to get classId from queried asset/instance

**Comment by jacogr** [comment]
When you query directly, you need to supply all arguments - as per the generated types. For item retrieval, unlike keys/entries, you need to be pin-point accurate.

Currently, for keys/entries -

- with 1 argument (Map), none should be supplied, N - 1
- with 2 arguments (DoubleMap), 1 should be supplied, N -1
- with N arguments, N -1 should be supplied

It should (untested, unknown) be possible to query with N -2 or no keys in all cases. This would probably bring the RPC nodes down since the keys queries are quite heavy (although at least now it is a paged RPC).

PRs and tests welcome to see if it could work - https://github.com/polkadot-js/api/blob/master/packages/types/src/metadata/decorate/storage/createFunction.ts#L106-L132

**Comment by Yuripetusko** [comment]
I will try this in a week if no one else will, please don't close this ticket yet.

I understand there can be an issue of a query that is too heavy, but using paged query should be ok

**Comment by jacogr** [comment]
Closed in #3886

**Comment by Yuripetusko** [comment]
Thank you @hamidra
