### ISSUE TITLE
Abnormal closure 

### ISSUE THREAD

**Issue by barmanabarmana** [polkadot-js/api#3951]
I am trying to connect to test api 
```
async  function ConnectToApi() {
            const api = await ApiPromise.create({provider: new WsProvider('wss://rpc.realis.network')});
            await api.isReady

    }
```
and it fails -this is the error 
![image](https://user-images.githubusercontent.com/87117376/133231655-31b0ac78-b43b-477d-a881-8a85b2a8676e.png)

Interesting that if am connecting to wss://rpc.polkadot.io or wss://kusama-rpc.polkadot.io/ everything is fine
Where the problem can be?

**Comment by jacogr** [comment]
That comes from the endpoint itself - sadly WSS (due to security concerns on the implementation layer, i.e. browser/node) doesn't give any additional info, just that, well the connection was aborted.

Since it is a `.network` domain, if done via a browser, ensure your uBlock doesn't block it. (If used - it has a blanket ban on any `.network` domains)

**Comment by barmanabarmana** [comment]
@jacogr it was it
thanks :)
