### ISSUE TITLE
Equivalent of web.eth.abi.encodeFunctionCall

### ISSUE THREAD

**Issue by lukerQuant** [polkadot-js/api#4003]
Hi all,

In Ethereum we can build a smart contract function call without the entire contract abi, see https://web3js.readthedocs.io/en/v1.5.2/web3-eth-abi.html?highlight=encodefunctioncall#encodefunctioncall 

Does polkadot-js have an equivalent? - I haven't seen it. 

If not can it be added? Or if so, are there any available examples?

Regards

**Comment by jacogr** [comment]
You actually need the full ABI for Substrate - the ABI exposes a type registry, so the function signature part itself it not stand-alone but rather refers to the registry for types (and types internally refer to each other as well, e.g. for composite, variant, etc. types)

PRs are certainly welcome to refer to the existing registry and add the above, but it is unlikely something I would do myself since the types needs to be resolvable first.

**Comment by lukerQuant** [comment]
Ah ok I didn't know you need the full contract ABI, thanks for clarifying
