### ISSUE TITLE
Equivalent method for `BlakeTwo256::ordered_trie_root`

### ISSUE THREAD

**Issue by liuchengxu** [polkadot-js/api#4046]
Is there a JS version of the method `BlakeTwo256::ordered_trie_root()`?https://github.com/paritytech/substrate/blob/ba153b9ae050eda022f002d74d76f98d1e339a81/primitives/runtime/src/traits.rs#L490

**Comment by jacogr** [comment]
There is, but it is not in a production library - see https://github.com/polkadot-js/client/pull/250/files#diff-51f60f2f24b6f5970504035d3a232ab8a20bf459225592a269c15ad7e5dd8b93R31

(Trie was only done for the JS client, last time it could sync was in the time of the Alexander testnet. The tries actually changed since then, but at least the ordered and unordered root should still be mostly aligned, just the base trie structure changed when it comes to extension leaves, the roots only need the hashing component, which is _probably_ still aligned)
