### ISSUE TITLE
Documentation for the `derive` method

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/api#4062]
There seems to be a magical `derive` that's not documented on the docs or the library. Some documentation would be useful as the method itself seems quite useful.

Same for crowdloan and auction methods

**Comment by jacogr** [comment]
These are (still, after all this time) deemed unstable. And with reason - for instance in the current released 6.3.1 the derives for balances are broken when you have vesting schedules. (Fixed in master, with a backwards-incompatible change to cater for the new multiple vesting structures) 

It is provided in the API since it may have some applicability to others, i.e. the apps UI uses these extensively to combine data from various sources. It is used by some teams, with the source as the actual truth-of-use. But it is rapidly changing and "quite" unstable since it is quite nimble to enable it to keep up with the different versions and having compatibility across versions from all types of Substrate implementations. (It tries to cater for a single interface to query ancient through to newest)

So this is not something that can be "stabilized" easily and thus documented.

**Comment by jacogr** [comment]
Closing, as it stabilized it will be added to parts that improve. (As per all libs)
