### ISSUE TITLE
Statemine 983158 failed to decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#4072]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-statemine-rpc.paritytech.net#/explorer/query/983158

![image](https://user-images.githubusercontent.com/2264908/137634700-a0e7b7c6-80e0-42b5-beb0-644505e77b23.png)

Hi, @jacogr . I think this is a bug of api.

**Comment by jacogr** [comment]
I am aware of this - sadly the rapid fire release of the v5 runtime didn't leave any time to adjust anything for Statemine, as a matter of fact it means that the types-known needs to be updated since the previous plan for Statemine now only appears in v500 (as opposed to v5)

It is not a high priority trying to track types for this chain, rather the only reason it is done is because of the teleport nature.

**Comment by wliyongfeng** [comment]
No problem. Excuse me for the frequent report. My scan scripts(highly depend on api) produced error logs, so I can always know them.
