### ISSUE TITLE
How do polkadot prevent double-spending ?

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#4147]
Today, I come across a question: If I coined a tx that was originally sent to DOT, then send to Kusama, both of the same nonce, then which property or a set of properties of the Tx used to prevent double-spending?

I anticipate there is a 'chain-type' property used to handle the double-spending issue, but can't find it inside ExtrinsicPayload.js or ExtrinsicPayload.js, etc file.

Can somebody shed light on it? 

Thanks

**Comment by jacogr** [comment]
The extrinsic signature is signed on a payload that contains -

- the mortality (how long the transaction lives)
- the genesisHash of the chain
- the specVersion

if any of these changes from chain to chain (or due to an upgrade), the signature would be invalid.

**Comment by code-brewer** [comment]
> * specVersion

**Comment by code-brewer** [comment]
Thanks, for the quick responses every time I have questions. @jacogr 
I don't think mortality play well in prevent this problem , but genesis Hash does. 
As to specVersion, does every parachain AND relay chain all has its own unique spec version?

**Comment by jacogr** [comment]
Mortality does play a role - for mortal transactions the actual blockHash where the transaction was generated gets signed. So you have 2 block hashes that needs to be valid for the transaction to be valid.

specVersion increases each time there is a runtime upgrade. Basically what this means is that -

- Alice sends a transaction in block 123,456 with runtime (specVersion) 9100
- Chain gets an upgrade at block 123,458 to specVersion 9101
- Alice transaction cannot be included anymore - it is now invalid since there has been an upgrade

The last item is nothing to do with re-play protection, but rather to ensure that transactions appliy to a known runtime, with specific logic and (importantly) transaction indexes. 

(These are also different between chains, e.g. the balances module is not at the same index between eg. Kusama and Polkadot, so actually something like a transfer on Kusama cannot even be decoded with the Polkadot runtime)

**Comment by jacogr** [comment]
Closing, answered.
