### ISSUE TITLE
parse batch transactions

### ISSUE THREAD

**Issue by regazeri** [polkadot-js/api#4148]
Hi
In our project I want to parse transactions and save them in db, about 'utility.batch' type how can i find status of each transfer inside transaction?
e.g--> in a sample batch transaction there are 5 transfer and 4 transfer are success and 1 is fail but status of transaction is success.how can find status of each transfer?
thanks in advance

**Comment by Swader** [comment]
You should be using batchAll instead of batch, to make sure all complete successfully. If they all do, then batchAll will emit a success event, whereas if even one fails, they all revert and a batchInterrupted event will fire. But you should be monitoring for transfer events instead of looking at the batch itself - ignore the batch, and just listen for balance transfer events.

**Comment by regazeri** [comment]
thanks for answer
but I need to check all batch transaction in blockchain and find status of each transfer inside it,I should find method property for each transfer but I don't know how?

**Comment by Swader** [comment]
If you use batchAll and there is no batchInterrupted event, then all transfers inside the batch have 100% successfully executed. That said, you can take apart a batch and scan the contents.

Here's (https://kusama.subscan.io/extrinsic/0x78de8e07e73977788dd5577a248fbfc3d4b06aba84ed4ce2e721a4a15d1e75eb) an example of a batch. If you look at Events, you'll notice that they specify what happened. If the transfer weren't successful, then the even would not say Withdraw, because the Withdraw would not have happened.

**Comment by regazeri** [comment]
thanks for your answer
Is there a condition that in a batch transaction (not in batchAll), only one of the transfers becomes fail and other transfers became  successful?
e.g batch with 2 transfer---- call 0 is success and call 1 is fail

**Comment by jacogr** [comment]
`.batch` would run until one transaction fails, then it interrupts. So if you have 5 transfers - A, B, C, D, E

A - success
B - success
C - fails, BatchInterrupted emitted, batch stops
D - not executed
E - not executed

**Comment by regazeri** [comment]
thanks for your support
my last question:in you example for A ,B will be emit "utility.ItemCompleted" and for C which event name will be emit?is "utility.BatchInterrupted"?
