### ISSUE TITLE
state_traceBlock RPC call is broken in GUI

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/api#4275]
Unless I'm missing something, using `traceBlock()` always results in "Expected 3 parameters, 1 found instead" (I'm only specifying block hash).

I suspect this might be related to [this change](https://github.com/paritytech/substrate/commit/864d096214cbde236f1ced7fdf4017ac22f5e5f5#diff-a470f7227faf378aa4b8cf63f5b3d35018da37803f6bf0456327e4f6d2e15250R322) that is not reflected in GUI yet.

I'm sorry if this is the wrong repo to report.

**Comment by jacogr** [comment]
I missed the linked PR. This now is actually very tricky, with RPCs since additional params cannot be detected. so the best that can be done is breaking it for everybody that have not upgraded to latest. Basically swapping the unhappiness around from those on latest to those on older - generally the API does track only latest on these things, unless PRs are missed like here...
