### ISSUE TITLE
api.createType does not decode little-endian values for primitives U128/...

### ISSUE THREAD

**Issue by sourabhniyogi** [polkadot-js/api#4313]
We would like to rely on api.createType to parse ALL storage values, without treating endianness for primitive types of 
U128/U64/U32/U16 which are encoded in little-endian form systematically.

However, passing to createType yields an incorrect result:
```
> console.log("INCORRECT", api.createType("u128", "0xa096bd1df4ec00020000000000000000").toString());
INCORRECT 213459159603198215814995357739002101760
```

The correct result is:
```
> console.log("CORRECT", hexToBn(v, { isLe: true }).toString() );
CORRECT 144375721290995360
```

Is there a proper way to get the little-endianness decoded correctly for these primitives types from `createType`?

Data with that have U128 data _inside_ them (e.g. free/frozen/..) decode with no issue.

The solution below is quite inelegant because it relies on exhaustively naming every type that needs little endian parsing:
```
const { ApiPromise, WsProvider } = require('@polkadot/api');
const { hexToBn } = require("@polkadot/util");

const api = new ApiPromise({ provider: new WsProvider(...) });
await api.isReady;

let v = "0xa096bd1df4ec00020000000000000000"; // for example...
let query = api.query[pallet][storage].meta;
var valueType = (query.type.isMap) ? query.type.asMap.value.toJSON() : query.type.asPlain.toJSON();
var valueTypeDef = api.registry.metadata.lookup.getTypeDef(valueType).type;
if ( valueTypeDef == "U128" || valueTypeDef == "U64" || valueTypeDef == "U32" || valueTypeDef == "U16"  || valueTypeDef == "I128"  ) {
   // This is likely be error prone if we missed a LE type that we don't know about!
  return hexToBn(v, { isLe: true }).toString()
}  else {
  return api.createType(valueTypeDef, v).toString());
}
```
Is there a better way?

**Comment by jacogr** [comment]
The hex values are very tricky... let me explain. Over RPC when retrieving a value, it comes back in hex form, BE encoded. All SCALE is LE, obviously so the hex encoding in RPC does not match up with what is generally used.

So what the createType and fiends does internally is to treat all number hex values (retrieved via RPC) as BE and then everything else as LE on the decoding step.

So if you have `0x123456` in LE format that you would like to pass in via createType, you need to fool the createType a tiny bit. So convert it as-is to Uint8Array and it knows it is SCALE encoding.

```js
api.createType('u64', u8aToU8a('0x123456')
```

It is not pretty, but sadly due to the RPC discrepancies where either can be passed in depending on where it comes from.

**Comment by sourabhniyogi** [comment]
Ok, we will fool the createType a tiny bit =) -- thank you!
