### ISSUE TITLE
Type documentation links are not working

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#438]
From https://polkadot.js.org/api/types/

- Metadata (and it looks the same as others) is not creating a link
- Other links (e.g. AccountId), try to load the .md file instead of the generated HTML - well, actually HTML is not generated

Need a solution that does not entail adding all these to SUMMARY.md

**Comment by ltfschoen** [comment]
What do you think about this hack https://github.com/GitbookIO/gitbook/issues/659#issuecomment-418074102?
For all the links that we have in the README files of the subdirectories like polkadot-js/api/docs/types/README.md, we'd make duplicates of all the markdown files that they link to in the subdirectory polkadot-js/api/docs/hidden/, and then we'd list them all at the bottom of the main polkadot-js/api/docs/SUMMARY.md, but they wouldn't need to be named i.e.
```
[](hidden/types/classes/_accountid_.accountid.md)
[](hidden/types/classes/_accountindex_.accountindex.md)
...
```
and then we'd add the following CSS to polkadot-js/api/docs/styles/website.css, so that all the links that we've added to the main SUMMARY.md file that link to the hidden/ subdirectory are hidden and don't appear in the navigation page, but because they are added as links in the main SUMMARY.md file, the corresponding .html files will be generated from the .md files in the subdirectories so the links work.
```
.summary .chapter[data-path^="hidden/"] {
  display: none;
}
```

Note: It looks like this Gitbook issue has been around for a while, these are the two issues I found:
* https://github.com/GitbookIO/gitbook/issues/81
* https://github.com/GitbookIO/gitbook/issues/659

**Comment by jacogr** [comment]
Yes, I saw the hack - It would mean we need to add the types to 3 places - types/README, types/index.js and docs/SUMMARY - but sadly I see no other option. So as much as it sucks, it is probably the _only_ solution.

**Comment by jacogr** [comment]
Just a quick one - I would not move the md to hidden, rather make the docs/types/classes folder hidden from SUMMARY.md - that should hide it there and have it in README
