### ISSUE TITLE
support fixpoint types from substrate-fixed

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/api#4386]
This is a longstanding request and had been closed a while back: https://github.com/polkadot-js/api/issues/2488

Now that Encointer will become a common good parachain and other parachain teams start using the types from `substrate-fixed`, I wonder if you may reconsider implementing this.

Encointer uses [substrate-fixed](https://github.com/encointer/substrate-fixed) types [`I64F64`](https://github.com/encointer/pallets/blob/976849b45ba5be04114f62c32c5f8b8fa864103f/primitives/src/balances.rs#L26-L27) for balances and integritee uses [`U32F32`](https://github.com/integritee-network/pallets/blob/0878cf64dc36a5805a358a92ac3952e63a84f601/teeracle/src/lib.rs#L35) for exchange rates and fee tuning.

[Our current approach for js](https://github.com/encointer/encointer-js/tree/master/packages/util#fixed-point-numbers) is using string representation of decimal numbers. Float conversion is tricky, but may be precise enough for practical use.

Would be great to see this translated in js/api, js/apps

**Comment by jacogr** [comment]
How do these types present themselves in metadata v14, ie. What does the type definitions inside the types structure look like when the metadata is decoded?

it is worth a look, but this has nothing to do with common parachains. This is yet another foreign repo to add to the list to align with changes and tests, without easy access to use on local dev networks. So it is a potential maintenance nightmare.

**Comment by clangenb** [comment]
I have just checked how they represent themselves in the metadata. Unfortunately, I think it is an unreasonable request as of now because the rust fixed type is a heavy construct of custom types defined in the [typenum](https://crates.io/crates/typenum) crate. This results in a quite nested structure in the metadata, and it will be quite the efforts to implement generic handling, I guess.

I will probably make sense to wait anyhow because upstream claims to migrate away from the typenum dependency as soon as const generics are supported by rust, which is the case since October. So there might be a fundamental change soon.

So if you agree @jacogr that it would be quite an effort to implement this now, we can close this. We might come back to you when the migration to const generics has been done in the upstream `fixed` crate.

```
 {
      "id": 44,
      "type": {
       "path": [
        "substrate_fixed",
        "FixedI128"
       ],
       "params": [
        {
         "name": "Frac",
         "type": 45
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "bits",
           "type": 55,
           "typeName": "i128"
          }
         ]
        }
       }
      }
     },
     {
      "id": 45,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 46
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 46,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 46,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 47
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 47,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 47,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 48
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 48,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 48,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 49
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 49,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 49,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 50
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 50,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 50,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 51
        },
        {
         "name": "B",
         "type": 54
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 51,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 54,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 51,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UInt"
       ],
       "params": [
        {
         "name": "U",
         "type": 52
        },
        {
         "name": "B",
         "type": 53
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "msb",
           "type": 52,
           "typeName": "U"
          },
          {
           "name": "lsb",
           "type": 53,
           "typeName": "B"
          }
         ]
        }
       }
      }
     },
     {
      "id": 52,
      "type": {
       "path": [
        "typenum",
        "uint",
        "UTerm"
       ],
       "def": {
        "composite": {}
       }
      }
     },
     {
      "id": 53,
      "type": {
       "path": [
        "typenum",
        "bit",
        "B1"
       ],
       "def": {
        "composite": {}
       }
      }
     },
     {
      "id": 54,
      "type": {
       "path": [
        "typenum",
        "bit",
        "B0"
       ],
       "def": {
        "composite": {}
       }
      }
     },
```

**Comment by jacogr** [comment]
This is actually not bad -

```js
{
      "id": 44,
      "type": {
       "path": [
        "substrate_fixed",
        "FixedI128"
       ],
       "params": [
        {
         "name": "Frac",
         "type": 45
        }
       ],
       "def": {
        "composite": {
         "fields": [
          {
           "name": "bits",
           "type": 55,
           "typeName": "i128"
          }
         ]
        }
       }
      }
     },
 ```
 
There are a number of cases where the params are used in determining what to build, e.g. https://github.com/polkadot-js/api/blob/master/packages/types/src/metadata/PortableRegistry/PortableRegistry.ts#L514-L535 for Range and BTreeMap.
 
But yes, it is an intrusive change with internal `TypeDef` support as well - once again, not difficult, but needs attention. Additionally there is the type generation (to cater for all `TypeDef` types as well as the creation paths). Nothing difficult, just sprawling.
 
But basically this is why it is critical that it is easily testable and where my concerns lie. BTreeMap is a prime example - it has been supported by Substrate itself for a very long time, but the API never had support, since well, it was not used anywhere in Substrate base and therefore not implementable nor testable by me. It is like trying to work in the dark when it is not used by the base. It was finally contributed by a team and was followed 9 months later by PRs from another team to make fixes to the support and ordering, which was broken from the initial contribution - well, broken in some cases. 

But is is mostly untested since I cannot just spin up one of the 6-8 Substrate branches I have and verify it.

**Comment by jacogr** [comment]
And no, I'm not against a PR for this - I can review code with proper tests against compliance with the crate, I just cannot code it myself.

**Comment by jacogr** [comment]
Closing until mentioned support is there - please feel free to put in a PR to enable when the time is right (and it can be tested)
