### ISSUE TITLE
Large memory usage regression caused by send caching

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/api#4414]
After https://github.com/polkadot-js/api/pull/4195 our app has very large memory usage (we send transactions with size on the order of megabytes) that inevitably leads to OOM in Node.js.

There is no description in the PR or even eventual changelog on why was it added, what problem solves and there doesn't seem to be a way to disable it globally or even in `.signAndSend()` call.

I'd appreciate some background on that PR at least and ideally not enable such significant changes in the library by default.

**Comment by jacogr** [comment]
1. Literally the PR you linked to has the CHANGELOG entry in the first file - https://github.com/polkadot-js/api/pull/4195/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR11
2. It is not applied on subscriptions, only queries where blockHash is applied, e.g. historic

While making it as invalid here, I will probably adjust the cache downwards, since it is for shorter-term requests only (e.g. request metadata at block, repeat 5 seconds later)

**Comment by nazar-pc** [comment]
You're definitely right about changelog, I was searching `cache` in the changelog and should have looked carefully at the first line of the PR.

I'd like to request disabling such caching entirely, we have multiple connections and send huge transactions via all of them, so even 100 entries would be an issue and will consume a ton of RAM.

I hope to remove this ugly workaround at some point: https://github.com/subspace/subspace-relayer/pull/98/files
