### ISSUE TITLE
Incorrect WeightPerClass type (and decoding)

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#4421]
The latest substrate version has a different definition for the `WeightPerClass` type than polkadot.js. The difference is that `maxExtrinsic` should be an `Option<Weight>`, but is being typed as `Weight`. Apparently not only the typescript types are wrong, but also the decoding itself, because the value that polkadot.js decodes is nonsensical, but if you override the type in the schema you get something reasonable

Relevant code: https://github.com/paritytech/substrate/blob/49a4103f4bfef55be20a5c6d26e18ff3003c3353/frame/system/src/limits.rs#L104

**Comment by jacogr** [comment]
Since metadata v14 the built-in types are static, i.e. they reflect what was there when metadata v14 went live. All types are now retrieved via metadata only,.

**Comment by jacogr** [comment]
On metadata v14 chains that should always decode using the types supplied in the metadata - the type definitions doesn't apply here at all. An example of this against't today's Substrate master -

![image](https://user-images.githubusercontent.com/1424473/148403813-2704a1aa-db20-45f3-99a6-57f0ba4b0d48.png)

The type being `FrameSystemLimitsBlockWeights` as retrieved from the metadata itself.

**Comment by monitz87** [comment]
Our chain uses metadata v12. What can we do to get the correct value other than overriding the type definition when instantiating the API?

**Comment by jacogr** [comment]
The only option would be to add the type to the API init, aka as part of your bundled types. We don't want the overhead of still having to maintain types against Substrate master. This is a solved problem since the metadata now supplies everything.

Substrate has diverged quite a lot since types have been frozen. Each retrospective update would have a ripple effect, i.e. any team maintaining historic type information for their chain would have to go back and add overrides up to the point of v14 upgrade.

**Comment by monitz87** [comment]
Understood, and fair enough. Thanks

**Comment by monitz87** [comment]
I know this question is out of the scope of this package, but I can't seem to find this information anywhere else:

I assumed the metadata version was tied to the substrate version, but it appears it isn't. How do you upgrade the metadata then?
