### ISSUE TITLE
Property 'data' does not exist on type 'Codec'.ts

### ISSUE THREAD

**Issue by nsoshenko** [polkadot-js/api#4450]
Trying to get account balance starting with api query:
`const {data: balance} = await api.query.system.account(address);`

I find it quite similar to the example shown at https://polkadot.js.org/docs/api/examples/promise/listen-to-balance-change :
`let { data: { free: previousFree }, nonce: previousNonce } = await api.query.system.account(Alice);`

But getting a TS error:
![](https://user-images.githubusercontent.com/61120416/149354883-f0a9923b-686a-4367-81ff-07c19b4106df.png)

Tried to downgrade @polkadot/api to 6.4.2 thinking the issue is in PR https://github.com/polkadot-js/api/pull/4329/files, but it changed nothing.
Would appreciate any help!

**Comment by jacogr** [comment]
This actually should be in the FAQ. Sadly it only exists in the changelog - 

https://github.com/polkadot-js/api/releases/tag/v7.0.1

will add to the FAQ over the weekend.

**Comment by nsoshenko** [comment]
Many thanks, @jacogr !
Addition of `import '@polkadot/api-augment';` doesn't fix the issue for me.
Would appreciate a link to the edited FAQ afterwards and have a nice weekend.

**Comment by jacogr** [comment]
See https://github.com/jacogr/api-test-4450 for an example (working as expected)
See https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing (augmentation explanation)

As always, when dealing with TS, ensure you are on a recent-ish version, explanation here - https://polkadot.js.org/docs/usage/FAQ#under-typescript-i-have-ts-compilation-errors
