### ISSUE TITLE
Types error in api-derive package

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/api#4455]
<img width="972" alt="截屏2022-01-16 下午3 37 42" src="https://user-images.githubusercontent.com/20088392/149651506-7a2e4bec-1ea4-455c-a39c-05b7c1911f87.png">

version: 7.4.1

**Comment by jacogr** [comment]
See the release notes for 7.0.1 - unlike older versions, you need to specifically add the API augmentation, either for your chain or the default Substrate/Kusama/Polkadot. This ensures that the API is correctly augmented for your chain, instead of forcing down Substrate types which is some cases cannot be overridden.

TL;DR `import '@polkadot/api-augment';` is not done automatically since 7.0, it has to be applied specifically.

**Comment by jacogr** [comment]
Added an FAQ entry with the specifics, https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing
