### ISSUE TITLE
How to handle: `Unable to decode storage [...] Decoded input doesn't match input`?

### ISSUE THREAD

**Issue by maltekliemann** [polkadot-js/api#4456]
I sometimes receive errors like the following when dealing with a local node:

```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.number:: createType(BlockNumber):: u32:: Decoded input doesn't match input, received 0xe094040000000000 (8 bytes), created 0xe0940400 (4 bytes)
```

A couple of questions:

- I guess this is a result of broken metadata? (This particular error was the result of forgetting to initialize the `api` with the `types` object.)
- When I connect to the local node using the polkadot.js browser interface, the same queries work just fine. Why?
- Suppose I get an error like this. Is there any better way to debug this than to go into the code of the node and try to guess the correct info for the `types` object that the API is initialized with?

**Comment by jacogr** [comment]
To answer the questions -

1. For older chains (i.e. those not using metadata v14), the API uses the defaults from Substrate. If changes are made to the types, the API doesn't know about them and they need to be specified. (This is not an issue with any chains using metadata v14, since the metadata no conveys all the types... well, more-or-less, types used in RPCs are not exposed in the metadata)
2. The apps UI has type definitions for chains that are injected, so if it is known there, the apps UI takes care of it, see https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/index.ts 
3. No, changes on Substrate needs to be reflected in the API. Unless, as said above, the chain uses metadata v14, then all tx, query, ... would be correctly decorated based on metadata - actually if you specify type overrides on these chains, they are just ignored since the metadata has full type definitions. Obviously with the caveat for RPCs, e.g. something like `BlockNumber` does appear in header RPC calls, so would still need to be specified.

**Comment by maltekliemann** [comment]
Thank you!
