### ISSUE TITLE
Missing developer documentation

### ISSUE THREAD

**Issue by gabrieljaegerde** [polkadot-js/api#4516]
Would be great to add some documentation for developers wishing to clone the repo and play around with it locally.

**Comment by gabrieljaegerde** [comment]
I am looking to edit and build the package locally and then add it to a local repository to test with npm link. 
Any help here would be appreciated as I don't seem to get it to work and I am sure it involves just running a command or 2 to get up and running.

**Comment by jacogr** [comment]
Build -

- `yarn build`

Test -

- `yarn test`

Linking won't work, since it is compiled. However there is a command inside https://github.com/polkadot-js/dev that allows to copy compiled versions. With a structure such as - `<Root>` - the root folder containing the `api` and `your-project`, i.e.

- `<Root>/api`
- `<Root>/your-project`

From inside the api folder run `yarn polkadot-dev-copy-to your-project` and it will compile and copy the files to `../your-project` from the `api` clone

**Comment by gabrieljaegerde** [comment]
EXACTLY what I needed!!! Thanks a bunch @jacogr .

Any reason why this info is not included in the README? Happy to make a PR.

**Comment by jacogr** [comment]
It belongs on the dev repo descriptions, with details for all the relevant scripts. (Since it applies to all Polkadot-JS libs not api only - and is supplied there)
