### ISSUE TITLE
Recursive block parser

### ISSUE THREAD

**Issue by rezafx** [polkadot-js/api#4683]
Hi, I'm working on an exchange and need to parse all blocks transactions,
I need to parse something like this : https://westend.subscan.io/extrinsic/0x9a3b8da7b055dc67e948c25e7c67f5ca6ef049011eb1de4901fc44a91d48b407
Here is my question:
How can I determine which event is related to which call ?
I tried to handle it using Depth-first algorithm but I didn't manage to do that

**Comment by jacogr** [comment]
This should be applicable - https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by rezafx** [comment]
I'm using `this.api.derive.chain.getBlock` to get block and then :
```
block.extrinsics.map(({ dispatchError, events, extrinsic }) =>
      this.transactionsScanner.scanTransaction(dispatchError, events, extrinsic),
    );
This helps me to get matched events, Let me explain my problem
imagine we have a transaction and this transaction contains 2 or more batch or batchAll and in events I see batchCompleted and batchInterrupted, Now how can I determine which event is related to which call ?
 
```

**Comment by jacogr** [comment]
The event phase, will have the `isApplyExtrinsic` and that maps to the index of the exteinsic. So if you have for instance -

- index 1: BatchA
- index 2: BatchB

The `asApplyExtrinsic` on the `BatchCompleted` will map to either index 1 or 2 and the other `BatchInterrupted` will map to the other (remaining) index.

**Comment by rezafx** [comment]
I have this : 
index 1: BatchA =>contains BatchAll a,BatchAll b
index 2: BatchB =>contains BatchAll a,Transfer b
our batch have childs and that childs are batch. look at this :https://westend.subscan.io/extrinsic/0x9a3b8da7b055dc67e948c25e7c67f5ca6ef049011eb1de4901fc44a91d48b407

**Comment by jacogr** [comment]
Here is the hierarchical view - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/explorer/query/10091936

Since the events only have a single index, the all point to a single parent extrinisic, e.g. as mapped in the link. There is no event phase identifier for sub, however certain events will have information, i.e. `ItemCompleted` has the index of the item in the batch. 

The only clue you have with nested batches is that everything executes sequentially, i.e. events are deposited in that order as well. However in the above case, it is quite a bit to untangle...

**Comment by jacogr** [comment]
This is actually a great StackOverflow question... there has been some similar ones in the past, see https://substrate.stackexchange.com/questions/174/correlate-events-with-extrinsics-in-a-utility-batch-call-in-polkadot
