### ISSUE TITLE
Polkadot 7.14.1 issue with ES Module

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4692]
After upgrading to @master (7.14.1) I get:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/crystalin/projects/moonbeam-tools/node_modules/@substrate/connect/dist/index.js
require() of ES modules is not supported.
require() of /home/crystalin/projects/moonbeam-tools/node_modules/@substrate/connect/dist/index.js from /home/crystalin/projects/moonbeam-tools/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/crystalin/projects/moonbeam-tools/node_modules/@substrate/connect/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/crystalin/projects/moonbeam-tools/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by TarikGul** [comment]
Can confirm I am also seeing this as well when running our jest suites.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@substrate/connect/dist/index.js
require() of ES modules is not supported.
require() of /Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@substrate/connect/dist/index.js from /Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@substrate/connect/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

It's getting late for me, so if need be when I am up tomorrow, I can try and put an isolated reproduction together locally. But that being said, I am assuming this might be more of an issue with `@substrate/connect` directly when it comes to bundling then `@polkadot/api` itself?

**Comment by jacogr** [comment]
Indeed, however since the API includes it (due to the merge of `ScProvider`), it does mean the API has issues :) It needs to support both ESM and CJS.

It looks problematic, `@substrate/connect` is ESM-only based on what I see in `node_modules`, so it seems like we need to revert that or have a dual-version. 

cc @josepot

**Comment by jacogr** [comment]
7.14.2 is released. Sorry about this.

**Comment by jacogr** [comment]
This is sadly creating some nightmares for me as well specifically in the apps UI (with the Jest tests) where `ScProvider` is actually used. Swapping to `@polkadot/rpc-provider/ScProvider` from the previous `0.5.0` version used there yields some interesting failures, 

https://github.com/polkadot-js/apps/runs/5715663918?check_suite_focus=true#step:3:3119

Basically the points to `WellKnownChain` being undefined here https://github.com/polkadot-js/api/blob/bb75b422730d6bf5189a87e9b7bbd1585bd5cd26/packages/rpc-provider/src/substrate-connect/ScProvider.ts#L34

A HACK with `|| {}` fixes it, but that just shouldn't happen and only confirms where the issue is, and is not a fix. Until Jest 28 gets released it is basically stuck in limbo there, the issue is that Jest grabs the CJS bundle for the rpc-provider and then tries to import ESM, so untold nightmares results from this. (This is purely a Jest issue, they have been _exceptionally_ slow in getting updated to ESM, import maps, etc. support). Will fiddle around more in the UI tests once I have a gap at some point to see if I can config my way out of it.

**Comment by josepot** [comment]
:wave: everyone!

First and foremost: I'm really sorry about this!

@jacogr is correct: `@substrate/connect` is a ESM only package. In fact, its most critical dependency (`@substrate/smoldot-light`) is also a ESM only package.

When I created the PR for adding the `ScProvider` I noticed that `@polkadot/rpc-provider` was defined as a `"type": "module"` and that made me think that it was fair game to add `@substrate/connect` as a dependency. Again, I'm very sorry about that! However, if I have to be completely honest, I'm still not 100% sure if I understand why it's problematic to have a ESM only dependency on [a ESM package](https://nodejs.org/docs/latest-v16.x/api/packages.html#type), but looking at the logs that have been shared I've noticed these lines:

> at Object.<anonymous> (/home/crystalin/projects/moonbeam-tools/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs:10:16)

and

> at Object.<anonymous> (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs:10:16)

which seem to suggest that when the `@polkadot/rpc-provider` is being built and published, it then gets converted to CJS? Is this what's happening?

On the other hand @jacogr about the issues that you are having with these tests:

> This is sadly creating some nightmares for me as well specifically in the apps UI (with the Jest tests) where ScProvider is actually used. Swapping to @polkadot/rpc-provider/ScProvider from the previous 0.5.0 version used there yields some interesting failures,

I would like to have a look at them, and try to figure out what the issue is. So, could you please send me a link to the repo where they are located so that I can try to reproduce the issues? Although, at a first glance, I think that mocking `@substrate/connect` [like we are doing here](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/substrate-connect/ScProvider.spec.ts#L155-L182) could do the trick?

Again, sorry about this, I'm sure that we will find a way to have the Provider for @substrate/connect without breaking everything :grimacing:

**Comment by jacogr** [comment]
Not your fault, small hiccups are expected along the way. Having the code in and not exporting it directly on the `@polkadot/rpc-provider` path but rather via `@polkadot/rpc-provider/substrate-connect` as in the latest patch does solve the problem. So breaking-the-world crisis is averted.

All `@polkadot` packages output both ESM and CJS (using export maps). While I certainly would like to skip CJS altogether, that would mean breaking a large part of the ecosystem - there are a lot of Node CJS-only programs using the `@polkadot` libs running out there, React Native has serious issues with ESM libs, ...

So that can is kicked down the road quite a bit. At some point the trigger will be pulled, but not yet today. Dual packaging is certainly not perfect and comes with it's own issues ("dual package hazard" springs to mind), but the choice for `@polkadot` is either to output CJS-only or ESM+CJS since we don't break userspace.

Will look at mocking when I have a gap, it would be perfect for the PR https://github.com/polkadot-js/apps/pull/7230

**Comment by TarikGul** [comment]
As an update as well, 7.14.2 does in fact fix our Jest issues! Thanks for the fix 🙏

**Comment by josepot** [comment]
FWIW the `7.14.2` release should also work nicely for the users of the `ScProvider`. The reason being that -as of today- using `@substrate/connect` on CJS doesn't make a lot of sense (b/c it currently wouldn't work on React Native anyways), and the ESM users can use it without any issues by importing the `ScProvider` via `import { ScProvider } from "@polkadot/rpc-provider/substrate-connect"`. Therefore,  for the time being, this fix is a really good compromise for everyone. So, thanks a lot @jacogr !
