### ISSUE TITLE
The performance will be very poor when using apiAt heavily.

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/api#4707]
This is the test code：

```javascript
const { WsProvider, ApiPromise } = require("@polkadot/api");

(async () => {
  const api = new ApiPromise({
    provider: new WsProvider("wss://rpc.polkadot.io/"),
  });

  await api.isReady;

  const blocks = 70;

  const blockHashes = await Promise.all(
    [...new Array(blocks)].map((_, index) =>
      api.rpc.chain.getBlockHash(index + 1)
    )
  );

  console.time("apiAt:");
  await Promise.all(blockHashes.map((blockHash) => api.at(blockHash)));
  console.timeEnd("apiAt:");

  process.exit(0);
})();
```

For 70 consecutive blocks, each block seems to fetch the metadata and create a new api object. Here's the result I got：

```
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
2022-03-31 16:00:52        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: No response received from RPC endpoint in 30s
```

Even if I reduce the number of concurrent requests, it will take several seconds.

Although I know that getting the metadata and decoding the metadata can be very time taking. But the fact is that the metadata for these blocks should be the same.

Wouldn't it be better to cache the api according to runtimeversion?

**Comment by jacogr** [comment]
It should check the runtime version first and find a match of exiting metadata. If not there is an issue. 

https://github.com/polkadot-js/api/blob/a98e9543b85c46a9cc56fe6f874e34d5ee3d69b4/packages/api/src/base/Init.ts#L156

**Comment by jacogr** [comment]
Looking at the above, while JS is simngle-threaded, it is indeed due to the parallel nature. One after the other and the above would indeed kick-in. There is actually 2 useful enhancements here to cater for this specific use:

1. Allow other chains to provide an `upgradeHistory`, e.g. for Kusama/Polkadot there is actually a shortcut for historic blocks that is maintained, e.g. https://github.com/polkadot-js/api/blob/a98e9543b85c46a9cc56fe6f874e34d5ee3d69b4/packages/types-known/src/upgrades/kusama.ts#L6 (kicks in on the line just above the one linked above)

2. The second part is more tricky - basically track open requests for a specific version and turn it into a promise. Basically if you know there is an open request for metadata for a specific version, then point to the same. It basically mirrors what happens here for the same blockHash into the version as well - https://github.com/polkadot-js/api/blob/a98e9543b85c46a9cc56fe6f874e34d5ee3d69b4/packages/api/src/base/Init.ts#L207

Overall though, the logic above works well to not duplicate when used in a serial fashion, but all at once would need a bit of love since requests don't cross-track (and quite a bit of testing to get right)

**Comment by ntduan** [comment]
thanks
