### ISSUE TITLE
Staking Menu Missing

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/api#4775]
> https://polkadot.js.org/apps/?rpc=wss://rpc.darwinia.network#/explorer

Might be similar to https://github.com/polkadot-js/api/issues/4740.
```
main.a6ce5405.js:19 Unable to create PalletStakingIndividualExposure type, disabling staking route
```

**Comment by jacogr** [comment]
It is on the apps UI itself. Sadly staking for non-known-shape Exposures is completely broken. In this case -

1. Nominees lists are not working at all
2. The staking.bond transaction on that chain is unusable with extra params

So the UI now has [explicit checks](https://github.com/polkadot-js/apps/blob/fb3e35118e1a25bf3e784e2a4bcbeec80f4416d5/packages/apps-routing/src/staking.ts#L15-L40) to ensure it only works with known shaped types and extrinsics which was driven by [this logged issue](https://github.com/polkadot-js/apps/issues/7449).

The alternative is that I need to continue chasing breakages and dealing with issue for unknown types that are not available in the editor and that I cannot test against any networks. This adds a massive amount of overhead to my life, basically touch staking and something somewhere breaks since it is not like-Substrate.
