### ISSUE TITLE
feature request: support import-blocks and export-blocks capabilities

### ISSUE THREAD

**Issue by onejoelman** [polkadot-js/api#4916]
Polkadot binary offers a feature of exporting blocks in binary format and json, as well as importing them afterwards.
Please port this feature to the official typescript api, enabling remote block submitting
Right now, I'm using a patch, running a bash command via ssh to do the following:
- shutdown polkadot instance
- call polkadot cli export blocks to temp file (```polkadot export-blocks --from ${from} --to ${to} --binary /temp/file```)
- stream the file
- delete the file
- re-launch polkadot instance

This seems to me a bit of a hack, and I'd be very happy if you could look into this feature.

Many thanks!
Joel

**Comment by jacogr** [comment]
The API only interacts with the exposed JSONRPC interfaces - https://polkadot.js.org/docs/substrate/rpc, not the binary itself.

**Comment by onejoelman** [comment]
ok thanks. I'll open an issue in their repo.
should I close this issue?

**Comment by jacogr** [comment]
You can open an issue with Substrate to add/expose and RPC - not sure how likely it is to be added, that would be up to the teams there to decide upon. (If it is ever added, it would probably be hidden behind an "unsafe" flag, since this operation would put a lot of load on the node itself, aka it won't be exposed by default)

**Comment by jacogr** [comment]
Closing, external to api.
