### ISSUE TITLE
Missed 

### ISSUE THREAD

**Issue by manylov** [polkadot-js/api#4917]
Hi, looks like api.rpc.chain.subscribeFinalizedHeads are missing some blocks. 
I've discovered it at the our node, then tested at the public node with the same result.

Here's the code: 
```
const { ApiPromise, WsProvider } = require('@polkadot/api')
const start = async () => {
  const wsProviderPublic = new WsProvider('wss://rpc.polkadot.io')

  const apiPublic = await ApiPromise.create({ provider: wsProviderPublic })

  apiPublic.rpc.chain.subscribeFinalizedHeads((header) => console.log(Date.now(), header.number.toNumber(), 'public'))
}

try {
  start().catch((error) => console.log('catch error', error))
} catch (error) {
  console.log('error:', error)
}
```

This is the output:

```
1654773821978 10668652 public
1654773826325 10668653 public
1654773834925 10668654 public
1654773839039 10668655 public
1654773852055 10668657 public
1654773864814 10668658 public
```

Block 10668656 has been missed. It happens every 20-30 blocks, sometimes 2 blocks missed.

**Comment by jacogr** [comment]
From how I know finalization to work, this is expected. It doesn't finalize one-by-one, but rather can do a whole tree. So basically, assume you have -

A - finalized
B - child of A, unfinalized
C - child of B, unfinalized

With the above you don't need to explicitly finalize B, if C gets finalized, B is finalized as well. (Since C builds on B). So effectively the finalization can happen in batched, you only need to do the latest one to finalize everything that it built upon.

This doesn't sit on the APIO layer, the API will return what the RPC returns.

**Comment by jacogr** [comment]
Closing as answered, Substrate related.
