### ISSUE TITLE
Get hash before signAndSend

### ISSUE THREAD

**Issue by A2DNEW** [polkadot-js/api#4918]
This is my code:

    const tx = await api.tx.balances.transfer(address, price);
    console.log(`hash1`, tx.hash.toHex());

    tx.signAndSend(newPair, (result: any) => {
        console.log("hash2", tx.hash.toHex());
        // and check status
    });

    // use hash for another function

I want to get hash before signAndSend, because I want to use it in another function.

But my code return different  hash for `hash1` and `hash2`

So, my code explain:

1- set transfer and get hash
2.1- signAndSend
2.2- use hash in another function

I don't want to use `await` for signAndSend. because I don't want to wait for it.

**Comment by jacogr** [comment]
The hash is over the full data - including the signature. Before it is signed, it is the signature of an unsigned extrinsic. So, yes, it will differ since it needs to be signed.

Look at `signAsync` to sign without sending. (And yes, you _need_ to wait for the result since it _needs_ to retrieve on-chain information to construct the payload)

**Comment by jacogr** [comment]
Closing, answered on SO.
