### ISSUE TITLE
BlockHash is not converted correctly

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4949]
When retrieving a BlockHash from block creation, none of the toXXX method allows to retrieve the correct value except toJSON().
See:
```
    const block = await api.rpc.engine.createBlock(true, finalize);

    console.log(`valids:`);
    console.log(block.toJSON());
    console.log(1, block.toJSON().hash.toString());
    console.log(`invalids:`);
    console.log(2, block.hash.toString());
    console.log(3, block.hash.toJSON());
    console.log(4, block.hash.toHex());
    console.log(5, Buffer.from(block.hash.toU8a()).toString("hex"));
    console.log(6, block.hash.toHuman());
```

prints:
```
valids:
{
  hash: '0x659939408abc33b6d91fcf13830cf2a848ed84ed36f4f22c24a1583ab7d82b98',
  aux: {
    headerOnly: false,
    clearJustificationRequests: false,
    needsJustification: false,
    badJustification: false,
    needsFinalityProof: false,
    isNewBest: true
  }
}
1 0x659939408abc33b6d91fcf13830cf2a848ed84ed36f4f22c24a1583ab7d82b98
invalids:
2 0x6468b70151a87b800130f138438a27c32e9ad1c9eeeff3125851726d2c5151f8
3 0x6468b70151a87b800130f138438a27c32e9ad1c9eeeff3125851726d2c5151f8
4 0x6468b70151a87b800130f138438a27c32e9ad1c9eeeff3125851726d2c5151f8
5 6468b70151a87b800130f138438a27c32e9ad1c9eeeff3125851726d2c5151f8
6 0x6468b70151a87b800130f138438a27c32e9ad1c9eeeff3125851726d2c5151f8
```

Only the first structure `block.toJSON()` output the correct hash

**Comment by jacogr** [comment]
This is a case of the definitions conflicting with the known properties that each `Codec` object exposes. So `.hash` is a built-in on each object which creates a hash over the data. In this case a conflicting field with the name `hash` won't be exposed over that already existing property.

The `.toJSON()` works since it gets the `.entries()` of the actual map, i.e. the original field. Basically internally it would do (using your variables) `block.get('hash')`.

In the runtime types, if this does happen, a field is added with an underscore, i.e. `hash_`, however since the RPC definitions are static and it doesn't have an actual mapping alias explicitly defined, it is only available via the `.get('hash')` on the map (or toJSON). There are some other types with the same collision that does add aliases, e.g. see https://github.com/polkadot-js/api/blob/0440ce606af7ab279c187a6dae2d67d307a789e1/packages/types/src/interfaces/eth/definitions.ts#L131-L136

**Comment by crystalin** [comment]
Thank you @jacogr
