### ISSUE TITLE
can't  to recognize  api  type annotations  for different  chain  at one project

### ISSUE THREAD

**Issue by cinlk** [polkadot-js/api#4969]
We have two substrate chain with different metadata, and generate each of  their  const,  query and  tx api   in same  declare (same namespace) module.  there are two same name storage method with different parameter type. 
for example chainA has this storage method definition as follow:
``` typescript
balance:{
    storageVersion: AugmentedQuery<ApiType, () => Observable<**ChainAType**>, []> & QueryableStorageEntry<ApiType, []>;
}

```
chainB storage method definition as follow:

``` typescript
balance: {
      storageVersion: AugmentedQuery<ApiType, () => Observable<**ChainBType**>, []> & QueryableStorageEntry<ApiType, []>;

}
```
 

When I want to use both of their api in one project and set the tsconfig.json  to apply 2 different api augmentations.
``` json
"paths": {
    "@polkadot/api-augment": [
      "./node_modules/@substrate/api-augment/chainA/index.d.ts",
     "./node_modules/@substrate/api-augment/chainB/index.d.ts"
     ],
} 
```
Initialing api  with chainB provider  find that  the "api.qeury.balance.storageVersion"   don't recognize  chainB's type  annotations, always use chainA's type annotations.

**Comment by jacogr** [comment]
Due to the way TS augmentation works (see [an article by DigitalOcean](https://www.digitalocean.com/community/tutorials/typescript-module-augmentation), [another HOWTO](https://isamatov.com/typescript-module-augmentation/) or the [official documentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), it would either -

- apply the latest, i.e. latest in wins
- may complain when there are parameter mismatches

This is not something solvable on the API layer. Augmentations in TS are alway additive.

**Comment by cinlk** [comment]
well, Any idea to solve this problem?  I think change TS declaration-merging  rules  is  not a good way

**Comment by jacogr** [comment]
There is no "solution", as mentioned above, not any changes that can be made not "not do this" - this is just how TS types are augmented, it tries to apply all and there is one winner.

**Comment by jacogr** [comment]
Closing, works as expected with TS, non api-related.
