### ISSUE TITLE
Error for mortal extrinsic "Invalid Transaction: Transaction has a bad signature"

### ISSUE THREAD

**Issue by arshtepe** [polkadot-js/api#5025]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

When I create immortal extrinsic, it works and I can submit the transaction
```
    const signerPayload = api.createType('SignerPayload', {
        address: sourceAddress,
        blockHash: api.genesisHash,
        blockNumber: 0,
        genesisHash: api.genesisHash,
        method: tx,
        nonce,
        tip: tx.tip,
        runtimeVersion: api.runtimeVersion,
        version: tx.version,
        eraPeriod: 1000064,
    });

    const signature = await signRaw(signerPayload.toRaw().data,....)
    const payload = signerPayload.toPayload();
    const ex = api.createType('Extrinsic', {method: signerPayload.method}, {version: signerPayload.version});
    ex.addSignature(payload.address, signature, payload);
    console.log(ex.toJSON())
```

but when I do it with the current block, it doesn't work ` author.submitExtrinsic
1010: Invalid Transaction: Transaction has a bad signature`

```
     const tx = await api.tx.proxy.removeProxy("[address]", 'Staking', '0');
    const {block} = await api.rpc.chain.getBlock()
    const nonce = await api.rpc.system.accountNextIndex(sourceAddress);
    const signerPayload = api.createType('SignerPayload', {
        address: sourceAddress,
        blockHash: block.header.hash,
        blockNumber: block.header.number,
        genesisHash: api.genesisHash,
        method: tx,
        nonce,
        tip: tx.tip,
        runtimeVersion: api.runtimeVersion,
        version: tx.version,
        eraPeriod: 1000064,
    });
 
//.....
```

* **Please tell us about your environment:**

  - Version: 8.10.1
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments available)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript
    - [ ] Other

**Comment by jacogr** [comment]
I would suggest you use the api.tx directly - these are not external interfaces, and it is really tricky to actually debug. Since it works with the API iotself, it means that your codse is incorrect - debugging that would take just as long as writing it. (So don't expect an answer to walk through your usage soon, if there is downtime I could take a look but it will be quite some time)

You can look at places such as the tools repo that use this type of interfaces, but apart from that it is a long slog to detect which params you are passing incorrectly.
