### ISSUE TITLE
Decode the default values using actual type

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#510]
The current implementation of metadata decoding decodes the `default` field of metadata storage functions assuming that they are `vec<u8>`, which they are.

But the `vec<u8>` actually represents something, so an additional layer of decoding needs to be done. Basically decode this `vec<u8>` using the `type` of the storage.

This additional decoding has been commented on purpose for now:
https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata/Modules.ts#L221-L230. It should be enabled when needed.

**Comment by jacogr** [comment]
We could also, in the API, do something like `new Type(returnedValue || meta.default)` - and keep it bytes? (Which may be cleaner and not need re-encoding inside the metadata parser)

**Comment by jacogr** [comment]
As discussed - instead of returning null in the rpc-core, we would -

- create type using the default bytes (when available)
- create empty type when default not available

Currently API users need to cater for value, null and undefined and this adds a lot of noise, rather just return the base default as/when there are no defaults.

**Comment by jacogr** [comment]
Will fix #142 as well
