### ISSUE TITLE
Release process.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#5146]
Hello @jacogr !

The purpose of this issue is mostly to ask if the releases for this repo and apps follow any criteria in terms of timing, quantity of changes committed to master etc.

Is there any recommended process for be aware about what is going to come in the next release (besides following the PRs merged to master of course)?

Thanks!

**Comment by jacogr** [comment]
polkadot-js follows a weekly release process. However this depends on stability (changes needed to be made) and oder in the "pyramid". So for pyramid, I refer to building blocks going higher level. This looks more-or-less like -

- wasm libs
- common libs
- api libs
- ui libs
- apps ui
- extension
- tools

So there is in reality, one person. So stuff gets prioritized. This means that stuff lower down the pyramid will always take priority to those above. So if there is an issue in the wasm libs, that means it would would (generally) get done first. This does also mean (7 days a week, 24 hrs a day) that not everything gets released weekly. Some stuff are "relatively" stable, e.g. wasm/common and their changes are on the smaller side and more infrequent, mostly.

Weekly API releases would be mostly in "minor point release form", since stuff like static metadata does change (tests, shipped generated types), this does mean "non patch".

Apps UI would get rolled into a release when there is enough stuff - there is a look each week to see if it makes sense. (It is not as critical since all merged gets put live immediately)

Extension is deemed mostly feature complete and moves like molasses on purpose - all merges gets used extensively locally first before it makes it out, aka I run the build from master branch and use it. (There is a huge lag with store approvals, so you cannot just "push a patch")
