### ISSUE TITLE
Send headers when set up WS(S) connection

### ISSUE THREAD

**Issue by pgolovkin** [polkadot-js/api#5279]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
When I'm using the WsProvider there is a constructor argument `headers`: ` constructor(endpoint?: string | string[], autoConnectMs?: number | false, headers?: Record<string, string>, timeout?: number);`
I'm passing header there 
`let result = new WsProvider(rpcUrl, 2000, {"Authorization": "1233"});`

And I don't see this header in the request. What may be wrong with it? Should additional information be added?

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

Polkadot rpc provider version is 9.5.2

**Comment by jacogr** [comment]
The browser `WebSockets` object does not support [headers in the constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). 

The functionality is only available on node.js (in this specific environment a library is used, Node does not have a built-in standard `WebSocket` object)

**Comment by pgolovkin** [comment]
Thank you!
Closing the issue.

**Comment by pgolovkin** [comment]
Sorry for reopening this issue.
It just came into my mind that it will be good to make developers able to provide WSS headers because some public RPC nodes have some headers limitation. Like Subsocial parachain allows only connection with headers `Origin: https://polkadot.js.org`. 
Being the open source and truly decentralised it will be nice to provide the ability for developers to make the integration code as flexible as possible.
If there is a limitation of the browser `WebSockets` built-in object isn't it a good idea to provide the custom Web Socket client to the WsProvider? In that case the developer may have a full control of the connection and make extra configuration needed for the specific RPC node.

**Comment by jacogr** [comment]
As far as possible, you always want to use the browser built-in objects. The same applies to Node/Deno - if there is a built-in object provided, it will always be used. We won't be replacing and/or maintaining custom WS objects where provided by the runtimes.

**Comment by pgolovkin** [comment]
In that case how the problem that I described may be solved? If some node doesn't accept WSS requests with `Origin` header I'm not able to use Polkadot JS provider for it.

**Comment by jacogr** [comment]
There is nothing code-wise we can do., There are 2 popular WebSocket packages -

- https://www.npmjs.com/package/ws
- https://www.npmjs.com/package/websocket

Both are Node.js only. Where it does provide a fallback for browsers (in the case of `ws`), it still uses the built-in engine `WebSocket` object. There are no "custom" WebSocket packages for the browser - the browser just does not expose the low-level APIs (unlike Node, which also allows C++ bindings) that would allow this to be created.

This is not a problem that the API can solve with the standard APIs available for `WebSocket`.

As an aside, due to the overwhelming popularity of `ws` vs `websocket`, the polyfill will also be swapped to that`ws` for Node environments. It has no header support.
