### ISSUE TITLE
Different versions have different method return values

### ISSUE THREAD

**Issue by moneohara** [polkadot-js/api#5292]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Different versions have different method return values

We are currently using v6.12.1 of polkadot.js.
After retrieving the latest block, when retrieving event information using the block information, the event information is returned in a way that is not expected.

An example of its use is shown below.

```
const { ApiPromise, HttpProvider } = require("@polkadot/api");

const httpProvider = new HttpProvider("Endpoints on the target server");
const apiPromise = await ApiPromise.create({ provider: httpProvider });

const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
const events = await api.query.system.events.at(blockHash);

console.log(JSON.stringify(events.toHuman()));
```
The results of running the above code in each version are shown below.

・v6.12.1(It will be an unanticipated form of event)
```
[
	{
		"phase": {
			"ApplyExtrinsic": "0"
		},
		"event": {
			"System": {
				"ExtrinsicSuccess": {
					"dispatchInfo": {
						"weight": {
							"refTime": "238,596,000"
						},
						"class": "Mandatory",
						"paysFee": "Yes"
					}
				}
			}
		},
		"topics": []
	},
	.....
```

・v7.15.1(Possible forms of events)
```
[
	{
		"phase": {
			"ApplyExtrinsic": "0"
		},
		"event": {
			"method": "ExtrinsicSuccess",
			"section": "system",
			"index": "0x0000",
			"data": [
				{
					"weight": {
						"refTime": "238,596,000"
					},
					"class": "Mandatory",
					"paysFee": "Yes"
				}
			]
		},
		"topics": []
	},
	......
```
Previously, v6.12.1 was able to retrieve events in the expected form, but recently events are being retrieved in a form other than the above-mentioned expected form.
Are there any updates that exist in previous versions of polkadot.js that would change the format of the response in past versions of polkadot.js?
Also, is the only way to solve the above problem is to upgrade polkadot.js?

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
@polkadot/api: 6.12.1

  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The ancient versions of the API does not support weights 1.5 (as used above) or the upcoming weight 2 (in the next Polkadot upgrade).

**Comment by moneohara** [comment]
@jacogr 
I am sorry, but I do not understand why the change in weights has anything to do with the API version.
If the weights change, does that mean that older versions will have incorrect response values?
Also, if the weights change, should we not use older versions of the API and keep them up to date?

**Comment by okmrs** [comment]
Sorry for cutting in, I am facing the same issue and have a question about API version and weights.

I couldn't find the infomation about the compatibility of API version and weights from any documentations like release notes(even though it might  be there).
Could you tell me where I should explore?

**Comment by okmrs** [comment]
Sorry for cutting in, I am facing the same issue and have a question about API version and weights.

I couldn't find the infomation about the compatibility of API version and weights from any documentations like release notes(even though it might be there).
Could you tell me where I should explore?

Hope your cooperation.

**Comment by okmrs** [comment]
Sorry for cutting in, I am facing the same issue and have a question about API version and weights.

I couldn't find the infomation about the compatibility of API version and weights from any documentations like release notes(even though it might be there).
Could you tell me where I should explore?

Hope your cooperation.

**Comment by okmrs** [comment]
Sorry for cutting in, I am facing the same issue and have a question about API version and weights.

In this release note, weight V1.5 is refered.
https://github.com/paritytech/polkadot/releases/tag/v0.9.29
So, now Polkadot(>= v0.9.29) is running with weight V1.5, right?

I couldn't make sense about the weights compatibility between Polkadot version and Polkadot-js version with any documentations.
Could you tell me where I should explore?

Hope your cooperation.

**Comment by okmrs** [comment]
@jacogr 
I understood there will be some non-backward compatible changes like this time, and should use latest version.
But I would appliciate if I could find out those changes in release notes.
e.g.) Response of `api.query.system.events.at` is now different between weights V1 and V2.

**Comment by jacogr** [comment]
It is not just Weights V1. Since the December API version you are using, Substrate have migrated all events to named events. This means that fields are named in newer versions of the runtimes. This information is conveyed in the metadata and that is what the API uses to decode it.

Basically in your version of the API predating named events, there is no support to correctly decode this into something that would make sense - hence having an "unanticipated" response. Full support for named events was added in [API 8.8.1](https://github.com/polkadot-js/api/releases/tag/v8.8.1) (which is when it was introduced in Substrate).

The API will always prioritize backwards compatibility and thus it will, with new changes to the runtime, always aim to provide data in a form that users that upgrade can recognize. This means that named events are still decoded to tuples (`toHuman()` obviously is different since it is a human, non-machine representation, so it adds richer info), Weights 1.5 will be converted to Weights V1 so there is one way of working with them (Weights V2 are different, since there are structures), etc.

This only works when the API is kept current. Older versions cannot anticipate the path that the runtimes will take in the future.

**Comment by okmrs** [comment]
@jacogr 
Appreciate detail. I will follow the latest full compatible version.
