### ISSUE TITLE
feature request: multi-call function in polkadot.js api by default

### ISSUE THREAD

**Issue by SamuraiT** [polkadot-js/api#5296]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
  - as far as I know, `api.queryMulti` doesn't support smart-contract interaction.
  - it should be available also with smart contract interaction 

for example, expected behavior would be something like 
```js
const aliceAddress = 'zxx...'
calls = [{
  address: 'zzz....', // contract address which has balanceOf function
  functionName: 'balanceOf',
  args: [aliceAddress]
},
{
  address: 'zxy....', // another contract address which has balanceOf function
  functionName: 'balanceOf',
  args: [aliceAddress]
}
]
const result = await api.queryMulti(calls)
console.log(result) // display the balances of zzz... and zxy.. token
```
c.f: https://github.com/makerdao/multicall

* **What is the motivation for changing the behavior?**
  - because most of the multicall would be made with smart contract, it should be supported

**Comment by SamuraiT** [comment]
thank you, @jacogr !
I see so there is no way to solve this other than creating multi-call smart-contract, right ?

**Comment by jacogr** [comment]
It is either -

- custom logic (not mapping to RPCs)
- doing it on the contracts layer (which is what your linked repo does on Ethereum)

It can only go into api-contracts and in all cases it would need to know the ABIs to make actual calls for option 1 (in the case of state, the metadata supplies all interfaces and multi-RPCs, so it can be a single step). Obviously your linked source uses the second option, since you have exactly the same ABI/RPC related issues elsewhere on contract platforms.
