### ISSUE TITLE
TS type generation support for Deno

### ISSUE THREAD

**Issue by jasl** [polkadot-js/api#5338]
I think this is a **feature request**

I'm trying Deno to replacing heavy Yarn nodejs app.

Generally Polkadot.js on Deno works great,
and I want to take advantage of typing,
it seems yet Polkadot.js typegen doesn't support Deno, or [the doc](https://polkadot.js.org/docs/api/examples/promise/typegen/)
doesn't cover Deno part.

Could you give some advice?

off topic question: I see https://github.com/polkadot-js/build-deno.land master synced latest v9.8.1, but not release this version for Deno, what's the releasing schedule for deno?

**Comment by jacogr** [comment]
Deno gets released when all the dependent packages are updated for the release cycle. (Since util was bumped this cycle, there are still a couple of outstanding packages that should be bumped before a release tag is made)

Typegen doesn't export for Deno. Augmentation for the included Polkadot, Kusama & Substrate _should_ work (or rather, used to at some point), but for augmented generation there is no support for Deno.

**Comment by jasl** [comment]
Thank you for clarify

**Comment by jacogr** [comment]
So generally, the package releases -

(we have dev, wasm, common, api, phishing, ui, extension, tools, apps - that is more-or-less the dependency tree)

- wasm, common generally goes Saturday (or early Sunday if delayed - these are non-weekly, but when available would go on these days)
- api generally goes on Sundays (after anything for the above is released - there may be patches mid-week in exceptional cases)
- phishing, ui, extension, tools generally goes on Mondays (if they do need a bump)
- apps a release is cut on Monday, sometime Tuesday if we run over

Browser bundles are auto-published to the repos, so no intervention there. Deno we generally try on Monday if all above is in place. (It all depends obviously on timing and finding the gaps to do the effort)
