### ISSUE TITLE
HTTP serve connection failed hyper::Error(Parse(Method))

### ISSUE THREAD

**Issue by rajqumar** [polkadot-js/api#5401]
I am getting this error on polkadot node logs `HTTP serve connection failed hyper::Error(Parse(Method))` when I am trying to connect from @polkadot/api using websockets

Polkadot Node Version: v0.9.36
@polkadot/api version: ^7.15.1

Logs from @polkadot/api
`REGISTRY: Unknown signed extensions CheckNonZeroSender found, treating them as no-effect
API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_root, mmr_verifyProof, mmr_verifyProofStateless, state_trieMigrationStatus, transaction_unstable_submitAndWatch, transaction_unstable_unwatch`

**Comment by jacogr** [comment]
The log from the API is correct - it is an information message that shows which RPCs and known on the node, but not known to the API. Same applies to the signed extension.

As for the Polkadot node logs, no idea. It is quite possible that due to your outdated version of the API it doesn't yet cater for the changes made when swapping to the jsonrpsee library on the node.

**Comment by rajqumar** [comment]
> The log from the API is correct - it is an information message that shows which RPCs and known on the node, but not known to the API. Same applies to the signed extension.
> 
> As for the Polkadot node logs, no idea. It is quite possible that due to your outdated version of the API (it is from April 2022) it doesn't yet cater for the changes made when the swap was made on Substrate to the jsonrpsee library.

How can I connect with my node and what version of @polkadot/api and nodejs should I use for the connection ? I am unable to connect.
