### ISSUE TITLE
Methods `generateBatchProof` and `generateProof` return the wrong type

### ISSUE THREAD

**Issue by en** [polkadot-js/api#5484]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

https://github.com/polkadot-js/api/blob/41d6429782e726334db5b760fcc40cb1605a116d/packages/rpc-augment/src/augment/jsonrpc.ts#L378-L382
`generateBatchProof` and `generateProof` incorrectly use each other's return values.

* **What is the motivation for changing the behavior?**

Swap the type of the return value.

* **Please tell us about your environment:**

  - Version: master
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The issue is that RPCs are completely unversioned. Sadly I cannot track all Substrate PRs.

So in these cases your best approach is actually to submit a PR. (These is actually one open to align with latest Substrate master, see https://github.com/polkadot-js/api/pull/5479)

(In retrospect, the mmr RPCs should not have been added at all - since it changes the whole time at this point and seems very unstable. Changing return types would mean that it would be broken on some older versions and working on newer versions - which is the reverse of what we have. So while we have "adjust-to-latest PRs", the best approach is actually just a complete removal until these are stabilized.)

**Comment by jacogr** [comment]
This is actually a duplicate as well, see https://github.com/polkadot-js/api/issues/5478
