### ISSUE TITLE
Ledger signature yielding Invalid Transaction: Transaction has a bad signature

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/api#5555]
- [x] Bug report
  - [x] Support request

Related [Stack Exchange](https://substrate.stackexchange.com/questions/7732/invalid-transaction-transaction-has-a-bad-signature-ledger-signature-into-tx) post.

I am not sure whether this is a bug or a mis-configuration - there have been firmware & app updates to Ledger - so this is being submitted as both a bug report and a support request.

I am attempting to submit a transaction using Polkadot JS API and a signature that has been signed by Ledger. Upon passing it to `send` I get the `Invalid Transaction: Transaction has a bad signature` error.

The payload is generated roughly as follows:

```
const lastHeader = await api.rpc.chain.getHeader();

const payload = {
        specVersion: api.runtimeVersion.specVersion.toHex(),
        transactionVersion: api.runtimeVersion.transactionVersion.toHex(),
        address: submitAddress,
        blockHash: lastHeader.hash.toHex(),
        blockNumber: lastHeader.number.toHex(),
        genesisHash: api.genesisHash.toHex(),
        method: api.createType('Call', tx).toHex(),
        nonce: tx.nonce.toHex(),
        signedExtensions: Object.values(
          api.registry.metadata.extrinsic.signedExtensions.toHuman() || {}
        ).map((e: any) => e.identifier),
        tip: tx.tip.toHex(),
        version: tx.version,
};

const raw = api.registry.createType('ExtrinsicPayload', payload);
```

The Ledger device is successfully generating a signature, using `@zondax/ledger-substrate-js`'s `sign` method. 

I am then injecting this signature into the `tx` like so:

```
tx.addSignature(from, hexAddPrefix(signature.toString('hex')));

const unsub = await tx.send(({ status, events = [] }: AnyApi) => {
   ...
});
```
This is yielding an error:
`RpcError: 1010: Invalid Transaction: Transaction has a bad signature`.

console logging `tx.toHuman()` after `addSignature` gives the following:

```
{
    "isSigned": true,
    "method": {
        "args": {
            "amount": "20,000,000,000",
            "pool_id": "15"
        },
        "method": "join",
        "section": "nominationPools"
    },
    "era": {
        "ImmortalEra": "0x00"
    },
    "nonce": "0",
    "signature": "0x4ce81c594615f5b0812b29f392081ae07fd65a142998fca1a2f9f81d67ded13098cd544689b401ca7c915b23ec6bf58a51aba7ba4eec51f7eb491f5af0c95b09",
    "signer": {
        "Id": "16F1ghy4bMr72BGyin7ryTxiQqJFJwpePsNJcZo1p6dUGVZT"
    },
    "tip": "0"
}
```

Older similar readings I have came across:
- https://github.com/polkadot-js/api/issues/4446
- https://github.com/polkadot-js/api/issues/3106

Thanks

**Comment by jacogr** [comment]
This is not a bug - the payload you are submitting to Ledger is not correct. Unlike other signers, Ledger only wants the payload (to sign) as would be submitted - no prefixes. Other signer all get a prefixed payload for parsing. (Ledger does parsing from the back, instead of the front, to work around not knowing the length of the transcation)

If you wish to do Ledger signing, I would most-probably look at the differences between the Ledger and normal signers, e.g. as the apps UI submits.

**Comment by rossbulat** [comment]
Thanks for the feedback, I been using Polkadot JS Apps as a reference for the payload, afaik it is an identical format to what PJS Apps is using.

I am logging payloads as they come into `signPayload` of [LedgerSigner](https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/signers/LedgerSigner.ts). i can see here that logging a payload comprises the same properties as what I am constructing. Here is an example taken from a nomination pool join extinsic, from LedgerSigner on JS Apps:

```
{
    "specVersion": "0x0000249a",
    "transactionVersion": "0x00000014",
    "address": "16F1ghy4bMr72BGyin7ryTxiQqJFJwpePsNJcZo1p6dUGVZT",
    "blockHash": "0xdc917c6ac86db54dbd4760c303462a5c9a988f089eb421e53e3d5a3008340c74",
    "blockNumber": "0x00e11aaa",
    "era": "0xa502",
    "genesisHash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
    "method": "0x27000700c817a8040f000000",
    "nonce": "0x00000000",
    "signedExtensions": [
        "CheckNonZeroSender",
        "CheckSpecVersion",
        "CheckTxVersion",
        "CheckGenesis",
        "CheckMortality",
        "CheckNonce",
        "CheckWeight",
        "ChargeTransactionPayment",
        "PrevalidateAttests"
    ],
    "tip": "0x00000000000000000000000000000000",
    "version": 4
}
```

Beyond my version using the immortal era, everything else is assumed to be of the same format. Here is a payload I am constructing, from the same nomination pools join call:

```
{
    "specVersion": "0x0000249a",
    "transactionVersion": "0x00000014",
    "address": "16F1ghy4bMr72BGyin7ryTxiQqJFJwpePsNJcZo1p6dUGVZT",
    "blockHash": "0xa296dc55c8ce8a8ba9093606d296dde21f11480b4d589c2369debcfdd0b402f7",
    "blockNumber": "0x00e11b16",
    "era": "0x00",
    "genesisHash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
    "method": "0x27000700c817a8040f000000",
    "nonce": "0x00000000",
    "signedExtensions": [
        "CheckNonZeroSender",
        "CheckSpecVersion",
        "CheckTxVersion",
        "CheckGenesis",
        "CheckMortality",
        "CheckNonce",
        "CheckWeight",
        "ChargeTransactionPayment",
        "PrevalidateAttests"
    ],
    "tip": "0x00000000000000000000000000000000",
    "version": 4
}
```

As per the JS Apps Ledger logic from [hw-ledger/src/bundle.ts. `sign`](https://github.com/polkadot-js/common/blob/4f5029118eb003041ff6c39c8336893a18590aee/packages/hw-ledger/src/bundle.ts#L77), we then format the payload:

```
const raw = api.registry.createType('ExtrinsicPayload', payload);
...

// Sign the payload on Ledger using a buffer:
const result = await polkadot.sign(
      LEDGER_DEFAULT_ACCOUNT + index,
      LEDGER_DEFAULT_CHANGE,
      LEDGER_DEFAULT_INDEX + 0,
      u8aToBuffer(payload.toU8a(true))
);

```
This successfully shows the method and args on the ledger device, with Approve and Reject. Once approve is clicked, the signature is returned & converted to hex in the same way that is being done [here](https://github.com/polkadot-js/common/blob/4f5029118eb003041ff6c39c8336893a18590aee/packages/hw-ledger/src/bundle.ts#L83).

```
 tx.addSignature(
      submitAddress,
      hexAddPrefix(txSignature.toString('hex'))
  );
```

I haven't been able to find where this `addSignature` part is done in JS Apps, and would assume that this is where the issue lies? This is where i log `tx.toHuman()` that displays the resultin object in the first post.

**Comment by TarikGul** [comment]
Interestingly enough, we recently had a similar issue where @marshacb was building out an integration with polkadot-js and wallet-connect. We encountered the same exact error to almost a tee @rossbulat. We had made sure to reproduce the behavior in a blank enviornment  to narrow down the root cause. We maintain txwrapper-core which is an "offline" signing library that wraps around polkadot-js so we were confused why we were getting issues because we just mirrored a lot of the signing functionality that we already have working. 

What ended up fixing the transactionPayload for us was just replicating some logic we had wrote way earlier in the past. It's [`defineMethod`](https://github.com/paritytech/txwrapper-core/blob/main/packages/txwrapper-core/src/core/method/defineMethod.ts#L100-L177) in `txwrapper-core`. It all uses polkadot-js so it's pretty simple to follow. We haven't found the root cause as of yet, but we were able to get the full workflow working last night after a few days of scratching our heads. 

(NOTE: @rossbulat - @marshacb was using your staking dashboard and the nominationPools to mock our workflow with wallet connect so I thought it was relevant here.) Happy to have @marshacb input more as well once we find the root cause.

**Comment by rossbulat** [comment]
> Interestingly enough, we recently had a similar issue where @marshacb was building out an integration with polkadot-js and wallet-connect. We encountered the same exact error to almost a tee @rossbulat. We had made sure to reproduce the behavior in a blank enviornment to narrow down the root cause. We maintain txwrapper-core which is an "offline" signing library that wraps around polkadot-js so we were confused why we were getting issues because we just mirrored a lot of the signing functionality that we already have working.
> 
> What ended up fixing the transactionPayload for us was just replicating some logic we had wrote way earlier in the past. It's [`defineMethod`](https://github.com/paritytech/txwrapper-core/blob/main/packages/txwrapper-core/src/core/method/defineMethod.ts#L100-L177) in `txwrapper-core`. It all uses polkadot-js so it's pretty simple to follow. We haven't found the root cause as of yet, but we were able to get the full workflow working last night after a few days of scratching our heads.
> 
> (NOTE: @rossbulat - @marshacb was using your staking dashboard and the nominationPools to mock our workflow with wallet connect so I thought it was relevant here.) Happy to have @marshacb input more as well once we find the root cause.
> 
> Edit: TL:DR It was a payload issue for us.

Thanks so much @TarikGul, I will attempt to reconstruct `defineMethod` and post a follow up shortly.

**Comment by TarikGul** [comment]
@rossbulat If you have any questions too, please feel free to reach out :)

**Comment by marshacb** [comment]
Hey @rossbulat, this may be anecdotal but I've been working on how to get the payload to work as is without `defineMethod` within the staking dashboard for our wallet connect integration and I've found two things that have helped. 

The first is helpful if you want to submit the extrinsic using the `api`'s `submitExtrinsic` method and involves explicitly creating the `era` type on the payload using the registry instead of using the hex value:

```
      const payload = {
        specVersion: specVersion.toHex(),
        transactionVersion: transactionVersion.toHex(),
        address,`,
        blockHash: blockHash.toHex(),
        blockNumber,
        era:  registry.createType('ExtrinsicEra', {
          current: blockNumber,
          period: 64,
        }),
        genesisHash: genesisHash.toHex(),
        method,
        nonce,
        signedExtensions: [
          'CheckNonZeroSender',
          'CheckSpecVersion',
          'CheckTxVersion',
          'CheckGenesis',
          'CheckMortality',
          'CheckNonce',
          'CheckWeight',
          'ChargeTransactionPayment',
        ],
        tip: '0x00000000000000000000000000000000',
        version: 4,
      };
```
This allowed me to successfully construct an `extrinsic`, call `addSignature` and call `submiteExtrinsic` on the api to submit the hex of the extrinsic as such: 

```
     const extrinsic = api.registry.createType(
        'Extrinsic',
        { method: method },
        { version: 4 }
      );
       extrinsic.addSignature(
         address,
         signature,
         payload
      );
      const hash = await api.rpc.author.submitExtrinsic(extrinsic.toHex());
```
The second thing is more pertaining to the post you made on stackexchange [here](https://substrate.stackexchange.com/questions/7732/invalid-transaction-transaction-has-a-bad-signature-ledger-signature-into-tx). We use the payload on the wallet side to construct the extrinsic payload and then sign to get the signature. So what I did was add the same`ExtrinsicPayload` based on that given payload as the third argument to `tx.addSignature`:
```
      const signingPayload = api.registry.createType(
        'ExtrinsicPayload',
        payload,
        {
          version: payload.version,
        }
      );
      tx.addSignature(address, signature, signingPayload);

      const unsub = await tx.send(({ status, events = [] }: AnyApi) => {
         ...
      });
```
Doing this for me got rid of the bad signature error and successfully submitted the transaction to the node. I hope this helps some. If you have any more questions about the process I took just let me know.

**Comment by rossbulat** [comment]
I can't overstate how helpful you have both been @marshacb, and @TarikGul, your pointers did the trick. I referred to `defineMethod`'s penultimate construction of the payload, and ensured `addSignature` was being used correctly re @marshacb's advice.

I am posting the correctly formatted payload and addSignature code on the Stack Exchange post now so others can discover it easier, and of course will refer to this issue too.
