### ISSUE TITLE
How to get the block hash using SubmittableExtrinsic.send()

### ISSUE THREAD

**Issue by nooxx** [polkadot-js/api#5567]
- [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
When sending a SubmittableExtrinsic (a signed raw transaction) I don't get an ISubmittableResult as expected in the callback, I get a Uint8Array.

```
await extrinsic.send((result) => {
     console.log(result);
});
```

<img width="318" alt="Screenshot 2023-03-30 at 15 47 16" src="https://user-images.githubusercontent.com/6512445/228856762-093bfc8e-b04c-4c41-a692-4b51804df232.png">

I expected to get an object from which I can find the status, block hash etc. As it is explained here
https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-send-an-unsigned-extrinsic

Thanks

  - Version: 10.2.1
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Which provider are you using - HTTP or WS?

On HTTP only the tx hash is returned. (Since it doesn't support subscriptions, it has no way of getting to the block hash - a subscription enables the retrieval of the in-block event)

So underlying we have this - https://github.com/polkadot-js/api/blob/4fd3289739e2d0b14eddf7590f729f17f49477cc/packages/api/src/submittable/createClass.ts#L187-L189

For the non-subscription interface (e.g. HTTP providers), the [author_submitExtrinsic](https://polkadot.js.org/docs/substrate/rpc#submitextrinsicextrinsic-extrinsic-hash) is used, for WS [author_submitAndWatch](https://polkadot.js.org/docs/substrate/rpc#submitandwatchextrinsicextrinsic-extrinsic-extrinsicstatus) is used.

**Comment by nooxx** [comment]
I'm using an HTTP provider. I will try with a WS provider thanks!
