### ISSUE TITLE
ApiPromise to use ApiRx internally

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#559]
Started in https://github.com/polkadot-js/api/pull/539, complete the loop

**Comment by ianhe8x** [comment]
I've some concerns regarding this change. For users who chose to use promise api, i believe it means they don't want rxjs as dependency as well. It would be more rational to me if the api package be split into api-promise and api-rx actually.

**Comment by amaurymartiny** [comment]
Even before this refactor (which is right now, since the refactor PR #566 is not merged yet), api-promise actually uses rxjs, via the rpc-rx dependency.

We did consider creating two branches, promise and rx, lower in the package dependencies tree. But, unless we introduce abstractions that make the code hard to understand, it unfortunately creates a lot of duplicate code between the 2 packages.

So instead, we decided to go with a leaner codebase, by using rxjs everywhere internally, and exposing a couple of interfaces (rx & promise for now, but other interfaces could be easily added) to the end user.

The end user does not need to know that we use rxjs internally of course. It might add up a bit in the final bundle size, compared to a pure promise package; but we made sure to add the smallest subset of rxjs into this codebase, so I don't think the added size is consequent. We have instead a more maintainable and customizable codebase, so I believe it's a reasonable trade-off.
