### ISSUE TITLE
Decoding seems slow

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5615]
Hi Jaco,

We are working on some of our scripts that are taking lot of time and one of them in particular is looping through all our system.accounts (> 1M accounts) and we realize that the slow parts seems to happen withing the PolkadotJS part:

For exemple querying data with curl:
```
curl -w@/home/ubuntu/.curl-time -o /dev/null -H "Content-Type: application/json" -d '{"id":12,"jsonrpc":"2.0","method":"state_getKeysPaged","params":["0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9",1000,"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9","0x7faba4348ae5cc48c6444fe1657d41c40dee8f245dd758a7daecad2e8d66c6fd"]}'  http://localhost:19944

    time_namelookup:  0.000026s
       time_connect:  0.000989s
    time_appconnect:  0.000000s
   time_pretransfer:  0.001044s
      time_redirect:  0.000000s
 time_starttransfer:  0.016760s
                    ----------
         time_total:  0.017167s
```
it takes 17ms, but when putting the logs around the js query:
```
smoke:balances Querying 1000-2000 +4ms
smoke:balances Done querying account: 1000-2000 +714ms
```
it takes 714ms (I also inspected and the CPU is at 99%)

Here is the loop I am doing:
```
const limit = 1000;
let last_key = "";
let count = 0;
    
while (true) {
      debug(`Querying ${count}-${count+limit} accounts`);
      const query = await apiAt.query.system.account.entriesPaged({
        args: [],
        pageSize: limit,
        startKey: last_key,
      });
      debug(`Done querying account: ${count}-${count+limit}`);

      if (query.length === 0) {
        break;
      }
      count += query.length;

      for (const user of query) {
        const accountId = `0x${user[0].toHex().slice(-40)}`;
        last_key = user[0].toString();
        accounts[accountId] = user[1];
      }
      if (count % (10 * limit) == 0) {
        debug(`Retrieved ${count} accounts`);
      }
    }
```

**Comment by crystalin** [comment]
Looking at the profiler, it is easy to see the parsing taking a lot of time:

Global chart of querying multiple batch of 1000 accounts:
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/329248/234781686-06a38056-4aa2-468a-9633-e2c71a1da309.png">

Looking at the details:
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/329248/234781875-c4116908-6e78-427f-9883-78092af12c0d.png">
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/329248/234782122-f251be80-7ca3-487c-9312-a29d734ed30b.png">


I included `moonbeam-loading-accounts.cpuprofile` (renamed on moonbeam-loading-accounts.txt for github) to load on the chrome profiler:
[moonbeam-loading-accounts.txt](https://github.com/polkadot-js/api/files/11340377/moonbeam-loading-accounts.txt)

**Comment by jacogr** [comment]
Just as a correction - `state_getKeysPaged` !== `entriesPaged `, it is rather `state_getKeysPaged + state_queryAt`. However, the point remains in that high CPU usage === decoding. (Low CPU usage would indicate a wait)

The API is first and foremost focussed on correctness. This doesn't mean that performance is not important - it is and always looking at some opportunities (obviously as time permits), so squeeze out and ounce or two. (Even so much so that I've actually been thinking of putting up my own funds for people who make PRs with a measurable impact on that area. There are certainly a lot on the left.)

The above seems to be (until the next one pops up), very much related not to parsing itself (or at least the first item on the last picture), but rather correctness checks, i.e. the pedantic check. Our all-time favorite -

"Decoded input doesn't match input, received 0x... (... bytes), created 0x... (... bytes)" 

This is actually/probably not that important anymore after metadata V14, i.e. types are "mostly", at least for storage, all specified via metadata - so nobody gets them incorrect. Could be useful to have that switched on/off via an API option.

**Comment by crystalin** [comment]
> This is actually/probably not that important anymore after metadata V14, i.e. types are "mostly", at least for storage, all specified via metadata - so nobody gets them incorrect. Could be useful to have that switched on/off via an API option.

I agree, this is definitely a good optimization to have. I'll try first hardcoding it to see if it works

**Comment by crystalin** [comment]
I did the test and removing the checkInstance help a bit, but there is still a significant part of the time spent in decoding the struct:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/329248/234915653-afe254bd-2f3a-4acf-b285-ba51534a1039.png">

**Comment by jacogr** [comment]
The specific (private fields) issue received a workaround in 10.5.1 on the back of https://github.com/polkadot-js/dev/pull/1029 (since the latest release the output is also es2022 which means the above work-around if technically not needed anymore, but most-probably still very useful for people who cross-compile to lower environments - so keeping in-place)

The investigation here was really excellent and pin-point. Feel free to open additional if more pops up.
