### ISSUE TITLE
Unable to decode storage scheduler.agenda

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5618]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The query param is 2075651, and the blockhash is query at is that of 2075650(0x1b268307bfec73be760aec6f017d7a7db704b6dbb2d135f635940df5b0f1961d).
![HQUCx1lurU](https://user-images.githubusercontent.com/2264908/235049684-b355c469-d803-4386-b722-f21ad7a337b9.jpg)

If I use node.js to query this storage, it produces following error:

```
Error: Unable to decode storage scheduler.agenda:: createType(Vec<Option<Scheduled>>):: Vec<Option<Scheduled>>:: Decoded input doesn't match input, received 0x0401013064656d6f63726163310000003f0d1c479981e6532920c5053f45ff18781e536e9d454490b95fdee1546035898bc3533100000000 (56 bytes), created 0x0401013064656d6f63726163310000003f0d1c479981e6532920c5053f45ff18781e536e9d454490b95fdee1546035898bc35331000000000000 (58 bytes)
```

I guess it's a decoding problem.

* **What is the motivation for changing the behavior?**

Decode history scheduler dispatched call correctly.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
There is an older scheduler type in addition to the one it tries to decode with. Specifically https://github.com/polkadot-js/api/blob/02b7807ba58326c47c28fa9b2fc93770641316fe/packages/types/src/interfaces/scheduler/definitions.ts#L16-L28

(As per the naming it was changed in Substrate runtime 254)

Currently there are no `Scheduler` type overrides for either Kusama or Polkadot. Type checnges on these just have not been tracked at all (unlike the stuff in there), see https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts

The issue if that I have no idea which runtimes the Substrate changes would map to at all. So it is exceptionally difficult to add these after the fact when I have not been tracking the changes to those.

I suppose it can be added to anything for the problematic runtime and those prior to that, which solves this one but would still be incorrect for runtimes just after than (since I don't have a line in the sand of when the Substrate-specific stuff went into anything else) and obviously also for Polkadot.
