### ISSUE TITLE
Support latest EthereumRuntimeRPCApi 

### ISSUE THREAD

**Issue by timbrinded** [polkadot-js/api#5679]
## **I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [X] Support request
  - [ ] Other

## **What is the current behavior and expected behavior?**

`EthereumRuntimeRPCApi` at [/types/src/interfaces/eth/runtime.ts](https://github.com/polkadot-js/api/blob/2235cbde19694a30a4369a78cc06aa76d5251050/packages/types/src/interfaces/eth/runtime.ts#L59) is for V4

Very recently frontier has been updated with a new RuntimeApi V5 as part of the WeightV2 changes:
https://github.com/paritytech/frontier/blob/master/primitives/rpc/src/lib.rs#L80

## **What is the motivation for changing the behavior?**

In order to provide types to all frontier based EVM chains that have been updated.

## **Please tell us about your environment:**

  - Version: `10.9.1`
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

 ## Additional Comments

I'm trying to understand the SDLC process a bit more with regards to the runtimeApis.

- How do the interfaces get updated - is it hand crafted or scraped by a script?

- How is versioning done between chains, for example if Astar's RT is on EthereumRuntimeRPCApiV4 but Moonbeam is on EthereumRuntimeRPCApiV5, will Astar be unable to use typegen package correctly if using the latest @polkadot/types pkg?

**Comment by jacogr** [comment]
1. It is currently hand-crafted. With metadata v15 this will be supplied as part of the metadata, so we will all be in a better position to not try and maintain these manually. (Obviously the existing would be kept since older chains and older runtimes would need to be supported, but at that point it won't be extended anymore)

2. No. All previous versions are part of the definitions. As part of the generation it checks the output from the getRuntimeVersion RPC and matches on that.

This is where the manual changes needs to be applied with the addition of the latest version (it only has V4, i.e. it doesn't go back further than that, so V5 "just" needs to be added additionally, e.g. here is an example of [BlockBuilder with versions 2, 3, 4, 5 & 6](https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/blockbuilder/runtime.ts)) - https://github.com/polkadot-js/api/blob/8282159f703a17d448c3bba8fa0ec5165209dfd6/packages/types/src/interfaces/eth/runtime.ts#L59-L72

**Comment by timbrinded** [comment]
ok @jacogr will raise a PR

**Comment by timbrinded** [comment]
Thanks @jacogr , am working on a PR for this now
