### ISSUE TITLE
Incorrect handling of revert flag in pallet-contracts query

### ISSUE THREAD

**Issue by TorstenStueber** [polkadot-js/api#5712]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

  When executing a query to pallet-contracts (e.g., `new ContractPromise(api, ..., ...).query(...)`), then the RPC call will return a value of type `ContractExecResult` (as defined [here](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/types/src/interfaces/contracts/types.ts#L73C18-L73C36)). This value is correctly scale decoded and will then be processed at [this part of the code](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/api-contract/src/base/Contract.ts#L150-L161). Here `result` is the actual payload of the return value and will be of type [`ContractExecResultResult`](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/types/src/interfaces/contracts/types.ts#L88). 
  
  If the query to the contract reverts, then the `result` will not be an `Error` but actually an `Ok` with internal value of type [`ContractExecResultOk`](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/types/src/interfaces/contracts/types.ts#L82) whose `flag` entry is set to 1, which is represents that the bitflag `isRevert` is true.
  
  In this case the [`data`](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/types/src/interfaces/contracts/types.ts#L84) entry of `ContractExecResultOk` is **not** supposed to be interpreted to be of the actual return type of the query message sent to the contract, instead it is meant to be interpreted as a type selector of a type referenced by the contract metadata declaration `lang_error` followed by the value of that type.
  
  This is currently [wrongly implemented](https://github.com/polkadot-js/api/blob/master/packages/api-contract/src/base/Contract.ts#L156-L157) as the value in `data` is decoded using the return value of the contract message independent and a possible REVERT flag is ignored.

* **What is the motivation for changing the behavior?**
  Correctly interpret messages that revert. This is particularly important for automated tests where some contracts are expected to revert and where the contained data value needs to be compared to an expected data value.

* **Please tell us about your environment:**
  - Version: current `master` branch that I link to in my explanation above (commit [d8136a8](https://github.com/polkadot-js/api/commit/d8136a8e61337d03fa156006cfbffee0a57c35d3))
  - Environment: not revelant
  - Language: not revelant

**Comment by xermicus** [comment]
I'm not too familiar with polkadot-js, but I'd assume that [this is not going to work](https://github.com/polkadot-js/api/blob/c028c6958211832bae5e5dda1868466a48195415/packages/api-contract/src/base/Contract.ts#L156-L157) for [Solang contracts](https://solang.readthedocs.io/en/v0.3.2/targets/polkadot.html#reverts-and-error-data-decoding). By my understaing, you're assuming that the execution output type is always the same, regardless whether the contract did revert or not right? Solidity contracts unfortunately can't really do this; Solidity doesn't know about `Result` and even if it would, the output could be empty (where Solidity doesn't know about the `Option` type neither), or the output could be of a type that isn't present in the metadata (due to Solidity bubbling up uncaught errors).

**Comment by TorstenStueber** [comment]
Seems that I incorrectly assumed that this is already standardized semantics of the contract metadata. But it is not and still [up to debate](https://github.com/paritytech/contracts-ui/issues/504#issuecomment-1690700066).

For that reason I will close this ticket for now.
