### ISSUE TITLE
Underlying storage for exposures has changed

### ISSUE THREAD

**Issue by Ank4n** [polkadot-js/api#5771]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
The `api.derive.staking._era_exposures(era)` under the hood calls `ErasStakersClipped`. This storage item would not be used anymore with the paged rewards changes ([PR link](https://github.com/paritytech/polkadot-sdk/pull/1189), [forum link](https://forum.polkadot.network/t/staking-update-paged-staking-reward-to-avoid-validator-oversubscription-issue-is-live-on-westend/5215)) and would be replaced with a new storage `ErasStakersPaged` which is a nmap of (Era, Validator, Page).

* **What is the motivation for changing the behavior?**
When runtime upgrades to [v1.4](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.4.0), this api would start breaking.

* **Suggest a motivation for the request or ideas how to implement the
addition or change**
There can be two apis, one to query how many pages of exposure exists which can be looked up by reading the storage item `ErasStakersOverview`. The current `_era_exposures` should then take a page index to read the exposure.

**Comment by TarikGul** [comment]
I'll be working on this soon and getting this supported/fixed Going to ensure there is compatibility for previous runtime versions as well so this doesn't act as a breaking change for some folks.

**Comment by TarikGul** [comment]
So i currently just made sure there is backwards and forward compatibility with `erasStakersPaged` for `_eraExposure`. I am going to create a tracking issue to remove `erasStakersClipped` once all relays have finally been updated to appropriate runtime.

Couple things:

> one to query how many pages of exposure exists which can be looked up by reading the storage item ErasStakersOverview

This already exists, the user can just use `api.query.staking.erasStakersOverview `

> The current _era_exposures should then take a page index to read the exposure.

With the current implementation this is not possible. Since `_eraExposure` is grabbing all the storageEntries using `.entries` the last storage entry arg is removed from the call. In this case that is `pageIndex`.

--------

On another note, https://github.com/polkadot-js/api/pull/5807 did augment the substrate types accordingly so the new storage calls are statically there for users.
