### ISSUE TITLE
Support new `ink!` contract events

### ISSUE THREAD

**Issue by ascjones** [polkadot-js/api#5789]
**I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

`ink!` events are changing in version `5.0`. See https://github.com/paritytech/ink/pull/1827, and https://use.ink/5.x/basics/events/.

The most important change is that there is a new field on each event definition in the metadata: `signature_topic` which must now be used to identify the type of event being received. Previously the index of the event i.e its position in the json array was used to determine which event to decode.

Now when handling an event, the first topic of the substrate event is matched to that signature topic in the metadata. If the event is anonymous, there is no signature topic in that case the raw hex bytes of the event can be returned and leave it up to the user what to do there.

Event decoding here: https://github.com/polkadot-js/api/blob/3bdf49b0428a62f16b3222b9a31bfefa43c1ca55/packages/api-contract/src/Abi/index.ts#L236

**Comment by cmichi** [comment]
I'm uploading a zip with two contracts here: [erc20-4.0-vs-5.0.zip](https://github.com/polkadot-js/api/files/14123501/erc20-4.0-vs-5.0.zip). It contains:

* ERC-20 with ink! 4.0
* ERC-20 with ink! 5.0

The diff comes down to

```diff
    "events": [
      {
        "args": [ ... ],
        "docs": [ ... ],
        "label": "...",
+       "module_path": "erc20::erc20",
+       "signature_topic": "0xb5b61a3e6a21a16be4f044b517c28ac692492f73c5bfd3f60178ad98c767f4cb"
      },
      ...
  ]
```

**Comment by cmichi** [comment]
@jacogr We would be very grateful if you could tackle this soonish. The context is that we're about to release ink! 5.0 and just now realized that `polkadot-js/api` needs to be updated.

**Comment by peetzweg** [comment]
Is this actually `ink!` specific? Would `ask!` and `solang` compiled contract emit events in the same way?

**Comment by ascjones** [comment]
> @ascjones Is this actually `ink!` specific? Would `ask!` and `solang` compiled contract emit events in the same way?

I'm not sure what the current state is, but we would expect them to emit events in this way in the future i.e. have the first topic be the signature topic and include that in the metadata. /cc @xermicus

**Comment by peetzweg** [comment]
Would be a bit of a hassle to not only treat contract compiled with different ink version differently but also languages. Is there something like an language overarching specification how pallet-contracts wasm contracts should behave?

**Comment by cmichi** [comment]
That's basically the ink! metadata. Solang & co just implement the same metadata format as ink!, Solang also uses the ink! crates for parts of that. I think Solang is still on the Metadata v4. 

When interpreting the metadata there should be no language-specific logic needed.

**Comment by xermicus** [comment]
Yes as soon as ink! 5.0 is released I'll keep Solang up and make a new release. As for the events, this shouldn't be any issue to adapt.

In general the metadata is mostly compatible. The only compromise so far is about how Solang Solidity contracts make use of `lang_error`, because the concepts of errors and error handling is fundamentally different between Solidity and ink!. We _might_ be able to solve this by [changing ink! metadata](https://github.com/paritytech/ink/issues/1841). Maybe it's also just way more pragramatic to just have some "special cases" instead of trying to make the ink! metadata format too generic (I don't have a hard opinion).  But this is the status quo already and not related to events, which I should be able to adapt in solang without problems.
