### ISSUE TITLE
Get rid of Globals and Singletons(Method injection, EventTypes injection, TypeRegistry)

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#580]
I believe you all agree that Metadata is a block scoped thing. But now in the code metadata and things derived from metadata are stored in the global scope. It brings conflict when, for example, feature of querying storage from specified block is added into api. Because metadata could be changed since that block and api is still trying to decode with the latest metadata.

Is there any plan to refactor that part? Or maybe I can try contribute that, even though it looks quite a large task.

**Comment by jacogr** [comment]
You are right that this is a non-trivial exercise. 

It practice it _should_ be relatively safe, since new events, methods, ... should generally be added as non-replacements, i.e. they don't clobber the indexes of previously defined values. (So new metadata can decode older blocks - breaking metadata in a backwards incompatible manner is generally a less than good idea, unless you do a chain refresh at that point). 

... Following this works great for chains such as Alexander and Charred Cherry, but probably not for any generic substrate chains that can be added where the same "don't break userspace" approach may not be in place.

It has been in the back of my mind for a long while, solving this elegantly, i.e. make sure you can decode anything new using the latest metadata (refresh transparently as it changes) vs. querying old blocks (where the issue would show up if non-backwards-compatible changes were made), I don't quite have an answer for.

**Comment by jacogr** [comment]
This one is critical though - https://github.com/polkadot-js/api/issues/449 (There is the subscribe metadata functions, we are not using it so we do fall behind on updates - so we break forward-compatibility)

**Comment by xlc** [comment]
Regards to compatibility with different runtime versions, I had some thoughts: https://github.com/paritytech/substrate/issues/1378

The idea solution to me is:
Implement codec metadata: https://github.com/paritytech/substrate/pull/1328
No more type registry is required as the metadata itself is enough to decode the types.
Trivial changes are no longer breaking (https://github.com/paritytech/substrate/pull/1373). How a value should be decoded is handled by the type metadata. The decoded result remain the same.
Adding fields (currently breaking) change can be automatically handled as long as the field is the last one.
Removing fields can also be automatically handled as long as the old field is optional / nullable.
Simple type change (e.g. U32 to U46) can be handled atomically, in the end they are all just BN.

It also enable feature detection and more advanced generic interface by knowing the exact structure of the runtime methods.

Similar idea can be applied to smart contract as well.

All I need is someone help me fix the HasCompact issue in my PR...

**Comment by jacogr** [comment]
Smart contracts won't have the ABI on-chain, however have been tracking that PR and the rest makes sense from a conceptual pov. (And solves the serious issue atm where stuff like Balances are actually hardcoded to a specific size, although it is configurable.)

Type registry won't actually go, it will just play a different role from the decoded meta. (It does not get rid of all the type definitions, but cleans it up considerably, e.g. an extrinsic has to be handled differently from a normal vec<u8> since it has a prefix in hex-mode, accounts have different text-representations)

**Comment by ianhe8x** [comment]
What if a dapp want to operate on multi-chains, which i believe is a goal of polkadot, then even if the metadata is backwards incompatible it won't work.

**Comment by jacogr** [comment]
Currently the API itself does not handle that case at all. But this really is a slippery slope and not trivial without multiple instances, i.e. most values operate as part of subscriptions (storage, etc), you just cannot get the meta for each result you retrieve to decode it alongside, it will kill the nodes with the number of queries going through.

What does make sense in those case is to have the globals on the API instance - and it some way, shape or form pass that through to the type decoders. (I/t still doesn't solve the "get a historic block issues", but keep metadata local to a per-chain instance.

**Comment by amaurymartiny** [comment]
Some ground work, which is _one_ way to solve this, is what was discussed in https://github.com/polkadot-js/api/pull/847#issuecomment-487560221, and is my preferred way.

The idea is to unify all type signatures.

Right now, our types' constructor have different signatures:
- `(value: Uint8Array|hex|JSON)` (U8, Text...)
- `(value: Uint8Array|hex|JSON, Type: TypeDef or Constructor)` (Option, Struct...)
- `(value: Uint8Array|hex|JSON, { meta: Metadata })` (Method, Event, Extrinsic...)
- etc

So the idea is for them to have all an unified signature.

My proposal:
- Make `Option`, `Struct`, `Vector` and some other Codec classes **abstract** classes. This is a breaking change:
```diff
- new Option(U64, 123); // not possible anymore
+ new Option.with(U64)(123); // should be like this everywhere
```
I think it reads better though.
- All Codec classes' constructor have the following signature:
```typescript
(value: Uint8Array|hex|JSON|whatever, options?: {[index: string]: any})
```
When we call `createType`, `createType('some string from Rust')` should return a `Constructor<Codec>`, whose constructor has the above signature.  `createType` will then pass the same `options` object to all types, and the types just take what they need. Some use cases:
```typescript
const A = createType('Option<u128>'); // returns Construcor<Option.with(U128)>
const a = new A(1234); // works

const m = new Method(Uint8Array.from([...]), { meta: api.runtimeMetadata }); // works
const m' = new Method(Uint8Array.from([...])); // should throw, because Method should require Metadata
```

For a start, I think this `options` object could contain at least 3 fields:
```
{
  metadata, // needed by Method
  typeRegistry, // goes along with Metadata
  networkId // used in Address.ts to set the address prefix
}
```

We pass that to all types, and the types, if they need something, they check `if options.someField` or throw.

---

next step would be to think how to pass metadata/typeRegistry/networkId to rpc-core. But the above can be done in a 1st step, and, apart from the breaking change above, should be okay.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/1592
