### ISSUE TITLE
Invalid static metadata v15 in `@polkadot/types-support`?

### ISSUE THREAD

**Issue by sinzii** [polkadot-js/api#6039]
Raw/hex static metadata should start with a scale-encoded prefix `0x6d657461` which is the [magic number prefix](https://github.com/paritytech/frame-metadata/blob/a07b2451b82809501fd797691046c1164f7e8840/frame-metadata/src/v14.rs#L30). This is no longer the case from `@polkadot/types-support >=v14.1.1`

So from `>=v14.1.1`, we no longer can decode the [static metadata v15](https://github.com/polkadot-js/api/blob/master/packages/types-support/src/metadata/v15/substrate-hex.ts):

![image](https://github.com/user-attachments/assets/b9ee1cfa-3808-42c5-a4be-75bc63a81563)

I'm not sure if this change is intentional, can you please check, thank you.

- `@polkadot/types-support@14.0.1`

![image](https://github.com/user-attachments/assets/9bf5774f-5cf0-40a1-85fa-7b9b72332565)

- `@polkadot/types-support@14.1.1`

![image](https://github.com/user-attachments/assets/fb1ca952-6e49-46fe-952c-b5c3b8529045)

**Comment by sinzii** [comment]
> This is because the Metadata for v15 is wrapped in an option.

Gotcha, this works to me. You probably fetch this via the runtime API: `metadata.metadataAtVersion`.

I'm not sure about others, but this change break the project that I'm working on after upgrading to the latest version, so not sure if you plan to unwrap the Option & the length part of the `OpaqueMetadata`, so the hex format will be consistant with other versions as well. Thanks.

**Comment by TarikGul** [comment]
> > This is because the Metadata for v15 is wrapped in an option.
> 
> Gotcha, this works to me. You probably fetch this via the runtime API: `metadata.metadataAtVersion`.
> 
> I'm not sure about others, but this change break the project that I'm working on after upgrading to the latest version, so not sure if you plan to unwrap the Option & the length part of the `OpaqueMetadata`, so the hex format will be consistent with other versions as well. Thanks.

As of now, I don't think it would make sense to change any of the metadatas in v15 to unwrapped since their original type from the node is `Option<OpaqueMetadata>`. I think the only one changed as you referenced above is `/v15/substrate-hex.ts`, but the rest of the chains that I added were `Option<OpaqueMetadata>` from the start. Apologies if changing the `/v15/substrate-hex.ts` caused issues (Truthfully i really thought it was just being used locally in PJS). But I think the current change is the best moving forward since it keeps in line with whats available on the node.

**Comment by sinzii** [comment]
That's fair, it's also minor to me and I can adapt to this change as well, thank you!
