### ISSUE TITLE
erasStakers is always empty, eraInfo method not documented?

### ISSUE THREAD

**Issue by dcolley** [polkadot-js/api#6042]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

```js
const era = (await api.query.staking.activeEra()).toJSON()
const v = "validatorstash";
const exposures = await api.query.staking.erasStakers(era.index, v);
console.debug(exposures)

// api.query.staking.erasStakers.entries() is also empty
```

* **What is the motivation for changing the behavior?**

This documentation says there should be an EraInfo object / function

`Note: Deprecated since v14. Use EraInfo instead to work with exposures.`

https://polkadot.js.org/docs/kusama/storage#erasstakersu32-accountid32-spstakingexposure

* **Please tell us about your environment:**

  - Version: nodejs: 20.2.0/ "@polkadot/api": "^14.3.1",
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
> Note: Deprecated since v14. Use EraInfo instead to work with exposures.

This is taken directly from the polkadot-sdk, so when it says `EraInfo` it is referring to the struct [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/lib.rs#L1049). This is specific to the storage for `pub type EraStakers`.

There not much correction we can do on the polkadot-js side since this is all just generated from the docs that are provided as part of the storage calls in the metadata.

The appropriate call you are looking for would be - `erasStakersPaged`, and `erasStakersOverview`.

**Comment by dcolley** [comment]
Thanks @TarikGul 

for anyone else who needs this:
```js
      var exposure = (await api.query.staking.erasStakersOverview(era.index, v)).toJSON();
      exposure.total = BigInt(exposure.total);
      exposure.own = BigInt(exposure.own);
      // console.log('exposure:', exposure);

      // validator other exposures
      exposure.others = [];
      for (let j = 0; j < exposure.pageCount; j++) {
        const exp = (await api.query.staking.erasStakersPaged(era.index, v, j)).toJSON();
        exp.others = exp.others.map((o) => {
          return {
            who: o.who,
            value: BigInt(o.value),
          };
        })
        exposure.others.push(...exp.others || []);
      }

```
