### ISSUE TITLE
Metadata parsing error with latest substrate

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#609]
I updated both substrate and polkadot.js apps to latest master, rebuild, purge chain, run with `--dev`.
When connected to the node, the metadata parsing logic ends up been an loop or something hangs Chrome and eventually crashed the page.
On my custom runtime it is able to parse metadata but many definitions are corrupted.

Possibly related: https://github.com/paritytech/substrate/issues/1495

I am going to do some investigation on this.

**Comment by xlc** [comment]
It seems substrate issue, but the codec still shouldn't hang the browser on corrupted data. i.e. when decode an (suppose be) array with non-sense length prefix, it should stop and throw decode error instead of attempting to create such array.

**Comment by jacogr** [comment]
Not sure how a "non-sensical length" is defined, lengths are applied everywhere from WASM data to small set timestamp extrinsics and is itself encoded in compact form. There is absolutely no do-some-not-others recovery strategy from these since everything relies on metadata.

Happy to listen to suggestions (in this case around the Text encoding, i.e. detect valid utf8). For now don't see what can/should be done here without concrete ideas since it deals with a very long bytes-only stream that should align to the definitions.

**Comment by xlc** [comment]
An easy heuristic is that if the length of the array is more than the size of the remaining data, it is definitely an error (unless array of `Unit` is allowed). This will provide a reasonable upper bound of the processing time / memory can be consumed by the decoder, which ensures it is less likely causing trouble (freeze browser or node.js process) on bad input.

Otherwise it is too easy to trick the sdk to decode an array of length of `Number.MAX_SAFE_INTEGER`
