### ISSUE TITLE
Allow to customize types for parachain

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#614]
I will like to modify the extrinsic type to make it take additional parameter. It is relatively easy to do on the substrate side however I don't see an easy to config it on polkadot.js side.

A possibility is provide a way (via type registry?) to allow user to override `Extrinsic` type with own implementation.

Similar requirement for Balance (U256 instead of U128).

substrate is designed to be very flexible and allow user to customize their chain, it will be good if polkadot.js is able to support similar level of flexibility.

Ideally, I will like to supply a json document describe all the customization about my chain, and have polkadot.js generates the api runtime based on the provided details. This json document could be hand crafted or generated by substrate (similar to metadata, but with complete information)

**Comment by jacogr** [comment]
`Extrinsic` is a difficult beast, e.g. submittables. At the same time it is designed (substrate-base), to be flexible, i.e. almost an anything goes approach, it is only `Bytes` (with a prefix). On this one would be interested to hear exactly what extensions are planned, it is worth-while keeping them in mind.

The other base types should be relatively straight-forward and possibly quite close already - the creation does the following when it creates a new type, `const Type = registry.get(value.type) || Types[value.type];` - effectively the registry provides an override. Where it does become a problematic area is in the case where other types extend these base types. (eg. `class Xyz extends Type` or struct defintions where it will fallback to the base types. Here it is a case of moving towards a "name definition" instead of "class use" type structure.

All-in-all, to have proper support is a bit off. However "some" support is either already in-place or can be done with some minor alterations.

**Comment by jacogr** [comment]
Closing due to #738
