### ISSUE TITLE
substrate breaking changes

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#618]
There are few breaking changes has been merged into substrate

- [ ] https://github.com/paritytech/substrate/pull/1522
- [ ] https://github.com/paritytech/substrate/pull/1499
- [ ] https://github.com/paritytech/substrate/pull/1507

polkadot.js needs to be updated regards to those changes

**Comment by jacogr** [comment]
- #1499 is not breaking - it comes back as `Compact<Type>` in the metadata, handled correctly (runtimes such as Polkadot still uses the HasCompact variant as well, so no cleanups unless the macro gets removed)

- #1522 is catered for by metadata, the Compact wrapping gets applied from that (see point above). There is a possibly breaking change with perbill/permill in Gav's bet toy

- #1507 We will only do once it is rolled out to the testnets (as a cleanup to remove the maps, not a high priority), polkadot.js caters for it as camelCase, so handles it transparently

**Comment by xlc** [comment]
Cool. I guess then my real issue is don't understand the rule to determine if a change is breaking or not. e.g. change method parameter is breaking, change to compact form is not.

**Comment by jacogr** [comment]
Yes, it is funny :) Metadata does break a lot of stuff - the new versioning one is very problematic - since basically all the masses of stuff in `types/src/Metadata` needs to be reworked and then there is the types-storage that is affected.

Anything passed through metadata as calls are fine - however, there are some very problematic cases, e.g. see this that was added - https://github.com/paritytech/substrate/blob/master/srml/balances/src/lib.rs#L134 - we completely got that wrong and had to map to `Address` (`::Source`) and `AccountId` (`::Target)

And then there are the waiting games - e.g. #1507 - typically we try and track when those are deployed on testnets and then make a move. (In some case it means some hacks to support both master and testnet versions)

I really appreciate the look though, the more eyes on things, the easier to make sure we are actually ahead and planned before stuff just falls apart :) It will get better... soon :)

**Comment by xlc** [comment]
The main trouble is I am maintain an internal testnet (which hopefully won't be internal soon), and I am merging and deploying latest changes from substrate and polkadot.js daily. I need to make sure the polkadot.js apps ui still works after the deployment. I am already quite a bit nervous now when pushing changes because they breaks quite often... 
But again I understand this is pre 1.0...

**Comment by jacogr** [comment]
You are nervous, I swear loudly :) The one worrying one is the metadata changes around the combination and versioning, probably need to make a start implementing that tomorrow since it is getting close.

Overall, the process is getting better since instead of just merging and not worrying about downstream, people are starting to ask questions around "will this affect" and think a bit more about API changes. Specifically because of the builders. 

However, rather be vigilant - in the JS side we also try and track the PRs, but if you spot _anything_ that could maybe even remotely have an impact, rather highlight if an issue is not logged, like here. (An example is #1507 - we have chatted about it in chat around "how", but there is not an issue logged here - there should be) 

But the last push for 1.0 is on, so most of the horrible changes are dying down.
