### ISSUE TITLE
Registering custom types and await ApiPromise.create

### ISSUE THREAD

**Issue by Noc2** [polkadot-js/api#771]
I just want to mention something I found strange when working with the @polkadot/api and registering custom types. For some reason `await ApiPromise.create({ types})` doesn’t work for me instead I need to use `getTypeRegistry().register(types);`

`await ApiPromise.create({ types})` creates the following errors in the chrome console:
`2019-03-13 16:39:17        RPC-CORE: getMetadata (block: Hash): Customtype:: Number can only safely store up to 53 bits
2019-03-13 16:39:17   API/DECORATOR: loadMeta a: getMetadata (block: Hash): Customtype:: Number can only safely store up to 53 bits`

**Comment by jacogr** [comment]
Thanks for the report. There is obviously an issue here, it should be handled properly by the API>

Do you have a sample of your types?

**Comment by Noc2** [comment]
This is the JSON: 
```
Metadata: 
{
ipfs_hash: 'Vec<u8>',
time: 'Moment',
license_code: 'u16',
price: 'Balance',
gateway: 'Vec<u8>',
meta_hash: 'Hash',
}
```

**Comment by jacogr** [comment]
Umpf, I think I see what goes wrong here - the `Metadata` type is used internally to retrieve the Metadata from the Node. (So your type registration overrides the default.) So basically I'm guessing you register after the API is created, so at that point it has the `Metadata` retrieve already, and things work.

We don't (yet) have a clear solution for overlapping types, it will get better with https://github.com/polkadot-js/api/pull/712 since 

(a) custom registration won't be needed
(b) there is some nice ideas for namespacing in there

So the only solution atm is -

1. change the substrate type name
2. API needs to change the metadata type to something else

**Comment by Noc2** [comment]
Yup. The metadata name is causing problems. I renamed it to metalog instead of metadata and everything works. Thanks

**Comment by jacogr** [comment]
Sorry about that one, it is not optimal at all :(
