### ISSUE TITLE
Cater for StorageDoubleMap for storage keys

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#776]
- Implemented in https://github.com/paritytech/substrate/pull/1918
- First used in substrate system events, https://github.com/paritytech/substrate/blob/master/srml/system/src/lib.rs#L331-L345

**Comment by jacogr** [comment]
And this now becomes V3 in the linked PR. (Didn't we _just_ do V2? ;))

**Comment by jacogr** [comment]
Will only revisit this if there are actual substrate PRs that use these types. For now, without proper tests, it will probably need a re-visit anyway if implemented right now (since testing cannot be done properly e2e without assumptions and/or writing sample Rust modules.)

**Comment by ianhe8x** [comment]
@jacogr During our works for supporting Double Map, there are some design decisions need your advice. Before, a StorageFunction can only have one key or none, therefore in [StorageKey.ts](https://github.com/polkadot-js/api/blob/facdbf8f3a4c7e9d528b14e7b03e89ff58b5ed09/packages/types/src/primitive/StorageKey.ts#L13) it is `(arg?: any): Uint8Array;`
Now with double map it adds another possibility. We could make it
```
(): Uint8Array;
(key: any): Uint8Array;
(key1: any, key2: any): Uint8Array;
```
which might be best for UX, but downside is we must also update other places where expects one key at most.
or we don't change interface, and use [key1, key2] for double map. 

We are working towards `[key1, key2]` approach for now unless you suggest otherwise.

**Comment by jacogr** [comment]
Ahh, yes, @amaurymartiny actually commented on that a while back. I would rather try the best-UX version first. From a API pov I think the `[key1, key2]` this is always slightly problematic, and a second choice.

Not 100% sure off-the-top of my head apart from StorageKey and types where the problems may come up. (decoration as well). It is generally relatively simple, the thing with multi-params is that the TS defs just become more and more hairy, i.e in some cases had to do this, excuse my language, crap - https://github.com/polkadot-js/api/blob/master/packages/api/src/types.ts#L112-L116

(Not pretty, but no real other option)

**Comment by jacogr** [comment]
Closing, thanks to the work by @AlexWZ0129
