### ISSUE TITLE
Era to be editable in ExtrinsicSignature and let the ExtrinsicSignature use era provided to it

### ISSUE THREAD

**Issue by KarishmaBothara** [polkadot-js/api#778]
Can we please have the era in ExtrinsicSignature editable and not 'read' only as we would like to pass era while constructing an extrinsic, not just while signing it.  

For example in an transaction
```
addAmount(amount, expire) {
  const tx = api.tx.XXX.addAmount(amount);
  const era = convertFromExpire(expire);
  (tx.signature as ExtrinsicSignature).era = era;
  return tx;
}
```

Also the sign method of ExtrinsicSignature, doesn't use its own era.. Can we have it to read its own era if it exist.

```
sign (method: Method, account: KeyringPair, { blockHash, era, nonce, version }: SignatureOptions): ExtrinsicSignature {
const signer = new Address(account.publicKey());
    const signingPayload = new SignaturePayload({
      nonce,
      method,
      **era: era || this.era || IMMORTAL_ERA,**
      blockHash
    });
    const signature = new Signature(signingPayload.sign(account, version as RuntimeVersion));
    return this.injectSignature(signature, signer, signingPayload.nonce, signingPayload.era);
  }

**Comment by jacogr** [comment]
Yes, it needs to be adapted to do exactly that, i.e. pull in the era specified. 

This is actually what the intent is behind https://github.com/polkadot-js/api/issues/756

(Closing this one since only need to track transaction eras in a single place, will explicitly refer to "passing the era" if we don't already do so in the linked issue)
