### ISSUE TITLE
Track nonce locally so it is possible to make multiple transactions in a single block

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#837]
Currently unless I track the nonce locally in my code and pass it to `signAndSend`, the second one is likely going to fail because the nonce value it used will be same as the first one.

polkadot.js should provide a way to track nonce for each account so we can make multiple transactions in a block.

Background:
We are implement a very simple faucet service, with a naive implementation it cannot handle two users requesting fund at same time due to nonce issue. And now the implementation is getting bit more complicated than I initially expected. I hope polkadot.js can shield us from those details.

Related but not dependent on: https://github.com/paritytech/substrate/issues/2263

**Comment by jacogr** [comment]
Nice approach for launching a new network.

I respectfully disagree that the API middleware should track this, it is going to get it wrong since it has no more info than the actual user of the API. In addition it is really trying to focus on interacting with the methods and providing the SCALE codec work around them, so it is really a connection and encoding/decoding layer.

The is has been a notoriously difficult problem to solve in blockchains, in the Parity Ethereum client a special (non-standard) [parity_nextNonce](https://wiki.parity.io/JSONRPC-parity-module#parity_nextnonce) is provided - it nicely tracks the actual local transaction queue, this info is really only available to the node.

Potential other approaches that you could investigate (but that will also break down at some point) -

- using a group of accounts to fund from (iterating over these)
- tracking it yourself (as you suggested the API does)

**Comment by xlc** [comment]
Make sense. Let’s see what will come out of https://github.com/paritytech/substrate/issues/2263

At minimum I think it make sense to have a receipt to show how to catch nonce issue when submitting transaction and retry with an updated new nonce. It won’t be optimal but good enough for most of the cases.

So this become a document issue that we should teach user how to handle nonce error.

**Comment by jacogr** [comment]
Def more open to either highlighting the issue (i.e. extract "this is a nonce error") or, as specified via a flag, handling it on the user's behalf with a retry. (Which could be tricky in itself, since things may be "stuck", so a retry won't pickup a new nonce)

But let's see if there is a node solution, if not, brainstorm some more.

**Comment by jacogr** [comment]
Closing, can re-open once there is a substrate solution to re-visit.
