### ISSUE TITLE
Use of `api.rpc.state.call`

### ISSUE THREAD

**Issue by adamdossa** [polkadot-js/api#840]
Trying to figure out how to use this / what it can be used for. The only real docs I can see are:
```
	/// Call a contract at a block's state.
	#[rpc(name = "state_call", alias("state_callAt"))]
	fn call(&self, name: String, bytes: Bytes, hash: Option<Hash>) -> Result<Bytes>;
```

and the test case:
```
#[test]
fn should_call_contract() {
	let core = ::tokio::runtime::Runtime::new().unwrap();
	let client = Arc::new(test_client::new());
	let genesis_hash = client.genesis_hash();
	let client = State::new(client, Subscriptions::new(core.executor()));

	assert_matches!(
		client.call("balanceOf".into(), Bytes(vec![1,2,3]), Some(genesis_hash).into()),
		Err(Error(ErrorKind::Client(client::error::ErrorKind::Execution(_)), _))
	)
}
```

any hints on how to use this? The test case looks like it's designed to fail.

**Comment by Stefie** [comment]
Hi @adamdossa you can find an implementations on the Polkadot Apps portal:
https://polkadot.js.org/apps/#/contracts
If you hover the questionmark on the top right you will get more info.

Here's the code for the frontend imlpementation: https://github.com/polkadot-js/apps/tree/master/packages/app-contracts/src

The contracts module is still under heavy development, but here's a link to the description of the current state of the module in the substrate repo 
https://github.com/paritytech/substrate/blob/b5b5c32895c046767827b8264f868e80b22965ad/srml/contract/src/lib.rs

I hope that helps!

**Comment by jacogr** [comment]
So a little history - `state_call` was actually one of the first RPCs ever added - you can trace the history of it back before the runtime was, well, an actual runtime. The architecture has changed a lot since then as well, both in terms or how information is retrieved and how information is submitted.

There are no current uses of this I could point you to atm. The source of truth is the Rust code, and have not had a need to use this in any of the projects I've been involved with.

(Contracts are separate, a specific srml module - only operational if you compile with a very recent version of the pDsl - there are some tweaks there, so it is still stabilizing)

**Comment by shawntabrizi** [comment]
I just used this RPC for the first time today. I used it to call a runtime API directly.

I created a new runtime API:

```
	impl pallet_identity::IdentityBenchmarks<Block> for Runtime {
		fn run_benchmarks() -> Vec<BenchmarkResults> {
			Identity::run_benchmarks()
		}
	}
```

And I was able to call this runtime API by calling with `name`:

```
IdentityBenchmarks_run_benchmarks
```
