### ISSUE TITLE
What is the syntax to declare a type `[u8; 16]`?

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#842]
How do I declare `[u8; 16]` type in the apps / settings / developer section?

I put this issue here instead of apps because I don't think type registry supports this.

**Comment by jacogr** [comment]
I don’t think we can. We do have U8aFixed, but if memory serves me right we actually o it cater for variable length atm. 

(And def an extension worth having, maybe the same syntax as used in the contracts, ABI? (The issue is new and logged around the array/Tuple for contracts, just on the mobile so cannot link directly)
