### ISSUE TITLE
Extrinsic hash generation mismatch

### ISSUE THREAD

**Issue by arjanz** [polkadot-js/api#954]
For Polkascan I'm trying to fix the determination of the extrinsic hash for older version of Substrate, by prefixing an additional Compact<u32> of the length of the extrinsic data. 

I'm testing this change, but I'm still experiencing a mismatch between the extrinsic hash generated by the polkadot-js. Also I noticed that every next balance transfer with the same amount and same destination result in the same extrinsic hash, but shouldn't the nonce also be included? 

Breakdown of an example in Alexander:

Block hash: `0x1f0d4ed338f2a0e511f68e79bb64c1389b2e770891a8dabe245cab91903c5ea5`

The 3rd item in the extrinsic data of the JSONRPC is a balance transfer signed by 5EGDZacWqkrmAariefaPY9XuUwbcijH6qWCWnUPoFeeSPXKF:

`0x81ff614029de73fbc23892b4955b8cfc7ab16a2589390991792ac5fa4e80f14ee988f69eb0d144ca1dc7b0cedad542e9826d2a95b771b75a49c53253602af4bfe9e6e431aef4d5444600b7b8ca2b45c160f7b3b8ee4344ee1a4f06bf929f7a96640900000300ff614029de73fbc23892b4955b8cfc7ab16a2589390991792ac5fa4e80f14ee988070010a5d4e8`

Length of extrinsic: 141

`Compact<u32> of 141: 0x3502`

Results in:

`0x350281ff614029de73fbc23892b4955b8cfc7ab16a2589390991792ac5fa4e80f14ee988f69eb0d144ca1dc7b0cedad542e9826d2a95b771b75a49c53253602af4bfe9e6e431aef4d5444600b7b8ca2b45c160f7b3b8ee4344ee1a4f06bf929f7a96640900000300ff614029de73fbc23892b4955b8cfc7ab16a2589390991792ac5fa4e80f14ee988070010a5d4e8`

Blake2b 32 bytes hash:

`0x65600ea74adef0870164b9ee7e69c6af6346c979ee9b819df4e2cf2b5aa6b728`

According to Polkadot-UI (with nonce 0):

`0x75c68b10493a63b09dd59e5f9111ce9d752f5c42646c33a55a6560381e05cc83`

Is this the correct way to determine the extrinsic hash when the length Compact<u32> is missing?

Arjan (Polkascan team)

**Comment by jacogr** [comment]
So it is quite possibly that the `extrinsic.hash` only hashes the method data, as opposed to everything. That would seem to match up with the experience since nonce it only included in the signature, not the actual Call/Method.

... looking as typing this ...

That doesn't seem to be the case, i.e. https://github.com/polkadot-js/api/blob/master/packages/types/src/type/Extrinsic.ts#L120-L124 - takes the fully encoded extrinsic (length, signature, method) and hashes that.

So looking at the example you provided, I get this - 

<img width="563" alt="Polkadot:Substrate Portal 2019-05-27 17-18-27" src="https://user-images.githubusercontent.com/1424473/58428676-81f74000-80a3-11e9-869c-9011289197a4.png">

Which also matches up with the raw data you provided and fed through https://polkadot.js.org/apps/#/toolbox/hash, i.e. in both cases the hash spat out is `0x65600ea74adef0870164b9ee7e69c6af6346c979ee9b819df4e2cf2b5aa6b728`

**Comment by arjanz** [comment]
Hi Jaco,

Thanks for the clarification, that was helpful. So in the end we generate the same hash, which is useful for example to one day generate links to Polkascan :)  

Actually I didn't check in the explorer tab (as I should), but I got confused when creating a balance transfer at https://polkadot.js.org/apps/#/transfer and I saw a different extrinsic hash before I was sending it to the network, maybe it uses a different way to generate?

**Comment by jacogr** [comment]
The one it generates there, is the unsigned hash. It can only be signed after generation, i.e. when clicking "sign" - at that point it will match. (And actually that display adds no real value, it is on the list to be removed)
