### ISSUE TITLE
False detection of duplicate

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/api#984]
Related to #795?

I have a main project depending on `@polkadot/api` v0.80.1 (polkabot)
This main project loads plugins. One plugin depends on `@polkadot/storage` v0.80.1

When the main project starts, I get the following error:
```
ExtError: Multiple versions of @polkadot/keyring detected, ensure that there is only version one in your dependency tree
    at assert (/Users/will/.../node_modules/@polkadot/util/assert.js:47:9)
```

Checking the 2 projects:

main project:
```
$ find node_modules/ -name 'keyring' | xargs -I {} cat {}/package.json | grep version
  "version": "0.91.1",
```

plugin:
```
$ find node_modules/ -name 'keyring' | xargs -I {} cat {}/package.json | grep version
  "version": "0.91.1",
```

So yes, both bring `@polkadot/keyring` in their dependency tree but the version is the same. Is that an issue with the check your are doing or something I can fix on my end?

**Comment by chevdor** [comment]
If anyone else runs into this issue, I for now got it out the way with:
```
sed -i '/function assertSingletonPackage(name) {/ a return' node_modules/@polkadot/util/assertSingletonPackage.js
```

I guess I should state that this 'fix' is NOT recommended for a production application.

**Comment by jacogr** [comment]
This is an issue, but actually the effects are quite horrible when it does pick up duplicates and uses then. There is a WIP approach to solve the keyring dep for api (https://github.com/polkadot-js/common/pull/416), however in the current form there is creates some very bad circular deps. So the idea is not a bad one, the implementation though is well, non-workable.

I would suggest making the plugin have a peerDep instead of a dep to keyring/api. (Since it is provided by main anyway)

**Comment by chevdor** [comment]
The issue is that I do not have any direct dep to KeyRing.

On one end it comes from @polkadot/api, on the other, in the plugin it comes from @polkadot/storage.

I will try making @polkadot/storage a peerDep but having to list all deps in the plugin host kinda defies the idea.

**Comment by chevdor** [comment]
Moreover, I just tested and it does not work. The only workaround so far is the one I mentioned above.

**Comment by jacogr** [comment]
Dependency removed in https://github.com/polkadot-js/api/pull/992
